// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBookingConversionRate = `-- name: GetBookingConversionRate :one
SELECT 
    COUNT(*) AS tong_booking,
    COUNT(*) FILTER (WHERE trang_thai = 'cho_xac_nhan') AS dang_cho,
    COUNT(*) FILTER (WHERE trang_thai = 'da_xac_nhan') AS da_xac_nhan,
    COUNT(*) FILTER (WHERE trang_thai = 'da_thanh_toan') AS da_thanh_toan,
    COUNT(*) FILTER (WHERE trang_thai = 'hoan_thanh') AS hoan_thanh,
    COUNT(*) FILTER (WHERE trang_thai = 'da_huy') AS da_huy,
    ROUND(
        COUNT(*) FILTER (WHERE trang_thai IN ('da_thanh_toan', 'hoan_thanh'))::DECIMAL / 
        NULLIF(COUNT(*), 0) * 100, 2
    ) AS ty_le_thanh_cong
FROM dat_cho
`

type GetBookingConversionRateRow struct {
	TongBooking   int64          `json:"tong_booking"`
	DangCho       int64          `json:"dang_cho"`
	DaXacNhan     int64          `json:"da_xac_nhan"`
	DaThanhToan   int64          `json:"da_thanh_toan"`
	HoanThanh     int64          `json:"hoan_thanh"`
	DaHuy         int64          `json:"da_huy"`
	TyLeThanhCong pgtype.Numeric `json:"ty_le_thanh_cong"`
}

// Tỷ lệ chuyển đổi booking
func (q *Queries) GetBookingConversionRate(ctx context.Context) (GetBookingConversionRateRow, error) {
	row := q.db.QueryRow(ctx, getBookingConversionRate)
	var i GetBookingConversionRateRow
	err := row.Scan(
		&i.TongBooking,
		&i.DangCho,
		&i.DaXacNhan,
		&i.DaThanhToan,
		&i.HoanThanh,
		&i.DaHuy,
		&i.TyLeThanhCong,
	)
	return i, err
}

const getBookingStatsByStatus = `-- name: GetBookingStatsByStatus :many

SELECT 
    trang_thai,
    COUNT(*) AS so_luong,
    COALESCE(SUM(tong_tien), 0) AS tong_tien
FROM dat_cho
GROUP BY trang_thai
ORDER BY so_luong DESC
`

type GetBookingStatsByStatusRow struct {
	TrangThai NullTrangThaiDatCho `json:"trang_thai"`
	SoLuong   int64               `json:"so_luong"`
	TongTien  interface{}         `json:"tong_tien"`
}

// =====================
// 4. BOOKING STATISTICS
// =====================
// Thống kê booking theo trạng thái
func (q *Queries) GetBookingStatsByStatus(ctx context.Context) ([]GetBookingStatsByStatusRow, error) {
	rows, err := q.db.Query(ctx, getBookingStatsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookingStatsByStatusRow
	for rows.Next() {
		var i GetBookingStatsByStatusRow
		if err := rows.Scan(&i.TrangThai, &i.SoLuong, &i.TongTien); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingsByDayOfWeek = `-- name: GetBookingsByDayOfWeek :many
SELECT 
    EXTRACT(DOW FROM ngay_dat) AS ngay_trong_tuan,
    CASE EXTRACT(DOW FROM ngay_dat)
        WHEN 0 THEN 'Chủ nhật'
        WHEN 1 THEN 'Thứ hai'
        WHEN 2 THEN 'Thứ ba'
        WHEN 3 THEN 'Thứ tư'
        WHEN 4 THEN 'Thứ năm'
        WHEN 5 THEN 'Thứ sáu'
        WHEN 6 THEN 'Thứ bảy'
    END AS ten_ngay,
    COUNT(*) AS so_booking,
    COALESCE(SUM(tong_tien), 0) AS doanh_thu
FROM dat_cho
WHERE trang_thai IN ('da_thanh_toan', 'hoan_thanh')
GROUP BY EXTRACT(DOW FROM ngay_dat)
ORDER BY ngay_trong_tuan
`

type GetBookingsByDayOfWeekRow struct {
	NgayTrongTuan pgtype.Numeric `json:"ngay_trong_tuan"`
	TenNgay       interface{}    `json:"ten_ngay"`
	SoBooking     int64          `json:"so_booking"`
	DoanhThu      interface{}    `json:"doanh_thu"`
}

// Thống kê booking theo ngày trong tuần
func (q *Queries) GetBookingsByDayOfWeek(ctx context.Context) ([]GetBookingsByDayOfWeekRow, error) {
	rows, err := q.db.Query(ctx, getBookingsByDayOfWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookingsByDayOfWeekRow
	for rows.Next() {
		var i GetBookingsByDayOfWeekRow
		if err := rows.Scan(
			&i.NgayTrongTuan,
			&i.TenNgay,
			&i.SoBooking,
			&i.DoanhThu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardOverview = `-- name: GetDashboardOverview :one


SELECT 
    (SELECT COUNT(*) FROM nguoi_dung WHERE dang_hoat_dong = TRUE) AS tong_nguoi_dung,
    (SELECT COUNT(*) FROM nguoi_dung WHERE dang_hoat_dong = TRUE AND vai_tro = 'khach_hang') AS tong_khach_hang,
    (SELECT COUNT(*) FROM nha_cung_cap) AS tong_nha_cung_cap,
    (SELECT COUNT(*) FROM tour WHERE dang_hoat_dong = TRUE) AS tong_tour,
    (SELECT COUNT(*) FROM tour WHERE dang_hoat_dong = TRUE AND trang_thai = 'cong_bo') AS tour_dang_hoat_dong,
    (SELECT COUNT(*) FROM dat_cho) AS tong_dat_cho,
    (SELECT COUNT(*) FROM dat_cho WHERE trang_thai = 'da_thanh_toan') AS dat_cho_da_thanh_toan,
    (SELECT COALESCE(SUM(tong_tien), 0) FROM dat_cho WHERE trang_thai IN ('da_thanh_toan', 'hoan_thanh')) AS tong_doanh_thu,
    (SELECT COALESCE(SUM(tong_tien), 0) FROM dat_cho 
     WHERE trang_thai IN ('da_thanh_toan', 'hoan_thanh') 
     AND DATE_TRUNC('month', ngay_dat) = DATE_TRUNC('month', CURRENT_DATE)) AS doanh_thu_thang_nay,
    (SELECT COUNT(*) FROM danh_gia WHERE dang_hoat_dong = TRUE) AS tong_danh_gia,
    (SELECT COALESCE(AVG(diem_danh_gia), 0) FROM danh_gia WHERE dang_hoat_dong = TRUE) AS diem_danh_gia_trung_binh
`

type GetDashboardOverviewRow struct {
	TongNguoiDung        int64       `json:"tong_nguoi_dung"`
	TongKhachHang        int64       `json:"tong_khach_hang"`
	TongNhaCungCap       int64       `json:"tong_nha_cung_cap"`
	TongTour             int64       `json:"tong_tour"`
	TourDangHoatDong     int64       `json:"tour_dang_hoat_dong"`
	TongDatCho           int64       `json:"tong_dat_cho"`
	DatChoDaThanhToan    int64       `json:"dat_cho_da_thanh_toan"`
	TongDoanhThu         interface{} `json:"tong_doanh_thu"`
	DoanhThuThangNay     interface{} `json:"doanh_thu_thang_nay"`
	TongDanhGia          int64       `json:"tong_danh_gia"`
	DiemDanhGiaTrungBinh interface{} `json:"diem_danh_gia_trung_binh"`
}

// ===========================================
// ADMIN STATISTICS QUERIES
// ===========================================
// =====================
// 1. DASHBOARD OVERVIEW
// =====================
// Tổng quan dashboard: tổng số người dùng, tour, booking, doanh thu
func (q *Queries) GetDashboardOverview(ctx context.Context) (GetDashboardOverviewRow, error) {
	row := q.db.QueryRow(ctx, getDashboardOverview)
	var i GetDashboardOverviewRow
	err := row.Scan(
		&i.TongNguoiDung,
		&i.TongKhachHang,
		&i.TongNhaCungCap,
		&i.TongTour,
		&i.TourDangHoatDong,
		&i.TongDatCho,
		&i.DatChoDaThanhToan,
		&i.TongDoanhThu,
		&i.DoanhThuThangNay,
		&i.TongDanhGia,
		&i.DiemDanhGiaTrungBinh,
	)
	return i, err
}

const getDashboardOverviewWithComparison = `-- name: GetDashboardOverviewWithComparison :one
SELECT 
    -- Tổng số
    (SELECT COUNT(*) FROM nguoi_dung WHERE dang_hoat_dong = TRUE) AS tong_nguoi_dung,
    (SELECT COUNT(*) FROM tour WHERE dang_hoat_dong = TRUE AND trang_thai = 'cong_bo') AS tong_tour,
    (SELECT COUNT(*) FROM dat_cho WHERE trang_thai IN ('da_thanh_toan', 'hoan_thanh')) AS tong_dat_cho_thanh_cong,
    
    -- Doanh thu tháng này
    (SELECT COALESCE(SUM(tong_tien), 0) FROM dat_cho 
     WHERE trang_thai IN ('da_thanh_toan', 'hoan_thanh') 
     AND DATE_TRUNC('month', ngay_dat) = DATE_TRUNC('month', CURRENT_DATE)) AS doanh_thu_thang_nay,
    
    -- Doanh thu tháng trước
    (SELECT COALESCE(SUM(tong_tien), 0) FROM dat_cho 
     WHERE trang_thai IN ('da_thanh_toan', 'hoan_thanh') 
     AND DATE_TRUNC('month', ngay_dat) = DATE_TRUNC('month', CURRENT_DATE - INTERVAL '1 month')) AS doanh_thu_thang_truoc,
    
    -- Người dùng mới tháng này
    (SELECT COUNT(*) FROM nguoi_dung 
     WHERE DATE_TRUNC('month', ngay_tao) = DATE_TRUNC('month', CURRENT_DATE)) AS nguoi_dung_moi_thang_nay,
    
    -- Người dùng mới tháng trước
    (SELECT COUNT(*) FROM nguoi_dung 
     WHERE DATE_TRUNC('month', ngay_tao) = DATE_TRUNC('month', CURRENT_DATE - INTERVAL '1 month')) AS nguoi_dung_moi_thang_truoc,
    
    -- Booking tháng này
    (SELECT COUNT(*) FROM dat_cho 
     WHERE DATE_TRUNC('month', ngay_dat) = DATE_TRUNC('month', CURRENT_DATE)) AS booking_thang_nay,
    
    -- Booking tháng trước
    (SELECT COUNT(*) FROM dat_cho 
     WHERE DATE_TRUNC('month', ngay_dat) = DATE_TRUNC('month', CURRENT_DATE - INTERVAL '1 month')) AS booking_thang_truoc
`

type GetDashboardOverviewWithComparisonRow struct {
	TongNguoiDung          int64       `json:"tong_nguoi_dung"`
	TongTour               int64       `json:"tong_tour"`
	TongDatChoThanhCong    int64       `json:"tong_dat_cho_thanh_cong"`
	DoanhThuThangNay       interface{} `json:"doanh_thu_thang_nay"`
	DoanhThuThangTruoc     interface{} `json:"doanh_thu_thang_truoc"`
	NguoiDungMoiThangNay   int64       `json:"nguoi_dung_moi_thang_nay"`
	NguoiDungMoiThangTruoc int64       `json:"nguoi_dung_moi_thang_truoc"`
	BookingThangNay        int64       `json:"booking_thang_nay"`
	BookingThangTruoc      int64       `json:"booking_thang_truoc"`
}

// Tổng quan dashboard với so sánh tháng trước
func (q *Queries) GetDashboardOverviewWithComparison(ctx context.Context) (GetDashboardOverviewWithComparisonRow, error) {
	row := q.db.QueryRow(ctx, getDashboardOverviewWithComparison)
	var i GetDashboardOverviewWithComparisonRow
	err := row.Scan(
		&i.TongNguoiDung,
		&i.TongTour,
		&i.TongDatChoThanhCong,
		&i.DoanhThuThangNay,
		&i.DoanhThuThangTruoc,
		&i.NguoiDungMoiThangNay,
		&i.NguoiDungMoiThangTruoc,
		&i.BookingThangNay,
		&i.BookingThangTruoc,
	)
	return i, err
}

const getDepartureCapacityStats = `-- name: GetDepartureCapacityStats :one
SELECT 
    COUNT(*) AS tong_khoi_hanh,
    SUM(suc_chua) AS tong_suc_chua,
    SUM(so_cho_da_dat) AS tong_da_dat,
    ROUND(
        SUM(so_cho_da_dat)::DECIMAL / NULLIF(SUM(suc_chua), 0) * 100, 2
    ) AS ty_le_lap_day
FROM khoi_hanh_tour
WHERE ngay_khoi_hanh >= CURRENT_DATE
  AND trang_thai IN ('len_lich', 'xac_nhan')
`

type GetDepartureCapacityStatsRow struct {
	TongKhoiHanh int64          `json:"tong_khoi_hanh"`
	TongSucChua  int64          `json:"tong_suc_chua"`
	TongDaDat    int64          `json:"tong_da_dat"`
	TyLeLapDay   pgtype.Numeric `json:"ty_le_lap_day"`
}

// Thống kê công suất khởi hành
func (q *Queries) GetDepartureCapacityStats(ctx context.Context) (GetDepartureCapacityStatsRow, error) {
	row := q.db.QueryRow(ctx, getDepartureCapacityStats)
	var i GetDepartureCapacityStatsRow
	err := row.Scan(
		&i.TongKhoiHanh,
		&i.TongSucChua,
		&i.TongDaDat,
		&i.TyLeLapDay,
	)
	return i, err
}

const getDeparturesByMonth = `-- name: GetDeparturesByMonth :many
SELECT 
    DATE_TRUNC('month', ngay_khoi_hanh) AS thang,
    COUNT(*) AS so_khoi_hanh,
    SUM(suc_chua) AS tong_suc_chua,
    SUM(so_cho_da_dat) AS tong_da_dat
FROM khoi_hanh_tour
WHERE ngay_khoi_hanh >= NOW() - INTERVAL '6 months'
  AND ngay_khoi_hanh <= NOW() + INTERVAL '6 months'
GROUP BY DATE_TRUNC('month', ngay_khoi_hanh)
ORDER BY thang ASC
`

type GetDeparturesByMonthRow struct {
	Thang       pgtype.Interval `json:"thang"`
	SoKhoiHanh  int64           `json:"so_khoi_hanh"`
	TongSucChua int64           `json:"tong_suc_chua"`
	TongDaDat   int64           `json:"tong_da_dat"`
}

// Khởi hành theo tháng
func (q *Queries) GetDeparturesByMonth(ctx context.Context) ([]GetDeparturesByMonthRow, error) {
	rows, err := q.db.Query(ctx, getDeparturesByMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeparturesByMonthRow
	for rows.Next() {
		var i GetDeparturesByMonthRow
		if err := rows.Scan(
			&i.Thang,
			&i.SoKhoiHanh,
			&i.TongSucChua,
			&i.TongDaDat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyReport = `-- name: GetMonthlyReport :one

SELECT 
    -- Doanh thu
    COALESCE(SUM(dc.tong_tien) FILTER (WHERE dc.trang_thai IN ('da_thanh_toan', 'hoan_thanh')), 0) AS doanh_thu,
    COUNT(dc.id) AS tong_booking,
    COUNT(dc.id) FILTER (WHERE dc.trang_thai IN ('da_thanh_toan', 'hoan_thanh')) AS booking_thanh_cong,
    COUNT(dc.id) FILTER (WHERE dc.trang_thai = 'da_huy') AS booking_huy,
    
    -- Người dùng mới
    (SELECT COUNT(*) FROM nguoi_dung 
     WHERE DATE_TRUNC('month', ngay_tao) = DATE_TRUNC('month', $1::DATE)) AS nguoi_dung_moi,
    
    -- Tour mới
    (SELECT COUNT(*) FROM tour 
     WHERE DATE_TRUNC('month', ngay_tao) = DATE_TRUNC('month', $1::DATE)) AS tour_moi,
    
    -- Đánh giá
    (SELECT COUNT(*) FROM danh_gia 
     WHERE DATE_TRUNC('month', ngay_tao) = DATE_TRUNC('month', $1::DATE) AND dang_hoat_dong = TRUE) AS danh_gia_moi,
    (SELECT COALESCE(AVG(diem_danh_gia), 0) FROM danh_gia 
     WHERE DATE_TRUNC('month', ngay_tao) = DATE_TRUNC('month', $1::DATE) AND dang_hoat_dong = TRUE) AS diem_danh_gia_trung_binh

FROM dat_cho dc
WHERE DATE_TRUNC('month', dc.ngay_dat) = DATE_TRUNC('month', $1::DATE)
`

type GetMonthlyReportRow struct {
	DoanhThu             interface{} `json:"doanh_thu"`
	TongBooking          int64       `json:"tong_booking"`
	BookingThanhCong     int64       `json:"booking_thanh_cong"`
	BookingHuy           int64       `json:"booking_huy"`
	NguoiDungMoi         int64       `json:"nguoi_dung_moi"`
	TourMoi              int64       `json:"tour_moi"`
	DanhGiaMoi           int64       `json:"danh_gia_moi"`
	DiemDanhGiaTrungBinh interface{} `json:"diem_danh_gia_trung_binh"`
}

// =====================
// 12. COMPREHENSIVE REPORTS
// =====================
// Báo cáo tháng
func (q *Queries) GetMonthlyReport(ctx context.Context, dollar_1 pgtype.Date) (GetMonthlyReportRow, error) {
	row := q.db.QueryRow(ctx, getMonthlyReport, dollar_1)
	var i GetMonthlyReportRow
	err := row.Scan(
		&i.DoanhThu,
		&i.TongBooking,
		&i.BookingThanhCong,
		&i.BookingHuy,
		&i.NguoiDungMoi,
		&i.TourMoi,
		&i.DanhGiaMoi,
		&i.DiemDanhGiaTrungBinh,
	)
	return i, err
}

const getMostFavoritedTours = `-- name: GetMostFavoritedTours :many

SELECT 
    t.id,
    t.tieu_de,
    t.gia_nguoi_lon,
    ncc.ten AS ten_nha_cung_cap,
    COUNT(tyt.id) AS so_yeu_thich,
    (SELECT duong_dan FROM anh_tour WHERE tour_id = t.id AND la_anh_chinh = TRUE LIMIT 1) AS anh_chinh
FROM tour t
LEFT JOIN tour_yeu_thich tyt ON t.id = tyt.tour_id
LEFT JOIN nha_cung_cap ncc ON t.nha_cung_cap_id = ncc.id
WHERE t.dang_hoat_dong = TRUE AND t.trang_thai = 'cong_bo'
GROUP BY t.id, t.tieu_de, t.gia_nguoi_lon, ncc.ten
ORDER BY so_yeu_thich DESC
LIMIT $1
`

type GetMostFavoritedToursRow struct {
	ID            int32          `json:"id"`
	TieuDe        string         `json:"tieu_de"`
	GiaNguoiLon   pgtype.Numeric `json:"gia_nguoi_lon"`
	TenNhaCungCap *string        `json:"ten_nha_cung_cap"`
	SoYeuThich    int64          `json:"so_yeu_thich"`
	AnhChinh      string         `json:"anh_chinh"`
}

// =====================
// 11. FAVORITES STATISTICS
// =====================
// Tours được yêu thích nhiều nhất
func (q *Queries) GetMostFavoritedTours(ctx context.Context, limit int32) ([]GetMostFavoritedToursRow, error) {
	rows, err := q.db.Query(ctx, getMostFavoritedTours, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMostFavoritedToursRow
	for rows.Next() {
		var i GetMostFavoritedToursRow
		if err := rows.Scan(
			&i.ID,
			&i.TieuDe,
			&i.GiaNguoiLon,
			&i.TenNhaCungCap,
			&i.SoYeuThich,
			&i.AnhChinh,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNewUsersToday = `-- name: GetNewUsersToday :one
SELECT 
    COUNT(*) AS nguoi_dung_moi_hom_nay,
    COUNT(*) FILTER (WHERE vai_tro = 'khach_hang') AS khach_hang_moi,
    COUNT(*) FILTER (WHERE vai_tro = 'nha_cung_cap') AS nha_cung_cap_moi
FROM nguoi_dung
WHERE DATE(ngay_tao) = CURRENT_DATE
`

type GetNewUsersTodayRow struct {
	NguoiDungMoiHomNay int64 `json:"nguoi_dung_moi_hom_nay"`
	KhachHangMoi       int64 `json:"khach_hang_moi"`
	NhaCungCapMoi      int64 `json:"nha_cung_cap_moi"`
}

// Số người dùng mới hôm nay
func (q *Queries) GetNewUsersToday(ctx context.Context) (GetNewUsersTodayRow, error) {
	row := q.db.QueryRow(ctx, getNewUsersToday)
	var i GetNewUsersTodayRow
	err := row.Scan(&i.NguoiDungMoiHomNay, &i.KhachHangMoi, &i.NhaCungCapMoi)
	return i, err
}

const getPaymentGatewayStats = `-- name: GetPaymentGatewayStats :many
SELECT 
    ctt.id AS cong_id,
    ctt.ten_hien_thi,
    COUNT(lsg.id) AS so_giao_dich,
    COALESCE(SUM(lsg.so_tien), 0) AS tong_tien,
    COUNT(*) FILTER (WHERE lsg.trang_thai = 'thanh_cong') AS thanh_cong,
    COUNT(*) FILTER (WHERE lsg.trang_thai = 'that_bai') AS that_bai
FROM cong_thanh_toan ctt
LEFT JOIN lich_su_giao_dich lsg ON ctt.id = lsg.cong_thanh_toan_id
GROUP BY ctt.id, ctt.ten_hien_thi
ORDER BY so_giao_dich DESC
`

type GetPaymentGatewayStatsRow struct {
	CongID     string      `json:"cong_id"`
	TenHienThi string      `json:"ten_hien_thi"`
	SoGiaoDich int64       `json:"so_giao_dich"`
	TongTien   interface{} `json:"tong_tien"`
	ThanhCong  int64       `json:"thanh_cong"`
	ThatBai    int64       `json:"that_bai"`
}

// Thống kê theo cổng thanh toán
func (q *Queries) GetPaymentGatewayStats(ctx context.Context) ([]GetPaymentGatewayStatsRow, error) {
	rows, err := q.db.Query(ctx, getPaymentGatewayStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaymentGatewayStatsRow
	for rows.Next() {
		var i GetPaymentGatewayStatsRow
		if err := rows.Scan(
			&i.CongID,
			&i.TenHienThi,
			&i.SoGiaoDich,
			&i.TongTien,
			&i.ThanhCong,
			&i.ThatBai,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentStatsByMethod = `-- name: GetPaymentStatsByMethod :many

SELECT 
    phuong_thuc_thanh_toan,
    COUNT(*) AS so_giao_dich,
    COALESCE(SUM(tong_tien), 0) AS tong_tien
FROM dat_cho
WHERE phuong_thuc_thanh_toan IS NOT NULL
  AND trang_thai IN ('da_thanh_toan', 'hoan_thanh')
GROUP BY phuong_thuc_thanh_toan
ORDER BY tong_tien DESC
`

type GetPaymentStatsByMethodRow struct {
	PhuongThucThanhToan *string     `json:"phuong_thuc_thanh_toan"`
	SoGiaoDich          int64       `json:"so_giao_dich"`
	TongTien            interface{} `json:"tong_tien"`
}

// =====================
// 5. PAYMENT STATISTICS
// =====================
// Thống kê thanh toán theo phương thức
func (q *Queries) GetPaymentStatsByMethod(ctx context.Context) ([]GetPaymentStatsByMethodRow, error) {
	rows, err := q.db.Query(ctx, getPaymentStatsByMethod)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaymentStatsByMethodRow
	for rows.Next() {
		var i GetPaymentStatsByMethodRow
		if err := rows.Scan(&i.PhuongThucThanhToan, &i.SoGiaoDich, &i.TongTien); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuarterlyReport = `-- name: GetQuarterlyReport :many
SELECT 
    EXTRACT(YEAR FROM ngay_dat) AS nam,
    EXTRACT(QUARTER FROM ngay_dat) AS quy,
    COUNT(*) AS tong_booking,
    COALESCE(SUM(tong_tien) FILTER (WHERE trang_thai IN ('da_thanh_toan', 'hoan_thanh')), 0) AS doanh_thu
FROM dat_cho
WHERE ngay_dat >= NOW() - INTERVAL '2 years'
GROUP BY EXTRACT(YEAR FROM ngay_dat), EXTRACT(QUARTER FROM ngay_dat)
ORDER BY nam ASC, quy ASC
`

type GetQuarterlyReportRow struct {
	Nam         pgtype.Numeric `json:"nam"`
	Quy         pgtype.Numeric `json:"quy"`
	TongBooking int64          `json:"tong_booking"`
	DoanhThu    interface{}    `json:"doanh_thu"`
}

// Báo cáo theo quý
func (q *Queries) GetQuarterlyReport(ctx context.Context) ([]GetQuarterlyReportRow, error) {
	rows, err := q.db.Query(ctx, getQuarterlyReport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuarterlyReportRow
	for rows.Next() {
		var i GetQuarterlyReportRow
		if err := rows.Scan(
			&i.Nam,
			&i.Quy,
			&i.TongBooking,
			&i.DoanhThu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentBookings = `-- name: GetRecentBookings :many
SELECT 
    dc.id,
    dc.ngay_dat,
    dc.tong_tien,
    dc.trang_thai,
    dc.so_nguoi_lon,
    dc.so_tre_em,
    nd.ho_ten AS ten_khach_hang,
    nd.email AS email_khach_hang,
    t.tieu_de AS ten_tour,
    kh.ngay_khoi_hanh
FROM dat_cho dc
JOIN nguoi_dung nd ON dc.nguoi_dung_id = nd.id
JOIN khoi_hanh_tour kh ON dc.khoi_hanh_id = kh.id
JOIN tour t ON kh.tour_id = t.id
ORDER BY dc.ngay_dat DESC
LIMIT $1
`

type GetRecentBookingsRow struct {
	ID             int32               `json:"id"`
	NgayDat        pgtype.Timestamp    `json:"ngay_dat"`
	TongTien       pgtype.Numeric      `json:"tong_tien"`
	TrangThai      NullTrangThaiDatCho `json:"trang_thai"`
	SoNguoiLon     *int32              `json:"so_nguoi_lon"`
	SoTreEm        *int32              `json:"so_tre_em"`
	TenKhachHang   string              `json:"ten_khach_hang"`
	EmailKhachHang string              `json:"email_khach_hang"`
	TenTour        string              `json:"ten_tour"`
	NgayKhoiHanh   pgtype.Date         `json:"ngay_khoi_hanh"`
}

// Booking gần đây
func (q *Queries) GetRecentBookings(ctx context.Context, limit int32) ([]GetRecentBookingsRow, error) {
	rows, err := q.db.Query(ctx, getRecentBookings, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentBookingsRow
	for rows.Next() {
		var i GetRecentBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.NgayDat,
			&i.TongTien,
			&i.TrangThai,
			&i.SoNguoiLon,
			&i.SoTreEm,
			&i.TenKhachHang,
			&i.EmailKhachHang,
			&i.TenTour,
			&i.NgayKhoiHanh,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentReviews = `-- name: GetRecentReviews :many
SELECT 
    dg.id,
    dg.diem_danh_gia,
    dg.tieu_de,
    dg.noi_dung,
    dg.ngay_tao,
    nd.ho_ten AS ten_nguoi_danh_gia,
    nd.email AS email_nguoi_danh_gia,
    t.tieu_de AS ten_tour
FROM danh_gia dg
JOIN nguoi_dung nd ON dg.nguoi_dung_id = nd.id
JOIN tour t ON dg.tour_id = t.id
WHERE dg.dang_hoat_dong = TRUE
ORDER BY dg.ngay_tao DESC
LIMIT $1
`

type GetRecentReviewsRow struct {
	ID                int32            `json:"id"`
	DiemDanhGia       int32            `json:"diem_danh_gia"`
	TieuDe            *string          `json:"tieu_de"`
	NoiDung           *string          `json:"noi_dung"`
	NgayTao           pgtype.Timestamp `json:"ngay_tao"`
	TenNguoiDanhGia   string           `json:"ten_nguoi_danh_gia"`
	EmailNguoiDanhGia string           `json:"email_nguoi_danh_gia"`
	TenTour           string           `json:"ten_tour"`
}

// Đánh giá gần đây
func (q *Queries) GetRecentReviews(ctx context.Context, limit int32) ([]GetRecentReviewsRow, error) {
	rows, err := q.db.Query(ctx, getRecentReviews, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentReviewsRow
	for rows.Next() {
		var i GetRecentReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.DiemDanhGia,
			&i.TieuDe,
			&i.NoiDung,
			&i.NgayTao,
			&i.TenNguoiDanhGia,
			&i.EmailNguoiDanhGia,
			&i.TenTour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueByDay = `-- name: GetRevenueByDay :many
SELECT 
    DATE(ngay_dat) AS ngay,
    COUNT(*) AS so_booking,
    COALESCE(SUM(tong_tien), 0) AS doanh_thu
FROM dat_cho
WHERE ngay_dat >= NOW() - INTERVAL '30 days'
  AND trang_thai IN ('da_thanh_toan', 'hoan_thanh')
GROUP BY DATE(ngay_dat)
ORDER BY ngay ASC
`

type GetRevenueByDayRow struct {
	Ngay      pgtype.Date `json:"ngay"`
	SoBooking int64       `json:"so_booking"`
	DoanhThu  interface{} `json:"doanh_thu"`
}

// Doanh thu theo ngày (30 ngày gần nhất)
func (q *Queries) GetRevenueByDay(ctx context.Context) ([]GetRevenueByDayRow, error) {
	rows, err := q.db.Query(ctx, getRevenueByDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevenueByDayRow
	for rows.Next() {
		var i GetRevenueByDayRow
		if err := rows.Scan(&i.Ngay, &i.SoBooking, &i.DoanhThu); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueByMonth = `-- name: GetRevenueByMonth :many
SELECT 
    DATE_TRUNC('month', ngay_dat) AS thang,
    COUNT(*) AS so_booking,
    COALESCE(SUM(tong_tien), 0) AS doanh_thu,
    COALESCE(AVG(tong_tien), 0) AS trung_binh_booking
FROM dat_cho
WHERE ngay_dat >= NOW() - INTERVAL '12 months'
  AND trang_thai IN ('da_thanh_toan', 'hoan_thanh')
GROUP BY DATE_TRUNC('month', ngay_dat)
ORDER BY thang ASC
`

type GetRevenueByMonthRow struct {
	Thang            pgtype.Interval `json:"thang"`
	SoBooking        int64           `json:"so_booking"`
	DoanhThu         interface{}     `json:"doanh_thu"`
	TrungBinhBooking interface{}     `json:"trung_binh_booking"`
}

// Doanh thu theo tháng (12 tháng gần nhất)
func (q *Queries) GetRevenueByMonth(ctx context.Context) ([]GetRevenueByMonthRow, error) {
	rows, err := q.db.Query(ctx, getRevenueByMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevenueByMonthRow
	for rows.Next() {
		var i GetRevenueByMonthRow
		if err := rows.Scan(
			&i.Thang,
			&i.SoBooking,
			&i.DoanhThu,
			&i.TrungBinhBooking,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueByYear = `-- name: GetRevenueByYear :many
SELECT 
    EXTRACT(YEAR FROM ngay_dat) AS nam,
    COUNT(*) AS so_booking,
    COALESCE(SUM(tong_tien), 0) AS doanh_thu
FROM dat_cho
WHERE trang_thai IN ('da_thanh_toan', 'hoan_thanh')
GROUP BY EXTRACT(YEAR FROM ngay_dat)
ORDER BY nam ASC
`

type GetRevenueByYearRow struct {
	Nam       pgtype.Numeric `json:"nam"`
	SoBooking int64          `json:"so_booking"`
	DoanhThu  interface{}    `json:"doanh_thu"`
}

// Doanh thu theo năm
func (q *Queries) GetRevenueByYear(ctx context.Context) ([]GetRevenueByYearRow, error) {
	rows, err := q.db.Query(ctx, getRevenueByYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevenueByYearRow
	for rows.Next() {
		var i GetRevenueByYearRow
		if err := rows.Scan(&i.Nam, &i.SoBooking, &i.DoanhThu); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewDistribution = `-- name: GetReviewDistribution :many
SELECT 
    diem_danh_gia,
    COUNT(*) AS so_luong,
    ROUND(COUNT(*)::DECIMAL / NULLIF((SELECT COUNT(*) FROM danh_gia WHERE dang_hoat_dong = TRUE), 0) * 100, 2) AS phan_tram
FROM danh_gia
WHERE dang_hoat_dong = TRUE
GROUP BY diem_danh_gia
ORDER BY diem_danh_gia DESC
`

type GetReviewDistributionRow struct {
	DiemDanhGia int32          `json:"diem_danh_gia"`
	SoLuong     int64          `json:"so_luong"`
	PhanTram    pgtype.Numeric `json:"phan_tram"`
}

// Phân bố đánh giá
func (q *Queries) GetReviewDistribution(ctx context.Context) ([]GetReviewDistributionRow, error) {
	rows, err := q.db.Query(ctx, getReviewDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReviewDistributionRow
	for rows.Next() {
		var i GetReviewDistributionRow
		if err := rows.Scan(&i.DiemDanhGia, &i.SoLuong, &i.PhanTram); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewStats = `-- name: GetReviewStats :one

SELECT 
    COUNT(*) AS tong_danh_gia,
    COALESCE(AVG(diem_danh_gia), 0) AS diem_trung_binh,
    COUNT(*) FILTER (WHERE diem_danh_gia = 5) AS so_5_sao,
    COUNT(*) FILTER (WHERE diem_danh_gia = 4) AS so_4_sao,
    COUNT(*) FILTER (WHERE diem_danh_gia = 3) AS so_3_sao,
    COUNT(*) FILTER (WHERE diem_danh_gia = 2) AS so_2_sao,
    COUNT(*) FILTER (WHERE diem_danh_gia = 1) AS so_1_sao
FROM danh_gia
WHERE dang_hoat_dong = TRUE
`

type GetReviewStatsRow struct {
	TongDanhGia   int64       `json:"tong_danh_gia"`
	DiemTrungBinh interface{} `json:"diem_trung_binh"`
	So5Sao        int64       `json:"so_5_sao"`
	So4Sao        int64       `json:"so_4_sao"`
	So3Sao        int64       `json:"so_3_sao"`
	So2Sao        int64       `json:"so_2_sao"`
	So1Sao        int64       `json:"so_1_sao"`
}

// =====================
// 7. REVIEW STATISTICS
// =====================
// Thống kê đánh giá tổng quan
func (q *Queries) GetReviewStats(ctx context.Context) (GetReviewStatsRow, error) {
	row := q.db.QueryRow(ctx, getReviewStats)
	var i GetReviewStatsRow
	err := row.Scan(
		&i.TongDanhGia,
		&i.DiemTrungBinh,
		&i.So5Sao,
		&i.So4Sao,
		&i.So3Sao,
		&i.So2Sao,
		&i.So1Sao,
	)
	return i, err
}

const getReviewsByMonth = `-- name: GetReviewsByMonth :many
SELECT 
    DATE_TRUNC('month', ngay_tao) AS thang,
    COUNT(*) AS so_luong,
    COALESCE(AVG(diem_danh_gia), 0) AS diem_trung_binh
FROM danh_gia
WHERE ngay_tao >= NOW() - INTERVAL '12 months'
  AND dang_hoat_dong = TRUE
GROUP BY DATE_TRUNC('month', ngay_tao)
ORDER BY thang ASC
`

type GetReviewsByMonthRow struct {
	Thang         pgtype.Interval `json:"thang"`
	SoLuong       int64           `json:"so_luong"`
	DiemTrungBinh interface{}     `json:"diem_trung_binh"`
}

// Đánh giá theo tháng
func (q *Queries) GetReviewsByMonth(ctx context.Context) ([]GetReviewsByMonthRow, error) {
	rows, err := q.db.Query(ctx, getReviewsByMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReviewsByMonthRow
	for rows.Next() {
		var i GetReviewsByMonthRow
		if err := rows.Scan(&i.Thang, &i.SoLuong, &i.DiemTrungBinh); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSupplierGrowthByMonth = `-- name: GetSupplierGrowthByMonth :many
SELECT 
    DATE_TRUNC('month', nd.ngay_tao) AS thang,
    COUNT(*) AS so_nha_cung_cap_moi
FROM nha_cung_cap ncc
JOIN nguoi_dung nd ON ncc.id = nd.id
WHERE nd.ngay_tao >= NOW() - INTERVAL '12 months'
GROUP BY DATE_TRUNC('month', nd.ngay_tao)
ORDER BY thang ASC
`

type GetSupplierGrowthByMonthRow struct {
	Thang           pgtype.Interval `json:"thang"`
	SoNhaCungCapMoi int64           `json:"so_nha_cung_cap_moi"`
}

// Tăng trưởng nhà cung cấp theo tháng
func (q *Queries) GetSupplierGrowthByMonth(ctx context.Context) ([]GetSupplierGrowthByMonthRow, error) {
	rows, err := q.db.Query(ctx, getSupplierGrowthByMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSupplierGrowthByMonthRow
	for rows.Next() {
		var i GetSupplierGrowthByMonthRow
		if err := rows.Scan(&i.Thang, &i.SoNhaCungCapMoi); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSupplierStats = `-- name: GetSupplierStats :one

SELECT 
    COUNT(*) AS tong_nha_cung_cap,
    (SELECT COUNT(*) FROM tour WHERE dang_hoat_dong = TRUE) AS tong_tour,
    (SELECT COUNT(*) FROM tour WHERE dang_hoat_dong = TRUE AND trang_thai = 'cong_bo') AS tour_dang_cong_bo
`

type GetSupplierStatsRow struct {
	TongNhaCungCap int64 `json:"tong_nha_cung_cap"`
	TongTour       int64 `json:"tong_tour"`
	TourDangCongBo int64 `json:"tour_dang_cong_bo"`
}

// =====================
// 6. SUPPLIER STATISTICS
// =====================
// Tổng quan nhà cung cấp
func (q *Queries) GetSupplierStats(ctx context.Context) (GetSupplierStatsRow, error) {
	row := q.db.QueryRow(ctx, getSupplierStats)
	var i GetSupplierStatsRow
	err := row.Scan(&i.TongNhaCungCap, &i.TongTour, &i.TourDangCongBo)
	return i, err
}

const getSystemActivity = `-- name: GetSystemActivity :many
SELECT 
    'booking' AS loai,
    dc.id AS id_doi_tuong,
    dc.ngay_dat AS thoi_gian,
    CONCAT('Booking mới #', dc.id, ' - ', t.tieu_de) AS mo_ta
FROM dat_cho dc
JOIN khoi_hanh_tour kh ON dc.khoi_hanh_id = kh.id
JOIN tour t ON kh.tour_id = t.id
WHERE dc.ngay_dat >= NOW() - INTERVAL '24 hours'

UNION ALL

SELECT 
    'user' AS loai,
    NULL AS id_doi_tuong,
    ngay_tao AS thoi_gian,
    CONCAT('Người dùng mới: ', ho_ten) AS mo_ta
FROM nguoi_dung
WHERE ngay_tao >= NOW() - INTERVAL '24 hours'

UNION ALL

SELECT 
    'review' AS loai,
    dg.id AS id_doi_tuong,
    dg.ngay_tao AS thoi_gian,
    CONCAT('Đánh giá mới ', dg.diem_danh_gia, ' sao cho tour: ', t.tieu_de) AS mo_ta
FROM danh_gia dg
JOIN tour t ON dg.tour_id = t.id
WHERE dg.ngay_tao >= NOW() - INTERVAL '24 hours'

ORDER BY thoi_gian DESC
LIMIT 50
`

type GetSystemActivityRow struct {
	Loai       string           `json:"loai"`
	IDDoiTuong int32            `json:"id_doi_tuong"`
	ThoiGian   pgtype.Timestamp `json:"thoi_gian"`
	MoTa       interface{}      `json:"mo_ta"`
}

// Hoạt động hệ thống gần đây
func (q *Queries) GetSystemActivity(ctx context.Context) ([]GetSystemActivityRow, error) {
	rows, err := q.db.Query(ctx, getSystemActivity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSystemActivityRow
	for rows.Next() {
		var i GetSystemActivityRow
		if err := rows.Scan(
			&i.Loai,
			&i.IDDoiTuong,
			&i.ThoiGian,
			&i.MoTa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopActiveUsers = `-- name: GetTopActiveUsers :many
SELECT 
    nd.id,
    nd.ho_ten,
    nd.email,
    COUNT(dc.id) AS so_booking,
    COALESCE(SUM(dc.tong_tien), 0) AS tong_chi_tieu
FROM nguoi_dung nd
LEFT JOIN dat_cho dc ON nd.id = dc.nguoi_dung_id
WHERE nd.vai_tro = 'khach_hang' AND nd.dang_hoat_dong = TRUE
GROUP BY nd.id, nd.ho_ten, nd.email
ORDER BY so_booking DESC
LIMIT 10
`

type GetTopActiveUsersRow struct {
	ID          pgtype.UUID `json:"id"`
	HoTen       string      `json:"ho_ten"`
	Email       string      `json:"email"`
	SoBooking   int64       `json:"so_booking"`
	TongChiTieu interface{} `json:"tong_chi_tieu"`
}

// Top người dùng hoạt động nhiều nhất (theo số booking)
func (q *Queries) GetTopActiveUsers(ctx context.Context) ([]GetTopActiveUsersRow, error) {
	rows, err := q.db.Query(ctx, getTopActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopActiveUsersRow
	for rows.Next() {
		var i GetTopActiveUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.HoTen,
			&i.Email,
			&i.SoBooking,
			&i.TongChiTieu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopBookedTours = `-- name: GetTopBookedTours :many
SELECT 
    t.id,
    t.tieu_de,
    t.gia_nguoi_lon,
    ncc.ten AS ten_nha_cung_cap,
    dmt.ten AS ten_danh_muc,
    COUNT(dc.id) AS so_booking,
    COALESCE(SUM(dc.tong_tien), 0) AS tong_doanh_thu,
    COALESCE(AVG(dg.diem_danh_gia), 0) AS diem_trung_binh,
    (SELECT duong_dan FROM anh_tour WHERE tour_id = t.id AND la_anh_chinh = TRUE LIMIT 1) AS anh_chinh
FROM tour t
LEFT JOIN dat_cho dc ON dc.khoi_hanh_id IN (SELECT id FROM khoi_hanh_tour WHERE tour_id = t.id)
LEFT JOIN nha_cung_cap ncc ON t.nha_cung_cap_id = ncc.id
LEFT JOIN danh_muc_tour dmt ON t.danh_muc_id = dmt.id
LEFT JOIN danh_gia dg ON t.id = dg.tour_id AND dg.dang_hoat_dong = TRUE
WHERE t.dang_hoat_dong = TRUE AND t.trang_thai = 'cong_bo'
GROUP BY t.id, t.tieu_de, t.gia_nguoi_lon, ncc.ten, dmt.ten
ORDER BY so_booking DESC
LIMIT $1
`

type GetTopBookedToursRow struct {
	ID            int32          `json:"id"`
	TieuDe        string         `json:"tieu_de"`
	GiaNguoiLon   pgtype.Numeric `json:"gia_nguoi_lon"`
	TenNhaCungCap *string        `json:"ten_nha_cung_cap"`
	TenDanhMuc    *string        `json:"ten_danh_muc"`
	SoBooking     int64          `json:"so_booking"`
	TongDoanhThu  interface{}    `json:"tong_doanh_thu"`
	DiemTrungBinh interface{}    `json:"diem_trung_binh"`
	AnhChinh      string         `json:"anh_chinh"`
}

// Top tours được đặt nhiều nhất
func (q *Queries) GetTopBookedTours(ctx context.Context, limit int32) ([]GetTopBookedToursRow, error) {
	rows, err := q.db.Query(ctx, getTopBookedTours, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopBookedToursRow
	for rows.Next() {
		var i GetTopBookedToursRow
		if err := rows.Scan(
			&i.ID,
			&i.TieuDe,
			&i.GiaNguoiLon,
			&i.TenNhaCungCap,
			&i.TenDanhMuc,
			&i.SoBooking,
			&i.TongDoanhThu,
			&i.DiemTrungBinh,
			&i.AnhChinh,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopDestinations = `-- name: GetTopDestinations :many

SELECT 
    dd.id,
    dd.ten,
    dd.tinh,
    dd.quoc_gia,
    dd.anh,
    COUNT(DISTINCT tdd.tour_id) AS so_tour,
    COALESCE(SUM(dc.tong_tien), 0) AS tong_doanh_thu
FROM diem_den dd
LEFT JOIN tour_diem_den tdd ON dd.id = tdd.diem_den_id
LEFT JOIN tour t ON tdd.tour_id = t.id AND t.dang_hoat_dong = TRUE
LEFT JOIN khoi_hanh_tour kh ON t.id = kh.tour_id
LEFT JOIN dat_cho dc ON kh.id = dc.khoi_hanh_id AND dc.trang_thai IN ('da_thanh_toan', 'hoan_thanh')
GROUP BY dd.id, dd.ten, dd.tinh, dd.quoc_gia, dd.anh
ORDER BY so_tour DESC
LIMIT $1
`

type GetTopDestinationsRow struct {
	ID           int32       `json:"id"`
	Ten          string      `json:"ten"`
	Tinh         *string     `json:"tinh"`
	QuocGia      *string     `json:"quoc_gia"`
	Anh          *string     `json:"anh"`
	SoTour       int64       `json:"so_tour"`
	TongDoanhThu interface{} `json:"tong_doanh_thu"`
}

// =====================
// 8. DESTINATION STATISTICS
// =====================
// Top điểm đến phổ biến
func (q *Queries) GetTopDestinations(ctx context.Context, limit int32) ([]GetTopDestinationsRow, error) {
	rows, err := q.db.Query(ctx, getTopDestinations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopDestinationsRow
	for rows.Next() {
		var i GetTopDestinationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ten,
			&i.Tinh,
			&i.QuocGia,
			&i.Anh,
			&i.SoTour,
			&i.TongDoanhThu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopSuppliersByRevenue = `-- name: GetTopSuppliersByRevenue :many
SELECT 
    ncc.id,
    ncc.ten,
    nd.email,
    ncc.logo,
    COUNT(DISTINCT t.id) AS so_tour,
    COUNT(dc.id) AS so_booking,
    COALESCE(SUM(dc.tong_tien), 0) AS tong_doanh_thu,
    COALESCE(AVG(dg.diem_danh_gia), 0) AS diem_trung_binh
FROM nha_cung_cap ncc
JOIN nguoi_dung nd ON ncc.id = nd.id
LEFT JOIN tour t ON ncc.id = t.nha_cung_cap_id AND t.dang_hoat_dong = TRUE
LEFT JOIN khoi_hanh_tour kh ON t.id = kh.tour_id
LEFT JOIN dat_cho dc ON kh.id = dc.khoi_hanh_id AND dc.trang_thai IN ('da_thanh_toan', 'hoan_thanh')
LEFT JOIN danh_gia dg ON t.id = dg.tour_id AND dg.dang_hoat_dong = TRUE
GROUP BY ncc.id, ncc.ten, nd.email, ncc.logo
ORDER BY tong_doanh_thu DESC
LIMIT $1
`

type GetTopSuppliersByRevenueRow struct {
	ID            pgtype.UUID `json:"id"`
	Ten           string      `json:"ten"`
	Email         string      `json:"email"`
	Logo          *string     `json:"logo"`
	SoTour        int64       `json:"so_tour"`
	SoBooking     int64       `json:"so_booking"`
	TongDoanhThu  interface{} `json:"tong_doanh_thu"`
	DiemTrungBinh interface{} `json:"diem_trung_binh"`
}

// Top nhà cung cấp theo doanh thu
func (q *Queries) GetTopSuppliersByRevenue(ctx context.Context, limit int32) ([]GetTopSuppliersByRevenueRow, error) {
	rows, err := q.db.Query(ctx, getTopSuppliersByRevenue, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopSuppliersByRevenueRow
	for rows.Next() {
		var i GetTopSuppliersByRevenueRow
		if err := rows.Scan(
			&i.ID,
			&i.Ten,
			&i.Email,
			&i.Logo,
			&i.SoTour,
			&i.SoBooking,
			&i.TongDoanhThu,
			&i.DiemTrungBinh,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopSuppliersByTours = `-- name: GetTopSuppliersByTours :many
SELECT 
    ncc.id,
    ncc.ten,
    nd.email,
    ncc.logo,
    COUNT(t.id) AS so_tour,
    COUNT(t.id) FILTER (WHERE t.trang_thai = 'cong_bo') AS tour_cong_bo,
    COUNT(t.id) FILTER (WHERE t.noi_bat = TRUE) AS tour_noi_bat
FROM nha_cung_cap ncc
JOIN nguoi_dung nd ON ncc.id = nd.id
LEFT JOIN tour t ON ncc.id = t.nha_cung_cap_id AND t.dang_hoat_dong = TRUE
GROUP BY ncc.id, ncc.ten, nd.email, ncc.logo
ORDER BY so_tour DESC
LIMIT $1
`

type GetTopSuppliersByToursRow struct {
	ID         pgtype.UUID `json:"id"`
	Ten        string      `json:"ten"`
	Email      string      `json:"email"`
	Logo       *string     `json:"logo"`
	SoTour     int64       `json:"so_tour"`
	TourCongBo int64       `json:"tour_cong_bo"`
	TourNoiBat int64       `json:"tour_noi_bat"`
}

// Top nhà cung cấp theo số tour
func (q *Queries) GetTopSuppliersByTours(ctx context.Context, limit int32) ([]GetTopSuppliersByToursRow, error) {
	rows, err := q.db.Query(ctx, getTopSuppliersByTours, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopSuppliersByToursRow
	for rows.Next() {
		var i GetTopSuppliersByToursRow
		if err := rows.Scan(
			&i.ID,
			&i.Ten,
			&i.Email,
			&i.Logo,
			&i.SoTour,
			&i.TourCongBo,
			&i.TourNoiBat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTourPriceDistribution = `-- name: GetTourPriceDistribution :many
SELECT 
    CASE 
        WHEN gia_nguoi_lon < 1000000 THEN 'Dưới 1 triệu'
        WHEN gia_nguoi_lon >= 1000000 AND gia_nguoi_lon < 3000000 THEN '1-3 triệu'
        WHEN gia_nguoi_lon >= 3000000 AND gia_nguoi_lon < 5000000 THEN '3-5 triệu'
        WHEN gia_nguoi_lon >= 5000000 AND gia_nguoi_lon < 10000000 THEN '5-10 triệu'
        ELSE 'Trên 10 triệu'
    END AS khoang_gia,
    COUNT(*) AS so_luong
FROM tour
WHERE dang_hoat_dong = TRUE AND trang_thai = 'cong_bo'
GROUP BY khoang_gia
ORDER BY 
    CASE khoang_gia
        WHEN 'Dưới 1 triệu' THEN 1
        WHEN '1-3 triệu' THEN 2
        WHEN '3-5 triệu' THEN 3
        WHEN '5-10 triệu' THEN 4
        ELSE 5
    END
`

type GetTourPriceDistributionRow struct {
	KhoangGia string `json:"khoang_gia"`
	SoLuong   int64  `json:"so_luong"`
}

// Phân bố giá tour
func (q *Queries) GetTourPriceDistribution(ctx context.Context) ([]GetTourPriceDistributionRow, error) {
	rows, err := q.db.Query(ctx, getTourPriceDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTourPriceDistributionRow
	for rows.Next() {
		var i GetTourPriceDistributionRow
		if err := rows.Scan(&i.KhoangGia, &i.SoLuong); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTourStatsByCategory = `-- name: GetTourStatsByCategory :many

SELECT 
    dmt.id AS danh_muc_id,
    dmt.ten AS ten_danh_muc,
    COUNT(t.id) AS tong_tour,
    COUNT(t.id) FILTER (WHERE t.trang_thai = 'cong_bo') AS tour_cong_bo,
    COUNT(t.id) FILTER (WHERE t.noi_bat = TRUE) AS tour_noi_bat,
    COALESCE(AVG(t.gia_nguoi_lon), 0) AS gia_trung_binh
FROM danh_muc_tour dmt
LEFT JOIN tour t ON dmt.id = t.danh_muc_id AND t.dang_hoat_dong = TRUE
GROUP BY dmt.id, dmt.ten
ORDER BY tong_tour DESC
`

type GetTourStatsByCategoryRow struct {
	DanhMucID    int32       `json:"danh_muc_id"`
	TenDanhMuc   string      `json:"ten_danh_muc"`
	TongTour     int64       `json:"tong_tour"`
	TourCongBo   int64       `json:"tour_cong_bo"`
	TourNoiBat   int64       `json:"tour_noi_bat"`
	GiaTrungBinh interface{} `json:"gia_trung_binh"`
}

// =====================
// 3. TOUR STATISTICS
// =====================
// Thống kê tour theo danh mục
func (q *Queries) GetTourStatsByCategory(ctx context.Context) ([]GetTourStatsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getTourStatsByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTourStatsByCategoryRow
	for rows.Next() {
		var i GetTourStatsByCategoryRow
		if err := rows.Scan(
			&i.DanhMucID,
			&i.TenDanhMuc,
			&i.TongTour,
			&i.TourCongBo,
			&i.TourNoiBat,
			&i.GiaTrungBinh,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTourStatsByStatus = `-- name: GetTourStatsByStatus :many
SELECT 
    trang_thai,
    COUNT(*) AS so_luong
FROM tour
WHERE dang_hoat_dong = TRUE
GROUP BY trang_thai
ORDER BY so_luong DESC
`

type GetTourStatsByStatusRow struct {
	TrangThai *string `json:"trang_thai"`
	SoLuong   int64   `json:"so_luong"`
}

// Thống kê tour theo trạng thái
func (q *Queries) GetTourStatsByStatus(ctx context.Context) ([]GetTourStatsByStatusRow, error) {
	rows, err := q.db.Query(ctx, getTourStatsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTourStatsByStatusRow
	for rows.Next() {
		var i GetTourStatsByStatusRow
		if err := rows.Scan(&i.TrangThai, &i.SoLuong); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getToursCreatedByMonth = `-- name: GetToursCreatedByMonth :many
SELECT 
    DATE_TRUNC('month', ngay_tao) AS thang,
    COUNT(*) AS so_luong
FROM tour
WHERE ngay_tao >= NOW() - INTERVAL '12 months'
GROUP BY DATE_TRUNC('month', ngay_tao)
ORDER BY thang ASC
`

type GetToursCreatedByMonthRow struct {
	Thang   pgtype.Interval `json:"thang"`
	SoLuong int64           `json:"so_luong"`
}

// Số tour mới theo tháng
func (q *Queries) GetToursCreatedByMonth(ctx context.Context) ([]GetToursCreatedByMonthRow, error) {
	rows, err := q.db.Query(ctx, getToursCreatedByMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetToursCreatedByMonthRow
	for rows.Next() {
		var i GetToursCreatedByMonthRow
		if err := rows.Scan(&i.Thang, &i.SoLuong); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getToursWithLowestRating = `-- name: GetToursWithLowestRating :many
SELECT 
    t.id,
    t.tieu_de,
    ncc.ten AS ten_nha_cung_cap,
    COUNT(dg.id) AS so_danh_gia,
    COALESCE(AVG(dg.diem_danh_gia), 0) AS diem_trung_binh
FROM tour t
LEFT JOIN danh_gia dg ON t.id = dg.tour_id AND dg.dang_hoat_dong = TRUE
LEFT JOIN nha_cung_cap ncc ON t.nha_cung_cap_id = ncc.id
WHERE t.dang_hoat_dong = TRUE
GROUP BY t.id, t.tieu_de, ncc.ten
HAVING COUNT(dg.id) > 0
ORDER BY diem_trung_binh ASC
LIMIT $1
`

type GetToursWithLowestRatingRow struct {
	ID            int32       `json:"id"`
	TieuDe        string      `json:"tieu_de"`
	TenNhaCungCap *string     `json:"ten_nha_cung_cap"`
	SoDanhGia     int64       `json:"so_danh_gia"`
	DiemTrungBinh interface{} `json:"diem_trung_binh"`
}

// Tours có điểm đánh giá thấp nhất (cần cải thiện)
func (q *Queries) GetToursWithLowestRating(ctx context.Context, limit int32) ([]GetToursWithLowestRatingRow, error) {
	rows, err := q.db.Query(ctx, getToursWithLowestRating, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetToursWithLowestRatingRow
	for rows.Next() {
		var i GetToursWithLowestRatingRow
		if err := rows.Scan(
			&i.ID,
			&i.TieuDe,
			&i.TenNhaCungCap,
			&i.SoDanhGia,
			&i.DiemTrungBinh,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionStatsByStatus = `-- name: GetTransactionStatsByStatus :many
SELECT 
    trang_thai,
    COUNT(*) AS so_giao_dich,
    COALESCE(SUM(so_tien), 0) AS tong_tien
FROM lich_su_giao_dich
GROUP BY trang_thai
ORDER BY so_giao_dich DESC
`

type GetTransactionStatsByStatusRow struct {
	TrangThai  NullTrangThaiThanhToan `json:"trang_thai"`
	SoGiaoDich int64                  `json:"so_giao_dich"`
	TongTien   interface{}            `json:"tong_tien"`
}

// Thống kê giao dịch theo trạng thái
func (q *Queries) GetTransactionStatsByStatus(ctx context.Context) ([]GetTransactionStatsByStatusRow, error) {
	rows, err := q.db.Query(ctx, getTransactionStatsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionStatsByStatusRow
	for rows.Next() {
		var i GetTransactionStatsByStatusRow
		if err := rows.Scan(&i.TrangThai, &i.SoGiaoDich, &i.TongTien); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByDay = `-- name: GetTransactionsByDay :many
SELECT 
    DATE(ngay_tao) AS ngay,
    COUNT(*) AS so_giao_dich,
    COALESCE(SUM(so_tien), 0) AS tong_tien,
    COUNT(*) FILTER (WHERE trang_thai = 'thanh_cong') AS thanh_cong,
    COUNT(*) FILTER (WHERE trang_thai = 'that_bai') AS that_bai
FROM lich_su_giao_dich
WHERE ngay_tao >= NOW() - INTERVAL '30 days'
GROUP BY DATE(ngay_tao)
ORDER BY ngay ASC
`

type GetTransactionsByDayRow struct {
	Ngay       pgtype.Date `json:"ngay"`
	SoGiaoDich int64       `json:"so_giao_dich"`
	TongTien   interface{} `json:"tong_tien"`
	ThanhCong  int64       `json:"thanh_cong"`
	ThatBai    int64       `json:"that_bai"`
}

// Giao dịch theo ngày (30 ngày gần nhất)
func (q *Queries) GetTransactionsByDay(ctx context.Context) ([]GetTransactionsByDayRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsByDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsByDayRow
	for rows.Next() {
		var i GetTransactionsByDayRow
		if err := rows.Scan(
			&i.Ngay,
			&i.SoGiaoDich,
			&i.TongTien,
			&i.ThanhCong,
			&i.ThatBai,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one

SELECT 
    COUNT(*) AS tong_thong_bao_chua_doc
FROM thong_bao
WHERE da_doc = FALSE
`

// =====================
// 10. NOTIFICATION & ACTIVITY
// =====================
// Số thông báo chưa đọc (cho admin xem tổng quan)
func (q *Queries) GetUnreadNotificationCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadNotificationCount)
	var tong_thong_bao_chua_doc int64
	err := row.Scan(&tong_thong_bao_chua_doc)
	return tong_thong_bao_chua_doc, err
}

const getUpcomingDepartures = `-- name: GetUpcomingDepartures :many

SELECT 
    kh.id,
    kh.ngay_khoi_hanh,
    kh.ngay_ket_thuc,
    kh.suc_chua,
    kh.so_cho_da_dat,
    kh.trang_thai,
    t.tieu_de AS ten_tour,
    t.gia_nguoi_lon,
    ncc.ten AS ten_nha_cung_cap,
    (kh.suc_chua - kh.so_cho_da_dat) AS cho_con_trong
FROM khoi_hanh_tour kh
JOIN tour t ON kh.tour_id = t.id
LEFT JOIN nha_cung_cap ncc ON t.nha_cung_cap_id = ncc.id
WHERE kh.ngay_khoi_hanh >= CURRENT_DATE
  AND kh.trang_thai IN ('len_lich', 'xac_nhan', 'con_cho')
ORDER BY kh.ngay_khoi_hanh ASC
LIMIT $1
`

type GetUpcomingDeparturesRow struct {
	ID            int32                 `json:"id"`
	NgayKhoiHanh  pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc   pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua       int32                 `json:"suc_chua"`
	SoChoDaDat    *int32                `json:"so_cho_da_dat"`
	TrangThai     NullTrangThaiKhoiHanh `json:"trang_thai"`
	TenTour       string                `json:"ten_tour"`
	GiaNguoiLon   pgtype.Numeric        `json:"gia_nguoi_lon"`
	TenNhaCungCap *string               `json:"ten_nha_cung_cap"`
	ChoConTrong   int32                 `json:"cho_con_trong"`
}

// =====================
// 9. DEPARTURE STATISTICS
// =====================
// Các khởi hành sắp tới
func (q *Queries) GetUpcomingDepartures(ctx context.Context, limit int32) ([]GetUpcomingDeparturesRow, error) {
	rows, err := q.db.Query(ctx, getUpcomingDepartures, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpcomingDeparturesRow
	for rows.Next() {
		var i GetUpcomingDeparturesRow
		if err := rows.Scan(
			&i.ID,
			&i.NgayKhoiHanh,
			&i.NgayKetThuc,
			&i.SucChua,
			&i.SoChoDaDat,
			&i.TrangThai,
			&i.TenTour,
			&i.GiaNguoiLon,
			&i.TenNhaCungCap,
			&i.ChoConTrong,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGrowthByDay = `-- name: GetUserGrowthByDay :many
SELECT 
    DATE(ngay_tao) AS ngay,
    COUNT(*) AS so_luong
FROM nguoi_dung
WHERE ngay_tao >= NOW() - INTERVAL '30 days'
GROUP BY DATE(ngay_tao)
ORDER BY ngay ASC
`

type GetUserGrowthByDayRow struct {
	Ngay    pgtype.Date `json:"ngay"`
	SoLuong int64       `json:"so_luong"`
}

// Tăng trưởng người dùng theo ngày (30 ngày gần nhất)
func (q *Queries) GetUserGrowthByDay(ctx context.Context) ([]GetUserGrowthByDayRow, error) {
	rows, err := q.db.Query(ctx, getUserGrowthByDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserGrowthByDayRow
	for rows.Next() {
		var i GetUserGrowthByDayRow
		if err := rows.Scan(&i.Ngay, &i.SoLuong); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGrowthByMonth = `-- name: GetUserGrowthByMonth :many
SELECT 
    DATE_TRUNC('month', ngay_tao) AS thang,
    COUNT(*) AS tong_dang_ky,
    COUNT(*) FILTER (WHERE vai_tro = 'khach_hang') AS khach_hang_moi,
    COUNT(*) FILTER (WHERE vai_tro = 'nha_cung_cap') AS nha_cung_cap_moi
FROM nguoi_dung
WHERE ngay_tao >= NOW() - INTERVAL '12 months'
GROUP BY DATE_TRUNC('month', ngay_tao)
ORDER BY thang ASC
`

type GetUserGrowthByMonthRow struct {
	Thang         pgtype.Interval `json:"thang"`
	TongDangKy    int64           `json:"tong_dang_ky"`
	KhachHangMoi  int64           `json:"khach_hang_moi"`
	NhaCungCapMoi int64           `json:"nha_cung_cap_moi"`
}

// Tăng trưởng người dùng theo tháng (12 tháng gần nhất)
func (q *Queries) GetUserGrowthByMonth(ctx context.Context) ([]GetUserGrowthByMonthRow, error) {
	rows, err := q.db.Query(ctx, getUserGrowthByMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserGrowthByMonthRow
	for rows.Next() {
		var i GetUserGrowthByMonthRow
		if err := rows.Scan(
			&i.Thang,
			&i.TongDangKy,
			&i.KhachHangMoi,
			&i.NhaCungCapMoi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStatsByRole = `-- name: GetUserStatsByRole :many

SELECT 
    vai_tro,
    COUNT(*) AS so_luong,
    COUNT(*) FILTER (WHERE dang_hoat_dong = TRUE) AS dang_hoat_dong,
    COUNT(*) FILTER (WHERE xac_thuc = TRUE) AS da_xac_thuc
FROM nguoi_dung
GROUP BY vai_tro
ORDER BY so_luong DESC
`

type GetUserStatsByRoleRow struct {
	VaiTro       NullVaiTroNguoiDung `json:"vai_tro"`
	SoLuong      int64               `json:"so_luong"`
	DangHoatDong int64               `json:"dang_hoat_dong"`
	DaXacThuc    int64               `json:"da_xac_thuc"`
}

// =====================
// 2. USER STATISTICS
// =====================
// Thống kê người dùng theo vai trò
func (q *Queries) GetUserStatsByRole(ctx context.Context) ([]GetUserStatsByRoleRow, error) {
	rows, err := q.db.Query(ctx, getUserStatsByRole)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserStatsByRoleRow
	for rows.Next() {
		var i GetUserStatsByRoleRow
		if err := rows.Scan(
			&i.VaiTro,
			&i.SoLuong,
			&i.DangHoatDong,
			&i.DaXacThuc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYearlyComparisonReport = `-- name: GetYearlyComparisonReport :many
SELECT 
    EXTRACT(YEAR FROM ngay_dat) AS nam,
    COUNT(*) AS tong_booking,
    COALESCE(SUM(tong_tien) FILTER (WHERE trang_thai IN ('da_thanh_toan', 'hoan_thanh')), 0) AS doanh_thu,
    COALESCE(AVG(tong_tien) FILTER (WHERE trang_thai IN ('da_thanh_toan', 'hoan_thanh')), 0) AS gia_tri_trung_binh
FROM dat_cho
GROUP BY EXTRACT(YEAR FROM ngay_dat)
ORDER BY nam ASC
`

type GetYearlyComparisonReportRow struct {
	Nam             pgtype.Numeric `json:"nam"`
	TongBooking     int64          `json:"tong_booking"`
	DoanhThu        interface{}    `json:"doanh_thu"`
	GiaTriTrungBinh interface{}    `json:"gia_tri_trung_binh"`
}

// So sánh theo năm
func (q *Queries) GetYearlyComparisonReport(ctx context.Context) ([]GetYearlyComparisonReportRow, error) {
	rows, err := q.db.Query(ctx, getYearlyComparisonReport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetYearlyComparisonReportRow
	for rows.Next() {
		var i GetYearlyComparisonReportRow
		if err := rows.Scan(
			&i.Nam,
			&i.TongBooking,
			&i.DoanhThu,
			&i.GiaTriTrungBinh,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
