// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: booking.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPassenger = `-- name: AddPassenger :one

INSERT INTO hanh_khach (
    dat_cho_id,
    ho_ten,
    ngay_sinh,
    loai_khach,
    gioi_tinh,
    so_giay_to_tuy_thanh,
    quoc_tich,
    ghi_chu
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, dat_cho_id, ho_ten, ngay_sinh, loai_khach, gioi_tinh, so_giay_to_tuy_thanh, quoc_tich, ghi_chu
`

type AddPassengerParams struct {
	DatChoID         int32       `json:"dat_cho_id"`
	HoTen            string      `json:"ho_ten"`
	NgaySinh         pgtype.Date `json:"ngay_sinh"`
	LoaiKhach        *string     `json:"loai_khach"`
	GioiTinh         *string     `json:"gioi_tinh"`
	SoGiayToTuyThanh *string     `json:"so_giay_to_tuy_thanh"`
	QuocTich         *string     `json:"quoc_tich"`
	GhiChu           *string     `json:"ghi_chu"`
}

// ===========================================
// BƯỚC 3: NHẬP THÔNG TIN HÀNH KHÁCH
// ===========================================
// Thêm hành khách vào booking
func (q *Queries) AddPassenger(ctx context.Context, arg AddPassengerParams) (HanhKhach, error) {
	row := q.db.QueryRow(ctx, addPassenger,
		arg.DatChoID,
		arg.HoTen,
		arg.NgaySinh,
		arg.LoaiKhach,
		arg.GioiTinh,
		arg.SoGiayToTuyThanh,
		arg.QuocTich,
		arg.GhiChu,
	)
	var i HanhKhach
	err := row.Scan(
		&i.ID,
		&i.DatChoID,
		&i.HoTen,
		&i.NgaySinh,
		&i.LoaiKhach,
		&i.GioiTinh,
		&i.SoGiayToTuyThanh,
		&i.QuocTich,
		&i.GhiChu,
	)
	return i, err
}

type AddPassengersParams struct {
	DatChoID         int32       `json:"dat_cho_id"`
	HoTen            string      `json:"ho_ten"`
	NgaySinh         pgtype.Date `json:"ngay_sinh"`
	LoaiKhach        *string     `json:"loai_khach"`
	GioiTinh         *string     `json:"gioi_tinh"`
	SoGiayToTuyThanh *string     `json:"so_giay_to_tuy_thanh"`
	QuocTich         *string     `json:"quoc_tich"`
	GhiChu           *string     `json:"ghi_chu"`
}

const autoCompleteBookings = `-- name: AutoCompleteBookings :exec
UPDATE dat_cho dc
SET 
    trang_thai = 'hoan_thanh',
    ngay_cap_nhat = CURRENT_TIMESTAMP
FROM khoi_hanh_tour kh
WHERE dc.khoi_hanh_id = kh.id
    AND dc.trang_thai = 'da_thanh_toan'
    AND kh.ngay_ket_thuc < CURRENT_DATE
`

// Tự động hoàn thành các booking sau khi tour kết thúc (chạy bằng cron job)
func (q *Queries) AutoCompleteBookings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, autoCompleteBookings)
	return err
}

const calculateRefundAmount = `-- name: CalculateRefundAmount :one
WITH booking_info AS (
    SELECT 
        dc.tong_tien,
        kh.ngay_khoi_hanh,
        (kh.ngay_khoi_hanh - CURRENT_DATE)::INT AS so_ngay_truoc_khoi_hanh
    FROM dat_cho dc
    JOIN khoi_hanh_tour kh ON kh.id = dc.khoi_hanh_id
    WHERE dc.id = $1::int
),
refund_calc AS (
    SELECT 
        bi.tong_tien,
        bi.so_ngay_truoc_khoi_hanh,
        CASE 
            WHEN bi.so_ngay_truoc_khoi_hanh >= 15 THEN 100.00
            WHEN bi.so_ngay_truoc_khoi_hanh >= 7 THEN 90.00
            WHEN bi.so_ngay_truoc_khoi_hanh >= 3 THEN 70.00
            WHEN bi.so_ngay_truoc_khoi_hanh >= 1 THEN 50.00
            ELSE 0.00
        END::DECIMAL(5,2) AS phan_tram_hoan,
        CASE 
            WHEN bi.so_ngay_truoc_khoi_hanh >= 15 THEN 'Hủy trước 15 ngày - hoàn 100%'
            WHEN bi.so_ngay_truoc_khoi_hanh >= 7 THEN 'Hủy trước 7 ngày - hoàn 90%'
            WHEN bi.so_ngay_truoc_khoi_hanh >= 3 THEN 'Hủy trước 3 ngày - hoàn 70%'
            WHEN bi.so_ngay_truoc_khoi_hanh >= 1 THEN 'Hủy trước 24 giờ - hoàn 50%'
            ELSE 'Hủy trong 24 giờ - không hoàn tiền'
        END::TEXT AS ly_do
    FROM booking_info bi
)
SELECT 
    rc.tong_tien,
    (rc.tong_tien * rc.phan_tram_hoan / 100.00)::DECIMAL(12,2) AS so_tien_hoan,
    rc.phan_tram_hoan,
    rc.so_ngay_truoc_khoi_hanh,
    rc.ly_do
FROM refund_calc rc
`

type CalculateRefundAmountRow struct {
	TongTien            pgtype.Numeric `json:"tong_tien"`
	SoTienHoan          pgtype.Numeric `json:"so_tien_hoan"`
	PhanTramHoan        pgtype.Numeric `json:"phan_tram_hoan"`
	SoNgayTruocKhoiHanh int32          `json:"so_ngay_truoc_khoi_hanh"`
	LyDo                string         `json:"ly_do"`
}

func (q *Queries) CalculateRefundAmount(ctx context.Context, bookingID int32) (CalculateRefundAmountRow, error) {
	row := q.db.QueryRow(ctx, calculateRefundAmount, bookingID)
	var i CalculateRefundAmountRow
	err := row.Scan(
		&i.TongTien,
		&i.SoTienHoan,
		&i.PhanTramHoan,
		&i.SoNgayTruocKhoiHanh,
		&i.LyDo,
	)
	return i, err
}

const calculateTourPrice = `-- name: CalculateTourPrice :one
SELECT  FROM tinh_gia_tour(
    $1::int, 
    $2::int, 
    $3::int
)
`

type CalculateTourPriceParams struct {
	KhoiHanhID int32 `json:"khoi_hanh_id"`
	SoNguoiLon int32 `json:"so_nguoi_lon"`
	SoTreEm    int32 `json:"so_tre_em"`
}

type CalculateTourPriceRow struct {
}

// Tính giá tour cho khách hàng xem trước khi đặt
func (q *Queries) CalculateTourPrice(ctx context.Context, arg CalculateTourPriceParams) (CalculateTourPriceRow, error) {
	row := q.db.QueryRow(ctx, calculateTourPrice, arg.KhoiHanhID, arg.SoNguoiLon, arg.SoTreEm)
	var i CalculateTourPriceRow
	err := row.Scan()
	return i, err
}

const cancelBooking = `-- name: CancelBooking :one
SELECT 
    so_tien_hoan::DECIMAL(12,2) as so_tien_hoan,
    phan_tram_hoan::DECIMAL(5,2) as phan_tram_hoan,
    so_ngay_truoc_khoi_hanh::INT as so_ngay_truoc_khoi_hanh,
    ly_do::TEXT as ly_do
FROM cancel_booking($1::int)
LIMIT 1
`

type CancelBookingRow struct {
	SoTienHoan          pgtype.Numeric `json:"so_tien_hoan"`
	PhanTramHoan        pgtype.Numeric `json:"phan_tram_hoan"`
	SoNgayTruocKhoiHanh int32          `json:"so_ngay_truoc_khoi_hanh"`
	LyDo                string         `json:"ly_do"`
}

func (q *Queries) CancelBooking(ctx context.Context, bookingID int32) (CancelBookingRow, error) {
	row := q.db.QueryRow(ctx, cancelBooking, bookingID)
	var i CancelBookingRow
	err := row.Scan(
		&i.SoTienHoan,
		&i.PhanTramHoan,
		&i.SoNgayTruocKhoiHanh,
		&i.LyDo,
	)
	return i, err
}

const checkDepartureAvailability = `-- name: CheckDepartureAvailability :one
SELECT 
    (suc_chua - so_cho_da_dat) >= $2 AS con_cho,
    (suc_chua - so_cho_da_dat) AS so_cho_trong
FROM khoi_hanh_tour
WHERE id = $1
    AND trang_thai IN ('len_lich', 'xac_nhan', 'con_cho')
`

type CheckDepartureAvailabilityParams struct {
	ID      int32 `json:"id"`
	SucChua int32 `json:"suc_chua"`
}

type CheckDepartureAvailabilityRow struct {
	ConCho     bool  `json:"con_cho"`
	SoChoTrong int32 `json:"so_cho_trong"`
}

// Kiểm tra còn đủ chỗ không
func (q *Queries) CheckDepartureAvailability(ctx context.Context, arg CheckDepartureAvailabilityParams) (CheckDepartureAvailabilityRow, error) {
	row := q.db.QueryRow(ctx, checkDepartureAvailability, arg.ID, arg.SucChua)
	var i CheckDepartureAvailabilityRow
	err := row.Scan(&i.ConCho, &i.SoChoTrong)
	return i, err
}

const completeBooking = `-- name: CompleteBooking :one

UPDATE dat_cho
SET 
    trang_thai = 'hoan_thanh',
    ngay_cap_nhat = CURRENT_TIMESTAMP
WHERE id = $1 AND trang_thai = 'da_thanh_toan'
RETURNING id, nguoi_dung_id, khoi_hanh_id, so_nguoi_lon, so_tre_em, tong_tien, don_vi_tien_te, trang_thai, phuong_thuc_thanh_toan, ngay_dat, ngay_cap_nhat
`

// ===========================================
// BƯỚC 6: HOÀN THÀNH TOUR
// ===========================================
// Đánh dấu booking hoàn thành (sau khi tour kết thúc)
func (q *Queries) CompleteBooking(ctx context.Context, id int32) (DatCho, error) {
	row := q.db.QueryRow(ctx, completeBooking, id)
	var i DatCho
	err := row.Scan(
		&i.ID,
		&i.NguoiDungID,
		&i.KhoiHanhID,
		&i.SoNguoiLon,
		&i.SoTreEm,
		&i.TongTien,
		&i.DonViTienTe,
		&i.TrangThai,
		&i.PhuongThucThanhToan,
		&i.NgayDat,
		&i.NgayCapNhat,
	)
	return i, err
}

const confirmBooking = `-- name: ConfirmBooking :one

UPDATE dat_cho
SET 
    trang_thai = 'da_xac_nhan',
    ngay_cap_nhat = CURRENT_TIMESTAMP
WHERE id = $1 AND trang_thai = 'cho_xac_nhan'
RETURNING id, nguoi_dung_id, khoi_hanh_id, so_nguoi_lon, so_tre_em, tong_tien, don_vi_tien_te, trang_thai, phuong_thuc_thanh_toan, ngay_dat, ngay_cap_nhat
`

// ===========================================
// BƯỚC 4: XÁC NHẬN ĐẶT CHỖ
// ===========================================
// Admin/Hệ thống xác nhận đặt chỗ
func (q *Queries) ConfirmBooking(ctx context.Context, id int32) (DatCho, error) {
	row := q.db.QueryRow(ctx, confirmBooking, id)
	var i DatCho
	err := row.Scan(
		&i.ID,
		&i.NguoiDungID,
		&i.KhoiHanhID,
		&i.SoNguoiLon,
		&i.SoTreEm,
		&i.TongTien,
		&i.DonViTienTe,
		&i.TrangThai,
		&i.PhuongThucThanhToan,
		&i.NgayDat,
		&i.NgayCapNhat,
	)
	return i, err
}

const countBookingsByUser = `-- name: CountBookingsByUser :one
SELECT COUNT(*)::int AS total_count
FROM dat_cho dc
JOIN khoi_hanh_tour kh ON kh.id = dc.khoi_hanh_id
WHERE 
    dc.nguoi_dung_id = $1
    -- Lọc theo trạng thái đặt chỗ (truyền NULL hoặc empty string nếu muốn lấy tất cả)
    AND CASE 
        WHEN COALESCE($2::text, '') = '' THEN TRUE
        ELSE dc.trang_thai = ($2::text)::trang_thai_dat_cho
    END
    -- Lọc theo trạng thái khởi hành (truyền NULL hoặc empty string nếu muốn lấy tất cả)
    -- Hỗ trợ nhiều giá trị phân cách bằng dấu phẩy
    AND CASE 
        WHEN COALESCE($3::text, '') = '' THEN TRUE
        WHEN $3::text LIKE '%,%' THEN 
            kh.trang_thai IN (
                SELECT unnest(string_to_array($3::text, ','))::trang_thai_khoi_hanh
            )
        ELSE kh.trang_thai = ($3::text)::trang_thai_khoi_hanh
    END
`

type CountBookingsByUserParams struct {
	NguoiDungID pgtype.UUID `json:"nguoi_dung_id"`
	Column2     string      `json:"column_2"`
	Column3     string      `json:"column_3"`
}

// Đếm tổng số đặt chỗ của người dùng (có filter)
func (q *Queries) CountBookingsByUser(ctx context.Context, arg CountBookingsByUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, countBookingsByUser, arg.NguoiDungID, arg.Column2, arg.Column3)
	var total_count int32
	err := row.Scan(&total_count)
	return total_count, err
}

const createBooking = `-- name: CreateBooking :one
SELECT  FROM create_booking(
    $1::uuid,
    $2::int,
    $3::int,
    $4::int,
    $5::varchar
) AS booking
`

type CreateBookingParams struct {
	NguoiDungID         pgtype.UUID `json:"nguoi_dung_id"`
	KhoiHanhID          int32       `json:"khoi_hanh_id"`
	SoNguoiLon          int32       `json:"so_nguoi_lon"`
	SoTreEm             int32       `json:"so_tre_em"`
	PhuongThucThanhToan *string     `json:"phuong_thuc_thanh_toan"`
}

type CreateBookingRow struct {
}

// Tạo đặt chỗ mới (tự động tính tổng tiền)
func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (CreateBookingRow, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.NguoiDungID,
		arg.KhoiHanhID,
		arg.SoNguoiLon,
		arg.SoTreEm,
		arg.PhuongThucThanhToan,
	)
	var i CreateBookingRow
	err := row.Scan()
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO lich_su_giao_dich (
    dat_cho_id,
    nguoi_dung_id,
    ma_giao_dich_noi_bo,
    cong_thanh_toan_id,
    so_tien,
    loai_giao_dich,
    trang_thai,
    noi_dung_chuyen_khoan
) VALUES (
    $1, $2, $3, $4, $5, 'thanh_toan', 'dang_cho_thanh_toan', $6
) RETURNING id, dat_cho_id, nguoi_dung_id, ma_giao_dich_noi_bo, ma_tham_chieu_cong_thanh_toan, cong_thanh_toan_id, so_tien, loai_giao_dich, trang_thai, noi_dung_chuyen_khoan, ngay_tao, ngay_hoan_thanh
`

type CreateTransactionParams struct {
	DatChoID           *int32         `json:"dat_cho_id"`
	NguoiDungID        pgtype.UUID    `json:"nguoi_dung_id"`
	MaGiaoDichNoiBo    string         `json:"ma_giao_dich_noi_bo"`
	CongThanhToanID    *string        `json:"cong_thanh_toan_id"`
	SoTien             pgtype.Numeric `json:"so_tien"`
	NoiDungChuyenKhoan *string        `json:"noi_dung_chuyen_khoan"`
}

// ===========================================
// BƯỚC 5: THANH TOÁN
// ===========================================
// Tạo giao dịch thanh toán mới
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (LichSuGiaoDich, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.DatChoID,
		arg.NguoiDungID,
		arg.MaGiaoDichNoiBo,
		arg.CongThanhToanID,
		arg.SoTien,
		arg.NoiDungChuyenKhoan,
	)
	var i LichSuGiaoDich
	err := row.Scan(
		&i.ID,
		&i.DatChoID,
		&i.NguoiDungID,
		&i.MaGiaoDichNoiBo,
		&i.MaThamChieuCongThanhToan,
		&i.CongThanhToanID,
		&i.SoTien,
		&i.LoaiGiaoDich,
		&i.TrangThai,
		&i.NoiDungChuyenKhoan,
		&i.NgayTao,
		&i.NgayHoanThanh,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :exec
DELETE FROM dat_cho WHERE id = $1
`

// Xóa đặt chỗ
func (q *Queries) DeleteBooking(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBooking, id)
	return err
}

const deleteBookings = `-- name: DeleteBookings :exec
DELETE FROM dat_cho WHERE id IN (SELECT unnest($1::int[]))
`

// Xóa nhiều đặt chỗ
func (q *Queries) DeleteBookings(ctx context.Context, ids []int32) error {
	_, err := q.db.Exec(ctx, deleteBookings, ids)
	return err
}

const deletePassenger = `-- name: DeletePassenger :exec
DELETE FROM hanh_khach WHERE id = $1
`

// Xóa hành khách
func (q *Queries) DeletePassenger(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePassenger, id)
	return err
}

const getAllRefunds = `-- name: GetAllRefunds :many

WITH refund_info AS (
    SELECT 
        dc.id AS booking_id,
        dc.tong_tien,
        kh.ngay_khoi_hanh,
        -- Tính số ngày trước khởi hành tại thời điểm hủy (ngay_cap_nhat)
        (kh.ngay_khoi_hanh - DATE(dc.ngay_cap_nhat))::INT AS so_ngay_truoc_khoi_hanh
    FROM dat_cho dc
    JOIN khoi_hanh_tour kh ON kh.id = dc.khoi_hanh_id
    WHERE dc.trang_thai = 'da_huy'
)
SELECT 
    dc.id AS booking_id,
    dc.ngay_dat,
    dc.ngay_cap_nhat AS ngay_huy,
    dc.tong_tien,
    dc.don_vi_tien_te,
    dc.so_nguoi_lon,
    dc.so_tre_em,
    dc.phuong_thuc_thanh_toan,
    dc.trang_thai,
    
    -- Thông tin khách hàng
    nd.id AS customer_id,
    nd.ho_ten AS customer_name,
    nd.email AS customer_email,
    nd.so_dien_thoai AS customer_phone,
    
    -- Thông tin tour
    t.id AS tour_id,
    t.tieu_de AS tour_title,
    ncc.id AS supplier_id,
    ncc.ten AS supplier_name,
    
    -- Thông tin khởi hành
    kh.id AS departure_id,
    kh.ngay_khoi_hanh,
    kh.ngay_ket_thuc,
    
    -- Thông tin refund
    ri.so_ngay_truoc_khoi_hanh,
    CASE 
        WHEN ri.so_ngay_truoc_khoi_hanh >= 15 THEN 100.00
        WHEN ri.so_ngay_truoc_khoi_hanh >= 7 THEN 90.00
        WHEN ri.so_ngay_truoc_khoi_hanh >= 3 THEN 70.00
        WHEN ri.so_ngay_truoc_khoi_hanh >= 1 THEN 50.00
        ELSE 0.00
    END::DECIMAL(5,2) AS phan_tram_hoan,
    (ri.tong_tien * 
        CASE 
            WHEN ri.so_ngay_truoc_khoi_hanh >= 15 THEN 100.00
            WHEN ri.so_ngay_truoc_khoi_hanh >= 7 THEN 90.00
            WHEN ri.so_ngay_truoc_khoi_hanh >= 3 THEN 70.00
            WHEN ri.so_ngay_truoc_khoi_hanh >= 1 THEN 50.00
            ELSE 0.00
        END / 100.00)::DECIMAL(12,2) AS so_tien_hoan,
    CASE 
        WHEN ri.so_ngay_truoc_khoi_hanh >= 15 THEN 'Hủy trước 15 ngày - hoàn 100%'
        WHEN ri.so_ngay_truoc_khoi_hanh >= 7 THEN 'Hủy trước 7 ngày - hoàn 90%'
        WHEN ri.so_ngay_truoc_khoi_hanh >= 3 THEN 'Hủy trước 3 ngày - hoàn 70%'
        WHEN ri.so_ngay_truoc_khoi_hanh >= 1 THEN 'Hủy trước 24 giờ - hoàn 50%'
        ELSE 'Hủy trong 24 giờ - không hoàn tiền'
    END::TEXT AS ly_do
FROM dat_cho dc
JOIN nguoi_dung nd ON nd.id = dc.nguoi_dung_id
JOIN khoi_hanh_tour kh ON kh.id = dc.khoi_hanh_id
JOIN tour t ON t.id = kh.tour_id
JOIN nha_cung_cap ncc ON ncc.id = t.nha_cung_cap_id
JOIN refund_info ri ON ri.booking_id = dc.id
WHERE dc.trang_thai = 'da_huy'
    AND ($1::timestamp IS NULL OR dc.ngay_cap_nhat >= $1::timestamp)
    AND ($2::timestamp IS NULL OR dc.ngay_cap_nhat <= $2::timestamp)
    AND ($3::uuid IS NULL OR ncc.id = $3::uuid)
    AND ($4::text IS NULL OR nd.ho_ten ILIKE '%' || $4::text || '%' OR nd.email ILIKE '%' || $4::text || '%' OR t.tieu_de ILIKE '%' || $4::text || '%')
ORDER BY dc.ngay_cap_nhat DESC
LIMIT $5 OFFSET $6
`

type GetAllRefundsParams struct {
	Column1 pgtype.Timestamp `json:"column_1"`
	Column2 pgtype.Timestamp `json:"column_2"`
	Column3 pgtype.UUID      `json:"column_3"`
	Column4 string           `json:"column_4"`
	Limit   int32            `json:"limit"`
	Offset  int32            `json:"offset"`
}

type GetAllRefundsRow struct {
	BookingID           int32               `json:"booking_id"`
	NgayDat             pgtype.Timestamp    `json:"ngay_dat"`
	NgayHuy             pgtype.Timestamp    `json:"ngay_huy"`
	TongTien            pgtype.Numeric      `json:"tong_tien"`
	DonViTienTe         *string             `json:"don_vi_tien_te"`
	SoNguoiLon          *int32              `json:"so_nguoi_lon"`
	SoTreEm             *int32              `json:"so_tre_em"`
	PhuongThucThanhToan *string             `json:"phuong_thuc_thanh_toan"`
	TrangThai           NullTrangThaiDatCho `json:"trang_thai"`
	CustomerID          pgtype.UUID         `json:"customer_id"`
	CustomerName        string              `json:"customer_name"`
	CustomerEmail       string              `json:"customer_email"`
	CustomerPhone       *string             `json:"customer_phone"`
	TourID              int32               `json:"tour_id"`
	TourTitle           string              `json:"tour_title"`
	SupplierID          pgtype.UUID         `json:"supplier_id"`
	SupplierName        string              `json:"supplier_name"`
	DepartureID         int32               `json:"departure_id"`
	NgayKhoiHanh        pgtype.Date         `json:"ngay_khoi_hanh"`
	NgayKetThuc         pgtype.Date         `json:"ngay_ket_thuc"`
	SoNgayTruocKhoiHanh int32               `json:"so_ngay_truoc_khoi_hanh"`
	PhanTramHoan        pgtype.Numeric      `json:"phan_tram_hoan"`
	SoTienHoan          pgtype.Numeric      `json:"so_tien_hoan"`
	LyDo                string              `json:"ly_do"`
}

// ===========================================
// QUẢN LÝ HOÀN TIỀN (REFUND MANAGEMENT)
// ===========================================
// Lấy tất cả refund cho admin (tất cả booking đã hủy với thông tin refund)
func (q *Queries) GetAllRefunds(ctx context.Context, arg GetAllRefundsParams) ([]GetAllRefundsRow, error) {
	rows, err := q.db.Query(ctx, getAllRefunds,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRefundsRow
	for rows.Next() {
		var i GetAllRefundsRow
		if err := rows.Scan(
			&i.BookingID,
			&i.NgayDat,
			&i.NgayHuy,
			&i.TongTien,
			&i.DonViTienTe,
			&i.SoNguoiLon,
			&i.SoTreEm,
			&i.PhuongThucThanhToan,
			&i.TrangThai,
			&i.CustomerID,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.TourID,
			&i.TourTitle,
			&i.SupplierID,
			&i.SupplierName,
			&i.DepartureID,
			&i.NgayKhoiHanh,
			&i.NgayKetThuc,
			&i.SoNgayTruocKhoiHanh,
			&i.PhanTramHoan,
			&i.SoTienHoan,
			&i.LyDo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableDepartures = `-- name: GetAvailableDepartures :many

SELECT 
    kh.id,
    kh.tour_id,
    kh.ngay_khoi_hanh,
    kh.ngay_ket_thuc,
    kh.suc_chua,
    kh.so_cho_da_dat,
    (kh.suc_chua - kh.so_cho_da_dat) AS so_cho_trong,
    kh.trang_thai,
    kh.ghi_chu
FROM khoi_hanh_tour kh
WHERE kh.tour_id = $1
    AND kh.trang_thai IN ('len_lich', 'xac_nhan', 'con_cho')
    AND kh.ngay_khoi_hanh > CURRENT_DATE
    AND (kh.suc_chua - kh.so_cho_da_dat) > 0
ORDER BY kh.ngay_khoi_hanh ASC
`

type GetAvailableDeparturesRow struct {
	ID           int32                 `json:"id"`
	TourID       int32                 `json:"tour_id"`
	NgayKhoiHanh pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc  pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua      int32                 `json:"suc_chua"`
	SoChoDaDat   *int32                `json:"so_cho_da_dat"`
	SoChoTrong   int32                 `json:"so_cho_trong"`
	TrangThai    NullTrangThaiKhoiHanh `json:"trang_thai"`
	GhiChu       *string               `json:"ghi_chu"`
}

// ===========================================
// BƯỚC 1: CHỌN TOUR & NGÀY KHỞI HÀNH
// ===========================================
// Lấy danh sách ngày khởi hành còn chỗ của một tour
func (q *Queries) GetAvailableDepartures(ctx context.Context, tourID int32) ([]GetAvailableDeparturesRow, error) {
	rows, err := q.db.Query(ctx, getAvailableDepartures, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAvailableDeparturesRow
	for rows.Next() {
		var i GetAvailableDeparturesRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.NgayKhoiHanh,
			&i.NgayKetThuc,
			&i.SucChua,
			&i.SoChoDaDat,
			&i.SoChoTrong,
			&i.TrangThai,
			&i.GhiChu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingById = `-- name: GetBookingById :one
SELECT 
    dc.id, dc.nguoi_dung_id, dc.khoi_hanh_id, dc.so_nguoi_lon, dc.so_tre_em, dc.tong_tien, dc.don_vi_tien_te, dc.trang_thai, dc.phuong_thuc_thanh_toan, dc.ngay_dat, dc.ngay_cap_nhat,
    nd.ho_ten AS ten_nguoi_dat,
    nd.email,
    nd.so_dien_thoai,
    kh.ngay_khoi_hanh,
    kh.ngay_ket_thuc,
    t.tieu_de AS ten_tour,
    t.nha_cung_cap_id
FROM dat_cho dc
JOIN nguoi_dung nd ON nd.id = dc.nguoi_dung_id
JOIN khoi_hanh_tour kh ON kh.id = dc.khoi_hanh_id
JOIN tour t ON t.id = kh.tour_id
WHERE dc.id = $1
`

type GetBookingByIdRow struct {
	ID                  int32               `json:"id"`
	NguoiDungID         pgtype.UUID         `json:"nguoi_dung_id"`
	KhoiHanhID          int32               `json:"khoi_hanh_id"`
	SoNguoiLon          *int32              `json:"so_nguoi_lon"`
	SoTreEm             *int32              `json:"so_tre_em"`
	TongTien            pgtype.Numeric      `json:"tong_tien"`
	DonViTienTe         *string             `json:"don_vi_tien_te"`
	TrangThai           NullTrangThaiDatCho `json:"trang_thai"`
	PhuongThucThanhToan *string             `json:"phuong_thuc_thanh_toan"`
	NgayDat             pgtype.Timestamp    `json:"ngay_dat"`
	NgayCapNhat         pgtype.Timestamp    `json:"ngay_cap_nhat"`
	TenNguoiDat         string              `json:"ten_nguoi_dat"`
	Email               string              `json:"email"`
	SoDienThoai         *string             `json:"so_dien_thoai"`
	NgayKhoiHanh        pgtype.Date         `json:"ngay_khoi_hanh"`
	NgayKetThuc         pgtype.Date         `json:"ngay_ket_thuc"`
	TenTour             string              `json:"ten_tour"`
	NhaCungCapID        pgtype.UUID         `json:"nha_cung_cap_id"`
}

// Lấy thông tin đặt chỗ theo ID
func (q *Queries) GetBookingById(ctx context.Context, id int32) (GetBookingByIdRow, error) {
	row := q.db.QueryRow(ctx, getBookingById, id)
	var i GetBookingByIdRow
	err := row.Scan(
		&i.ID,
		&i.NguoiDungID,
		&i.KhoiHanhID,
		&i.SoNguoiLon,
		&i.SoTreEm,
		&i.TongTien,
		&i.DonViTienTe,
		&i.TrangThai,
		&i.PhuongThucThanhToan,
		&i.NgayDat,
		&i.NgayCapNhat,
		&i.TenNguoiDat,
		&i.Email,
		&i.SoDienThoai,
		&i.NgayKhoiHanh,
		&i.NgayKetThuc,
		&i.TenTour,
		&i.NhaCungCapID,
	)
	return i, err
}

const getBookingStats = `-- name: GetBookingStats :one

SELECT 
    COUNT(*) FILTER (WHERE dc.trang_thai = 'cho_xac_nhan') AS cho_xac_nhan,
    COUNT(*) FILTER (WHERE dc.trang_thai = 'da_xac_nhan') AS da_xac_nhan,
    COUNT(*) FILTER (WHERE dc.trang_thai = 'da_thanh_toan') AS da_thanh_toan,
    COUNT(*) FILTER (WHERE dc.trang_thai = 'hoan_thanh') AS hoan_thanh,
    COUNT(*) FILTER (WHERE dc.trang_thai = 'da_huy') AS da_huy,
    COALESCE(SUM(dc.tong_tien) FILTER (WHERE dc.trang_thai IN ('da_thanh_toan', 'hoan_thanh')), 0) AS tong_doanh_thu
FROM dat_cho dc
JOIN khoi_hanh_tour kh ON kh.id = dc.khoi_hanh_id
JOIN tour t ON t.id = kh.tour_id
WHERE ($1::uuid IS NULL OR t.nha_cung_cap_id = $1)
    AND ($2::timestamp IS NULL OR dc.ngay_dat >= $2)
    AND ($3::timestamp IS NULL OR dc.ngay_dat <= $3)
`

type GetBookingStatsParams struct {
	Column1 pgtype.UUID      `json:"column_1"`
	Column2 pgtype.Timestamp `json:"column_2"`
	Column3 pgtype.Timestamp `json:"column_3"`
}

type GetBookingStatsRow struct {
	ChoXacNhan   int64       `json:"cho_xac_nhan"`
	DaXacNhan    int64       `json:"da_xac_nhan"`
	DaThanhToan  int64       `json:"da_thanh_toan"`
	HoanThanh    int64       `json:"hoan_thanh"`
	DaHuy        int64       `json:"da_huy"`
	TongDoanhThu interface{} `json:"tong_doanh_thu"`
}

// ===========================================
// THỐNG KÊ & BÁO CÁO
// ===========================================
// Thống kê booking theo nhà cung cấp
func (q *Queries) GetBookingStats(ctx context.Context, arg GetBookingStatsParams) (GetBookingStatsRow, error) {
	row := q.db.QueryRow(ctx, getBookingStats, arg.Column1, arg.Column2, arg.Column3)
	var i GetBookingStatsRow
	err := row.Scan(
		&i.ChoXacNhan,
		&i.DaXacNhan,
		&i.DaThanhToan,
		&i.HoanThanh,
		&i.DaHuy,
		&i.TongDoanhThu,
	)
	return i, err
}

const getBookingsByStatus = `-- name: GetBookingsByStatus :many
SELECT 
    dc.id, dc.nguoi_dung_id, dc.khoi_hanh_id, dc.so_nguoi_lon, dc.so_tre_em, dc.tong_tien, dc.don_vi_tien_te, dc.trang_thai, dc.phuong_thuc_thanh_toan, dc.ngay_dat, dc.ngay_cap_nhat,
    nd.ho_ten AS ten_nguoi_dat,
    nd.email,
    kh.ngay_khoi_hanh,
    kh.ngay_ket_thuc,
    t.tieu_de AS ten_tour
FROM dat_cho dc
JOIN nguoi_dung nd ON nd.id = dc.nguoi_dung_id
JOIN khoi_hanh_tour kh ON kh.id = dc.khoi_hanh_id
JOIN tour t ON t.id = kh.tour_id
WHERE dc.trang_thai = $1::trang_thai_dat_cho
    AND ($2::uuid IS NULL OR t.nha_cung_cap_id = $2)
ORDER BY dc.ngay_dat DESC
LIMIT $3 OFFSET $4
`

type GetBookingsByStatusParams struct {
	Column1 TrangThaiDatCho `json:"column_1"`
	Column2 pgtype.UUID     `json:"column_2"`
	Limit   int32           `json:"limit"`
	Offset  int32           `json:"offset"`
}

type GetBookingsByStatusRow struct {
	ID                  int32               `json:"id"`
	NguoiDungID         pgtype.UUID         `json:"nguoi_dung_id"`
	KhoiHanhID          int32               `json:"khoi_hanh_id"`
	SoNguoiLon          *int32              `json:"so_nguoi_lon"`
	SoTreEm             *int32              `json:"so_tre_em"`
	TongTien            pgtype.Numeric      `json:"tong_tien"`
	DonViTienTe         *string             `json:"don_vi_tien_te"`
	TrangThai           NullTrangThaiDatCho `json:"trang_thai"`
	PhuongThucThanhToan *string             `json:"phuong_thuc_thanh_toan"`
	NgayDat             pgtype.Timestamp    `json:"ngay_dat"`
	NgayCapNhat         pgtype.Timestamp    `json:"ngay_cap_nhat"`
	TenNguoiDat         string              `json:"ten_nguoi_dat"`
	Email               string              `json:"email"`
	NgayKhoiHanh        pgtype.Date         `json:"ngay_khoi_hanh"`
	NgayKetThuc         pgtype.Date         `json:"ngay_ket_thuc"`
	TenTour             string              `json:"ten_tour"`
}

// Lấy booking theo trạng thái
func (q *Queries) GetBookingsByStatus(ctx context.Context, arg GetBookingsByStatusParams) ([]GetBookingsByStatusRow, error) {
	rows, err := q.db.Query(ctx, getBookingsByStatus,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookingsByStatusRow
	for rows.Next() {
		var i GetBookingsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.NguoiDungID,
			&i.KhoiHanhID,
			&i.SoNguoiLon,
			&i.SoTreEm,
			&i.TongTien,
			&i.DonViTienTe,
			&i.TrangThai,
			&i.PhuongThucThanhToan,
			&i.NgayDat,
			&i.NgayCapNhat,
			&i.TenNguoiDat,
			&i.Email,
			&i.NgayKhoiHanh,
			&i.NgayKetThuc,
			&i.TenTour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingsByUser = `-- name: GetBookingsByUser :many
SELECT 
    dc.id, dc.nguoi_dung_id, dc.khoi_hanh_id, dc.so_nguoi_lon, dc.so_tre_em, dc.tong_tien, dc.don_vi_tien_te, dc.trang_thai, dc.phuong_thuc_thanh_toan, dc.ngay_dat, dc.ngay_cap_nhat,
    kh.ngay_khoi_hanh,
    kh.ngay_ket_thuc,
    kh.trang_thai AS trang_thai_khoi_hanh, -- Trạng thái thực tế của chuyến đi
    t.tieu_de AS ten_tour,
    -- Giả sử bảng anh_tour tồn tại như trong subquery của bạn
    (SELECT duong_dan FROM anh_tour WHERE tour_id = t.id AND la_anh_chinh = TRUE LIMIT 1) AS anh_tour
FROM dat_cho dc
JOIN khoi_hanh_tour kh ON kh.id = dc.khoi_hanh_id
JOIN tour t ON t.id = kh.tour_id
WHERE 
    dc.nguoi_dung_id = $1
    -- Lọc theo trạng thái đặt chỗ (truyền NULL hoặc empty string nếu muốn lấy tất cả)
    AND CASE 
        WHEN COALESCE($4::text, '') = '' THEN TRUE
        ELSE dc.trang_thai = ($4::text)::trang_thai_dat_cho
    END
    -- Lọc theo trạng thái khởi hành (truyền NULL hoặc empty string nếu muốn lấy tất cả)
    -- Hỗ trợ nhiều giá trị phân cách bằng dấu phẩy
    AND CASE 
        WHEN COALESCE($5::text, '') = '' THEN TRUE
        WHEN $5::text LIKE '%,%' THEN 
            kh.trang_thai IN (
                SELECT unnest(string_to_array($5::text, ','))::trang_thai_khoi_hanh
            )
        ELSE kh.trang_thai = ($5::text)::trang_thai_khoi_hanh
    END
ORDER BY dc.ngay_dat DESC
LIMIT $2 OFFSET $3
`

type GetBookingsByUserParams struct {
	NguoiDungID pgtype.UUID `json:"nguoi_dung_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	Column4     string      `json:"column_4"`
	Column5     string      `json:"column_5"`
}

type GetBookingsByUserRow struct {
	ID                  int32                 `json:"id"`
	NguoiDungID         pgtype.UUID           `json:"nguoi_dung_id"`
	KhoiHanhID          int32                 `json:"khoi_hanh_id"`
	SoNguoiLon          *int32                `json:"so_nguoi_lon"`
	SoTreEm             *int32                `json:"so_tre_em"`
	TongTien            pgtype.Numeric        `json:"tong_tien"`
	DonViTienTe         *string               `json:"don_vi_tien_te"`
	TrangThai           NullTrangThaiDatCho   `json:"trang_thai"`
	PhuongThucThanhToan *string               `json:"phuong_thuc_thanh_toan"`
	NgayDat             pgtype.Timestamp      `json:"ngay_dat"`
	NgayCapNhat         pgtype.Timestamp      `json:"ngay_cap_nhat"`
	NgayKhoiHanh        pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc         pgtype.Date           `json:"ngay_ket_thuc"`
	TrangThaiKhoiHanh   NullTrangThaiKhoiHanh `json:"trang_thai_khoi_hanh"`
	TenTour             string                `json:"ten_tour"`
	AnhTour             string                `json:"anh_tour"`
}

// Lấy danh sách đặt chỗ của người dùng
func (q *Queries) GetBookingsByUser(ctx context.Context, arg GetBookingsByUserParams) ([]GetBookingsByUserRow, error) {
	rows, err := q.db.Query(ctx, getBookingsByUser,
		arg.NguoiDungID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookingsByUserRow
	for rows.Next() {
		var i GetBookingsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.NguoiDungID,
			&i.KhoiHanhID,
			&i.SoNguoiLon,
			&i.SoTreEm,
			&i.TongTien,
			&i.DonViTienTe,
			&i.TrangThai,
			&i.PhuongThucThanhToan,
			&i.NgayDat,
			&i.NgayCapNhat,
			&i.NgayKhoiHanh,
			&i.NgayKetThuc,
			&i.TrangThaiKhoiHanh,
			&i.TenTour,
			&i.AnhTour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingsByUserId = `-- name: GetBookingsByUserId :many
SELECT 
    dc.id, dc.nguoi_dung_id, dc.khoi_hanh_id, dc.so_nguoi_lon, dc.so_tre_em, dc.tong_tien, dc.don_vi_tien_te, dc.trang_thai, dc.phuong_thuc_thanh_toan, dc.ngay_dat, dc.ngay_cap_nhat,
    nd.ho_ten AS ten_nguoi_dat,
    kh.ngay_khoi_hanh,
    kh.ngay_ket_thuc,
    t.tieu_de AS ten_tour
FROM dat_cho dc
JOIN nguoi_dung nd ON nd.id = dc.nguoi_dung_id
JOIN khoi_hanh_tour kh ON kh.id = dc.khoi_hanh_id
JOIN tour t ON t.id = kh.tour_id
WHERE dc.nguoi_dung_id = $1
`

type GetBookingsByUserIdRow struct {
	ID                  int32               `json:"id"`
	NguoiDungID         pgtype.UUID         `json:"nguoi_dung_id"`
	KhoiHanhID          int32               `json:"khoi_hanh_id"`
	SoNguoiLon          *int32              `json:"so_nguoi_lon"`
	SoTreEm             *int32              `json:"so_tre_em"`
	TongTien            pgtype.Numeric      `json:"tong_tien"`
	DonViTienTe         *string             `json:"don_vi_tien_te"`
	TrangThai           NullTrangThaiDatCho `json:"trang_thai"`
	PhuongThucThanhToan *string             `json:"phuong_thuc_thanh_toan"`
	NgayDat             pgtype.Timestamp    `json:"ngay_dat"`
	NgayCapNhat         pgtype.Timestamp    `json:"ngay_cap_nhat"`
	TenNguoiDat         string              `json:"ten_nguoi_dat"`
	NgayKhoiHanh        pgtype.Date         `json:"ngay_khoi_hanh"`
	NgayKetThuc         pgtype.Date         `json:"ngay_ket_thuc"`
	TenTour             string              `json:"ten_tour"`
}

func (q *Queries) GetBookingsByUserId(ctx context.Context, nguoiDungID pgtype.UUID) ([]GetBookingsByUserIdRow, error) {
	rows, err := q.db.Query(ctx, getBookingsByUserId, nguoiDungID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookingsByUserIdRow
	for rows.Next() {
		var i GetBookingsByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.NguoiDungID,
			&i.KhoiHanhID,
			&i.SoNguoiLon,
			&i.SoTreEm,
			&i.TongTien,
			&i.DonViTienTe,
			&i.TrangThai,
			&i.PhuongThucThanhToan,
			&i.NgayDat,
			&i.NgayCapNhat,
			&i.TenNguoiDat,
			&i.NgayKhoiHanh,
			&i.NgayKetThuc,
			&i.TenTour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCancelledBookings = `-- name: GetCancelledBookings :many
SELECT 
    dc.id, dc.nguoi_dung_id, dc.khoi_hanh_id, dc.so_nguoi_lon, dc.so_tre_em, dc.tong_tien, dc.don_vi_tien_te, dc.trang_thai, dc.phuong_thuc_thanh_toan, dc.ngay_dat, dc.ngay_cap_nhat,
    nd.ho_ten AS ten_nguoi_dat,
    kh.ngay_khoi_hanh,
    t.tieu_de AS ten_tour
FROM dat_cho dc
JOIN nguoi_dung nd ON nd.id = dc.nguoi_dung_id
JOIN khoi_hanh_tour kh ON kh.id = dc.khoi_hanh_id
JOIN tour t ON t.id = kh.tour_id
WHERE dc.trang_thai = 'da_huy'
    AND ($1::uuid IS NULL OR t.nha_cung_cap_id = $1)
ORDER BY dc.ngay_cap_nhat DESC
LIMIT $2 OFFSET $3
`

type GetCancelledBookingsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type GetCancelledBookingsRow struct {
	ID                  int32               `json:"id"`
	NguoiDungID         pgtype.UUID         `json:"nguoi_dung_id"`
	KhoiHanhID          int32               `json:"khoi_hanh_id"`
	SoNguoiLon          *int32              `json:"so_nguoi_lon"`
	SoTreEm             *int32              `json:"so_tre_em"`
	TongTien            pgtype.Numeric      `json:"tong_tien"`
	DonViTienTe         *string             `json:"don_vi_tien_te"`
	TrangThai           NullTrangThaiDatCho `json:"trang_thai"`
	PhuongThucThanhToan *string             `json:"phuong_thuc_thanh_toan"`
	NgayDat             pgtype.Timestamp    `json:"ngay_dat"`
	NgayCapNhat         pgtype.Timestamp    `json:"ngay_cap_nhat"`
	TenNguoiDat         string              `json:"ten_nguoi_dat"`
	NgayKhoiHanh        pgtype.Date         `json:"ngay_khoi_hanh"`
	TenTour             string              `json:"ten_tour"`
}

// Lấy danh sách booking đã hủy
func (q *Queries) GetCancelledBookings(ctx context.Context, arg GetCancelledBookingsParams) ([]GetCancelledBookingsRow, error) {
	rows, err := q.db.Query(ctx, getCancelledBookings, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCancelledBookingsRow
	for rows.Next() {
		var i GetCancelledBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.NguoiDungID,
			&i.KhoiHanhID,
			&i.SoNguoiLon,
			&i.SoTreEm,
			&i.TongTien,
			&i.DonViTienTe,
			&i.TrangThai,
			&i.PhuongThucThanhToan,
			&i.NgayDat,
			&i.NgayCapNhat,
			&i.TenNguoiDat,
			&i.NgayKhoiHanh,
			&i.TenTour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDepartureById = `-- name: GetDepartureById :one
SELECT 
    kh.id, kh.tour_id, kh.ngay_khoi_hanh, kh.ngay_ket_thuc, kh.suc_chua, kh.so_cho_da_dat, kh.trang_thai, kh.ghi_chu, kh.ngay_tao, kh.ngay_cap_nhat,
    t.tieu_de AS ten_tour,
    t.gia_nguoi_lon,
    t.gia_tre_em,
    t.don_vi_tien_te
FROM khoi_hanh_tour kh
JOIN tour t ON t.id = kh.tour_id
WHERE kh.id = $1
`

type GetDepartureByIdRow struct {
	ID           int32                 `json:"id"`
	TourID       int32                 `json:"tour_id"`
	NgayKhoiHanh pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc  pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua      int32                 `json:"suc_chua"`
	SoChoDaDat   *int32                `json:"so_cho_da_dat"`
	TrangThai    NullTrangThaiKhoiHanh `json:"trang_thai"`
	GhiChu       *string               `json:"ghi_chu"`
	NgayTao      pgtype.Timestamp      `json:"ngay_tao"`
	NgayCapNhat  pgtype.Timestamp      `json:"ngay_cap_nhat"`
	TenTour      string                `json:"ten_tour"`
	GiaNguoiLon  pgtype.Numeric        `json:"gia_nguoi_lon"`
	GiaTreEm     pgtype.Numeric        `json:"gia_tre_em"`
	DonViTienTe  *string               `json:"don_vi_tien_te"`
}

// Lấy thông tin chi tiết một ngày khởi hành
func (q *Queries) GetDepartureById(ctx context.Context, id int32) (GetDepartureByIdRow, error) {
	row := q.db.QueryRow(ctx, getDepartureById, id)
	var i GetDepartureByIdRow
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.NgayKhoiHanh,
		&i.NgayKetThuc,
		&i.SucChua,
		&i.SoChoDaDat,
		&i.TrangThai,
		&i.GhiChu,
		&i.NgayTao,
		&i.NgayCapNhat,
		&i.TenTour,
		&i.GiaNguoiLon,
		&i.GiaTreEm,
		&i.DonViTienTe,
	)
	return i, err
}

const getPassengersByBooking = `-- name: GetPassengersByBooking :many
SELECT id, dat_cho_id, ho_ten, ngay_sinh, loai_khach, gioi_tinh, so_giay_to_tuy_thanh, quoc_tich, ghi_chu FROM hanh_khach
WHERE dat_cho_id = $1
ORDER BY loai_khach DESC, id ASC
`

// Lấy danh sách hành khách của một booking
func (q *Queries) GetPassengersByBooking(ctx context.Context, datChoID int32) ([]HanhKhach, error) {
	rows, err := q.db.Query(ctx, getPassengersByBooking, datChoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HanhKhach
	for rows.Next() {
		var i HanhKhach
		if err := rows.Scan(
			&i.ID,
			&i.DatChoID,
			&i.HoTen,
			&i.NgaySinh,
			&i.LoaiKhach,
			&i.GioiTinh,
			&i.SoGiayToTuyThanh,
			&i.QuocTich,
			&i.GhiChu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentGateways = `-- name: GetPaymentGateways :many
SELECT id, ten_hien_thi, hoat_dong, phi_giao_dich_phan_tram FROM cong_thanh_toan
WHERE hoat_dong = TRUE
`

// Lấy danh sách cổng thanh toán đang hoạt động
func (q *Queries) GetPaymentGateways(ctx context.Context) ([]CongThanhToan, error) {
	rows, err := q.db.Query(ctx, getPaymentGateways)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CongThanhToan
	for rows.Next() {
		var i CongThanhToan
		if err := rows.Scan(
			&i.ID,
			&i.TenHienThi,
			&i.HoatDong,
			&i.PhiGiaoDichPhanTram,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingBookings = `-- name: GetPendingBookings :many
SELECT 
    dc.id, dc.nguoi_dung_id, dc.khoi_hanh_id, dc.so_nguoi_lon, dc.so_tre_em, dc.tong_tien, dc.don_vi_tien_te, dc.trang_thai, dc.phuong_thuc_thanh_toan, dc.ngay_dat, dc.ngay_cap_nhat,
    nd.ho_ten AS ten_nguoi_dat,
    nd.email,
    nd.so_dien_thoai,
    kh.ngay_khoi_hanh,
    t.tieu_de AS ten_tour,
    t.nha_cung_cap_id
FROM dat_cho dc
JOIN nguoi_dung nd ON nd.id = dc.nguoi_dung_id
JOIN khoi_hanh_tour kh ON kh.id = dc.khoi_hanh_id
JOIN tour t ON t.id = kh.tour_id
WHERE dc.trang_thai = 'cho_xac_nhan'
    AND ($1::uuid IS NULL OR t.nha_cung_cap_id = $1)
ORDER BY dc.ngay_dat ASC
LIMIT $2 OFFSET $3
`

type GetPendingBookingsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type GetPendingBookingsRow struct {
	ID                  int32               `json:"id"`
	NguoiDungID         pgtype.UUID         `json:"nguoi_dung_id"`
	KhoiHanhID          int32               `json:"khoi_hanh_id"`
	SoNguoiLon          *int32              `json:"so_nguoi_lon"`
	SoTreEm             *int32              `json:"so_tre_em"`
	TongTien            pgtype.Numeric      `json:"tong_tien"`
	DonViTienTe         *string             `json:"don_vi_tien_te"`
	TrangThai           NullTrangThaiDatCho `json:"trang_thai"`
	PhuongThucThanhToan *string             `json:"phuong_thuc_thanh_toan"`
	NgayDat             pgtype.Timestamp    `json:"ngay_dat"`
	NgayCapNhat         pgtype.Timestamp    `json:"ngay_cap_nhat"`
	TenNguoiDat         string              `json:"ten_nguoi_dat"`
	Email               string              `json:"email"`
	SoDienThoai         *string             `json:"so_dien_thoai"`
	NgayKhoiHanh        pgtype.Date         `json:"ngay_khoi_hanh"`
	TenTour             string              `json:"ten_tour"`
	NhaCungCapID        pgtype.UUID         `json:"nha_cung_cap_id"`
}

// Lấy danh sách booking chờ xác nhận (dành cho Admin/NCC)
func (q *Queries) GetPendingBookings(ctx context.Context, arg GetPendingBookingsParams) ([]GetPendingBookingsRow, error) {
	rows, err := q.db.Query(ctx, getPendingBookings, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingBookingsRow
	for rows.Next() {
		var i GetPendingBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.NguoiDungID,
			&i.KhoiHanhID,
			&i.SoNguoiLon,
			&i.SoTreEm,
			&i.TongTien,
			&i.DonViTienTe,
			&i.TrangThai,
			&i.PhuongThucThanhToan,
			&i.NgayDat,
			&i.NgayCapNhat,
			&i.TenNguoiDat,
			&i.Email,
			&i.SoDienThoai,
			&i.NgayKhoiHanh,
			&i.TenTour,
			&i.NhaCungCapID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefundStats = `-- name: GetRefundStats :one
WITH refund_info AS (
    SELECT 
        dc.id AS booking_id,
        dc.tong_tien,
        dc.ngay_cap_nhat AS ngay_huy,
        kh.ngay_khoi_hanh,
        (kh.ngay_khoi_hanh - CURRENT_DATE)::INT AS so_ngay_truoc_khoi_hanh,
        t.nha_cung_cap_id
    FROM dat_cho dc
    JOIN khoi_hanh_tour kh ON kh.id = dc.khoi_hanh_id
    JOIN tour t ON t.id = kh.tour_id
    WHERE dc.trang_thai = 'da_huy'
        AND ($1::timestamp IS NULL OR dc.ngay_cap_nhat >= $1::timestamp)
        AND ($2::timestamp IS NULL OR dc.ngay_cap_nhat <= $2::timestamp)
)
SELECT 
    COUNT(*)::int AS tong_so_refund,
    COALESCE(SUM(ri.tong_tien), 0)::numeric AS tong_tien_goc,
    COALESCE(SUM(
        ri.tong_tien * 
        CASE 
            WHEN ri.so_ngay_truoc_khoi_hanh >= 15 THEN 100.00
            WHEN ri.so_ngay_truoc_khoi_hanh >= 7 THEN 90.00
            WHEN ri.so_ngay_truoc_khoi_hanh >= 3 THEN 70.00
            WHEN ri.so_ngay_truoc_khoi_hanh >= 1 THEN 50.00
            ELSE 0.00
        END / 100.00
    ), 0)::numeric AS tong_tien_hoan,
    COALESCE(SUM(
        ri.tong_tien * 
        (100.00 - 
            CASE 
                WHEN ri.so_ngay_truoc_khoi_hanh >= 15 THEN 100.00
                WHEN ri.so_ngay_truoc_khoi_hanh >= 7 THEN 90.00
                WHEN ri.so_ngay_truoc_khoi_hanh >= 3 THEN 70.00
                WHEN ri.so_ngay_truoc_khoi_hanh >= 1 THEN 50.00
                ELSE 0.00
            END
        ) / 100.00
    ), 0)::numeric AS tong_tien_phat,
    COUNT(*) FILTER (WHERE ri.so_ngay_truoc_khoi_hanh >= 15)::int AS hoan_100_percent,
    COUNT(*) FILTER (WHERE ri.so_ngay_truoc_khoi_hanh >= 7 AND ri.so_ngay_truoc_khoi_hanh < 15)::int AS hoan_90_percent,
    COUNT(*) FILTER (WHERE ri.so_ngay_truoc_khoi_hanh >= 3 AND ri.so_ngay_truoc_khoi_hanh < 7)::int AS hoan_70_percent,
    COUNT(*) FILTER (WHERE ri.so_ngay_truoc_khoi_hanh >= 1 AND ri.so_ngay_truoc_khoi_hanh < 3)::int AS hoan_50_percent,
    COUNT(*) FILTER (WHERE ri.so_ngay_truoc_khoi_hanh < 1)::int AS khong_hoan
FROM refund_info ri
`

type GetRefundStatsParams struct {
	Column1 pgtype.Timestamp `json:"column_1"`
	Column2 pgtype.Timestamp `json:"column_2"`
}

type GetRefundStatsRow struct {
	TongSoRefund   int32          `json:"tong_so_refund"`
	TongTienGoc    pgtype.Numeric `json:"tong_tien_goc"`
	TongTienHoan   pgtype.Numeric `json:"tong_tien_hoan"`
	TongTienPhat   pgtype.Numeric `json:"tong_tien_phat"`
	Hoan100Percent int32          `json:"hoan_100_percent"`
	Hoan90Percent  int32          `json:"hoan_90_percent"`
	Hoan70Percent  int32          `json:"hoan_70_percent"`
	Hoan50Percent  int32          `json:"hoan_50_percent"`
	KhongHoan      int32          `json:"khong_hoan"`
}

// Thống kê refund cho admin
func (q *Queries) GetRefundStats(ctx context.Context, arg GetRefundStatsParams) (GetRefundStatsRow, error) {
	row := q.db.QueryRow(ctx, getRefundStats, arg.Column1, arg.Column2)
	var i GetRefundStatsRow
	err := row.Scan(
		&i.TongSoRefund,
		&i.TongTienGoc,
		&i.TongTienHoan,
		&i.TongTienPhat,
		&i.Hoan100Percent,
		&i.Hoan90Percent,
		&i.Hoan70Percent,
		&i.Hoan50Percent,
		&i.KhongHoan,
	)
	return i, err
}

const getSupplierRefundStats = `-- name: GetSupplierRefundStats :one
WITH refund_info AS (
    SELECT 
        dc.id AS booking_id,
        dc.tong_tien,
        dc.ngay_cap_nhat AS ngay_huy,
        kh.ngay_khoi_hanh,
        (kh.ngay_khoi_hanh - CURRENT_DATE)::INT AS so_ngay_truoc_khoi_hanh
    FROM dat_cho dc
    JOIN khoi_hanh_tour kh ON kh.id = dc.khoi_hanh_id
    JOIN tour t ON t.id = kh.tour_id
    WHERE dc.trang_thai = 'da_huy'
        AND t.nha_cung_cap_id = $1::uuid
        AND ($2::timestamp IS NULL OR dc.ngay_cap_nhat >= $2::timestamp)
        AND ($3::timestamp IS NULL OR dc.ngay_cap_nhat <= $3::timestamp)
)
SELECT 
    COUNT(*)::int AS tong_so_refund,
    COALESCE(SUM(ri.tong_tien), 0)::numeric AS tong_tien_goc,
    COALESCE(SUM(
        ri.tong_tien * 
        CASE 
            WHEN ri.so_ngay_truoc_khoi_hanh >= 15 THEN 100.00
            WHEN ri.so_ngay_truoc_khoi_hanh >= 7 THEN 90.00
            WHEN ri.so_ngay_truoc_khoi_hanh >= 3 THEN 70.00
            WHEN ri.so_ngay_truoc_khoi_hanh >= 1 THEN 50.00
            ELSE 0.00
        END / 100.00
    ), 0)::numeric AS tong_tien_hoan,
    COALESCE(SUM(
        ri.tong_tien * 
        (100.00 - 
            CASE 
                WHEN ri.so_ngay_truoc_khoi_hanh >= 15 THEN 100.00
                WHEN ri.so_ngay_truoc_khoi_hanh >= 7 THEN 90.00
                WHEN ri.so_ngay_truoc_khoi_hanh >= 3 THEN 70.00
                WHEN ri.so_ngay_truoc_khoi_hanh >= 1 THEN 50.00
                ELSE 0.00
            END
        ) / 100.00
    ), 0)::numeric AS tong_tien_phat,
    COUNT(*) FILTER (WHERE ri.so_ngay_truoc_khoi_hanh >= 15)::int AS hoan_100_percent,
    COUNT(*) FILTER (WHERE ri.so_ngay_truoc_khoi_hanh >= 7 AND ri.so_ngay_truoc_khoi_hanh < 15)::int AS hoan_90_percent,
    COUNT(*) FILTER (WHERE ri.so_ngay_truoc_khoi_hanh >= 3 AND ri.so_ngay_truoc_khoi_hanh < 7)::int AS hoan_70_percent,
    COUNT(*) FILTER (WHERE ri.so_ngay_truoc_khoi_hanh >= 1 AND ri.so_ngay_truoc_khoi_hanh < 3)::int AS hoan_50_percent,
    COUNT(*) FILTER (WHERE ri.so_ngay_truoc_khoi_hanh < 1)::int AS khong_hoan
FROM refund_info ri
`

type GetSupplierRefundStatsParams struct {
	Column1 pgtype.UUID      `json:"column_1"`
	Column2 pgtype.Timestamp `json:"column_2"`
	Column3 pgtype.Timestamp `json:"column_3"`
}

type GetSupplierRefundStatsRow struct {
	TongSoRefund   int32          `json:"tong_so_refund"`
	TongTienGoc    pgtype.Numeric `json:"tong_tien_goc"`
	TongTienHoan   pgtype.Numeric `json:"tong_tien_hoan"`
	TongTienPhat   pgtype.Numeric `json:"tong_tien_phat"`
	Hoan100Percent int32          `json:"hoan_100_percent"`
	Hoan90Percent  int32          `json:"hoan_90_percent"`
	Hoan70Percent  int32          `json:"hoan_70_percent"`
	Hoan50Percent  int32          `json:"hoan_50_percent"`
	KhongHoan      int32          `json:"khong_hoan"`
}

// Thống kê refund cho supplier
func (q *Queries) GetSupplierRefundStats(ctx context.Context, arg GetSupplierRefundStatsParams) (GetSupplierRefundStatsRow, error) {
	row := q.db.QueryRow(ctx, getSupplierRefundStats, arg.Column1, arg.Column2, arg.Column3)
	var i GetSupplierRefundStatsRow
	err := row.Scan(
		&i.TongSoRefund,
		&i.TongTienGoc,
		&i.TongTienHoan,
		&i.TongTienPhat,
		&i.Hoan100Percent,
		&i.Hoan90Percent,
		&i.Hoan70Percent,
		&i.Hoan50Percent,
		&i.KhongHoan,
	)
	return i, err
}

const getSupplierRefunds = `-- name: GetSupplierRefunds :many
WITH refund_info AS (
    SELECT 
        dc.id AS booking_id,
        dc.tong_tien,
        kh.ngay_khoi_hanh,
        -- Tính số ngày trước khởi hành tại thời điểm hủy (ngay_cap_nhat)
        (kh.ngay_khoi_hanh - DATE(dc.ngay_cap_nhat))::INT AS so_ngay_truoc_khoi_hanh
    FROM dat_cho dc
    JOIN khoi_hanh_tour kh ON kh.id = dc.khoi_hanh_id
    JOIN tour t ON t.id = kh.tour_id
    WHERE dc.trang_thai = 'da_huy'
        AND t.nha_cung_cap_id = $1::uuid
)
SELECT 
    dc.id AS booking_id,
    dc.ngay_dat,
    dc.ngay_cap_nhat AS ngay_huy,
    dc.tong_tien,
    dc.don_vi_tien_te,
    dc.so_nguoi_lon,
    dc.so_tre_em,
    dc.phuong_thuc_thanh_toan,
    dc.trang_thai,
    
    -- Thông tin khách hàng
    nd.id AS customer_id,
    nd.ho_ten AS customer_name,
    nd.email AS customer_email,
    nd.so_dien_thoai AS customer_phone,
    
    -- Thông tin tour
    t.id AS tour_id,
    t.tieu_de AS tour_title,
    
    -- Thông tin khởi hành
    kh.id AS departure_id,
    kh.ngay_khoi_hanh,
    kh.ngay_ket_thuc,
    
    -- Thông tin refund
    ri.so_ngay_truoc_khoi_hanh,
    CASE 
        WHEN ri.so_ngay_truoc_khoi_hanh >= 15 THEN 100.00
        WHEN ri.so_ngay_truoc_khoi_hanh >= 7 THEN 90.00
        WHEN ri.so_ngay_truoc_khoi_hanh >= 3 THEN 70.00
        WHEN ri.so_ngay_truoc_khoi_hanh >= 1 THEN 50.00
        ELSE 0.00
    END::DECIMAL(5,2) AS phan_tram_hoan,
    (ri.tong_tien * 
        CASE 
            WHEN ri.so_ngay_truoc_khoi_hanh >= 15 THEN 100.00
            WHEN ri.so_ngay_truoc_khoi_hanh >= 7 THEN 90.00
            WHEN ri.so_ngay_truoc_khoi_hanh >= 3 THEN 70.00
            WHEN ri.so_ngay_truoc_khoi_hanh >= 1 THEN 50.00
            ELSE 0.00
        END / 100.00)::DECIMAL(12,2) AS so_tien_hoan,
    CASE 
        WHEN ri.so_ngay_truoc_khoi_hanh >= 15 THEN 'Hủy trước 15 ngày - hoàn 100%'
        WHEN ri.so_ngay_truoc_khoi_hanh >= 7 THEN 'Hủy trước 7 ngày - hoàn 90%'
        WHEN ri.so_ngay_truoc_khoi_hanh >= 3 THEN 'Hủy trước 3 ngày - hoàn 70%'
        WHEN ri.so_ngay_truoc_khoi_hanh >= 1 THEN 'Hủy trước 24 giờ - hoàn 50%'
        ELSE 'Hủy trong 24 giờ - không hoàn tiền'
    END::TEXT AS ly_do
FROM dat_cho dc
JOIN nguoi_dung nd ON nd.id = dc.nguoi_dung_id
JOIN khoi_hanh_tour kh ON kh.id = dc.khoi_hanh_id
JOIN tour t ON t.id = kh.tour_id
JOIN refund_info ri ON ri.booking_id = dc.id
WHERE dc.trang_thai = 'da_huy'
    AND t.nha_cung_cap_id = $1::uuid
    AND ($2::timestamp IS NULL OR dc.ngay_cap_nhat >= $2::timestamp)
    AND ($3::timestamp IS NULL OR dc.ngay_cap_nhat <= $3::timestamp)
    AND ($4::text IS NULL OR nd.ho_ten ILIKE '%' || $4::text || '%' OR nd.email ILIKE '%' || $4::text || '%' OR t.tieu_de ILIKE '%' || $4::text || '%')
ORDER BY dc.ngay_cap_nhat DESC
LIMIT $5 OFFSET $6
`

type GetSupplierRefundsParams struct {
	Column1 pgtype.UUID      `json:"column_1"`
	Column2 pgtype.Timestamp `json:"column_2"`
	Column3 pgtype.Timestamp `json:"column_3"`
	Column4 string           `json:"column_4"`
	Limit   int32            `json:"limit"`
	Offset  int32            `json:"offset"`
}

type GetSupplierRefundsRow struct {
	BookingID           int32               `json:"booking_id"`
	NgayDat             pgtype.Timestamp    `json:"ngay_dat"`
	NgayHuy             pgtype.Timestamp    `json:"ngay_huy"`
	TongTien            pgtype.Numeric      `json:"tong_tien"`
	DonViTienTe         *string             `json:"don_vi_tien_te"`
	SoNguoiLon          *int32              `json:"so_nguoi_lon"`
	SoTreEm             *int32              `json:"so_tre_em"`
	PhuongThucThanhToan *string             `json:"phuong_thuc_thanh_toan"`
	TrangThai           NullTrangThaiDatCho `json:"trang_thai"`
	CustomerID          pgtype.UUID         `json:"customer_id"`
	CustomerName        string              `json:"customer_name"`
	CustomerEmail       string              `json:"customer_email"`
	CustomerPhone       *string             `json:"customer_phone"`
	TourID              int32               `json:"tour_id"`
	TourTitle           string              `json:"tour_title"`
	DepartureID         int32               `json:"departure_id"`
	NgayKhoiHanh        pgtype.Date         `json:"ngay_khoi_hanh"`
	NgayKetThuc         pgtype.Date         `json:"ngay_ket_thuc"`
	SoNgayTruocKhoiHanh int32               `json:"so_ngay_truoc_khoi_hanh"`
	PhanTramHoan        pgtype.Numeric      `json:"phan_tram_hoan"`
	SoTienHoan          pgtype.Numeric      `json:"so_tien_hoan"`
	LyDo                string              `json:"ly_do"`
}

// Lấy refund cho supplier (chỉ tour của họ)
func (q *Queries) GetSupplierRefunds(ctx context.Context, arg GetSupplierRefundsParams) ([]GetSupplierRefundsRow, error) {
	rows, err := q.db.Query(ctx, getSupplierRefunds,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSupplierRefundsRow
	for rows.Next() {
		var i GetSupplierRefundsRow
		if err := rows.Scan(
			&i.BookingID,
			&i.NgayDat,
			&i.NgayHuy,
			&i.TongTien,
			&i.DonViTienTe,
			&i.SoNguoiLon,
			&i.SoTreEm,
			&i.PhuongThucThanhToan,
			&i.TrangThai,
			&i.CustomerID,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.TourID,
			&i.TourTitle,
			&i.DepartureID,
			&i.NgayKhoiHanh,
			&i.NgayKetThuc,
			&i.SoNgayTruocKhoiHanh,
			&i.PhanTramHoan,
			&i.SoTienHoan,
			&i.LyDo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByCode = `-- name: GetTransactionByCode :one
SELECT id, dat_cho_id, nguoi_dung_id, ma_giao_dich_noi_bo, ma_tham_chieu_cong_thanh_toan, cong_thanh_toan_id, so_tien, loai_giao_dich, trang_thai, noi_dung_chuyen_khoan, ngay_tao, ngay_hoan_thanh FROM lich_su_giao_dich
WHERE ma_giao_dich_noi_bo = $1
`

// Tìm giao dịch theo mã nội bộ
func (q *Queries) GetTransactionByCode(ctx context.Context, maGiaoDichNoiBo string) (LichSuGiaoDich, error) {
	row := q.db.QueryRow(ctx, getTransactionByCode, maGiaoDichNoiBo)
	var i LichSuGiaoDich
	err := row.Scan(
		&i.ID,
		&i.DatChoID,
		&i.NguoiDungID,
		&i.MaGiaoDichNoiBo,
		&i.MaThamChieuCongThanhToan,
		&i.CongThanhToanID,
		&i.SoTien,
		&i.LoaiGiaoDich,
		&i.TrangThai,
		&i.NoiDungChuyenKhoan,
		&i.NgayTao,
		&i.NgayHoanThanh,
	)
	return i, err
}

const getTransactionsByBooking = `-- name: GetTransactionsByBooking :many
SELECT 
    lsgd.id, lsgd.dat_cho_id, lsgd.nguoi_dung_id, lsgd.ma_giao_dich_noi_bo, lsgd.ma_tham_chieu_cong_thanh_toan, lsgd.cong_thanh_toan_id, lsgd.so_tien, lsgd.loai_giao_dich, lsgd.trang_thai, lsgd.noi_dung_chuyen_khoan, lsgd.ngay_tao, lsgd.ngay_hoan_thanh,
    ctt.ten_hien_thi AS ten_cong_thanh_toan
FROM lich_su_giao_dich lsgd
LEFT JOIN cong_thanh_toan ctt ON ctt.id = lsgd.cong_thanh_toan_id
WHERE lsgd.dat_cho_id = $1
ORDER BY lsgd.ngay_tao DESC
`

type GetTransactionsByBookingRow struct {
	ID                       int32                  `json:"id"`
	DatChoID                 *int32                 `json:"dat_cho_id"`
	NguoiDungID              pgtype.UUID            `json:"nguoi_dung_id"`
	MaGiaoDichNoiBo          string                 `json:"ma_giao_dich_noi_bo"`
	MaThamChieuCongThanhToan *string                `json:"ma_tham_chieu_cong_thanh_toan"`
	CongThanhToanID          *string                `json:"cong_thanh_toan_id"`
	SoTien                   pgtype.Numeric         `json:"so_tien"`
	LoaiGiaoDich             *string                `json:"loai_giao_dich"`
	TrangThai                NullTrangThaiThanhToan `json:"trang_thai"`
	NoiDungChuyenKhoan       *string                `json:"noi_dung_chuyen_khoan"`
	NgayTao                  pgtype.Timestamp       `json:"ngay_tao"`
	NgayHoanThanh            pgtype.Timestamp       `json:"ngay_hoan_thanh"`
	TenCongThanhToan         *string                `json:"ten_cong_thanh_toan"`
}

// Lấy lịch sử giao dịch của một booking
func (q *Queries) GetTransactionsByBooking(ctx context.Context, datChoID *int32) ([]GetTransactionsByBookingRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsByBooking, datChoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsByBookingRow
	for rows.Next() {
		var i GetTransactionsByBookingRow
		if err := rows.Scan(
			&i.ID,
			&i.DatChoID,
			&i.NguoiDungID,
			&i.MaGiaoDichNoiBo,
			&i.MaThamChieuCongThanhToan,
			&i.CongThanhToanID,
			&i.SoTien,
			&i.LoaiGiaoDich,
			&i.TrangThai,
			&i.NoiDungChuyenKhoan,
			&i.NgayTao,
			&i.NgayHoanThanh,
			&i.TenCongThanhToan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const holdSeat = `-- name: HoldSeat :exec
SELECT hold_seat($1::int, $2::int, $3::int)
`

type HoldSeatParams struct {
	KhoiHanhID int32 `json:"khoi_hanh_id"`
	SoNguoiLon int32 `json:"so_nguoi_lon"`
	SoTreEm    int32 `json:"so_tre_em"`
}

func (q *Queries) HoldSeat(ctx context.Context, arg HoldSeatParams) error {
	_, err := q.db.Exec(ctx, holdSeat, arg.KhoiHanhID, arg.SoNguoiLon, arg.SoTreEm)
	return err
}

const updateBookingPaymentStatus = `-- name: UpdateBookingPaymentStatus :one
UPDATE dat_cho
SET 
    trang_thai = 'da_thanh_toan',
    phuong_thuc_thanh_toan = $2,
    ngay_cap_nhat = CURRENT_TIMESTAMP
WHERE id = $1 AND trang_thai IN ('cho_xac_nhan', 'da_xac_nhan')
RETURNING id, nguoi_dung_id, khoi_hanh_id, so_nguoi_lon, so_tre_em, tong_tien, don_vi_tien_te, trang_thai, phuong_thuc_thanh_toan, ngay_dat, ngay_cap_nhat
`

type UpdateBookingPaymentStatusParams struct {
	ID                  int32   `json:"id"`
	PhuongThucThanhToan *string `json:"phuong_thuc_thanh_toan"`
}

// Cập nhật trạng thái booking sau khi thanh toán thành công
func (q *Queries) UpdateBookingPaymentStatus(ctx context.Context, arg UpdateBookingPaymentStatusParams) (DatCho, error) {
	row := q.db.QueryRow(ctx, updateBookingPaymentStatus, arg.ID, arg.PhuongThucThanhToan)
	var i DatCho
	err := row.Scan(
		&i.ID,
		&i.NguoiDungID,
		&i.KhoiHanhID,
		&i.SoNguoiLon,
		&i.SoTreEm,
		&i.TongTien,
		&i.DonViTienTe,
		&i.TrangThai,
		&i.PhuongThucThanhToan,
		&i.NgayDat,
		&i.NgayCapNhat,
	)
	return i, err
}

const updatePassenger = `-- name: UpdatePassenger :one
UPDATE hanh_khach
SET 
    ho_ten = COALESCE($2, ho_ten),
    ngay_sinh = COALESCE($3, ngay_sinh),
    loai_khach = COALESCE($4, loai_khach),
    gioi_tinh = COALESCE($5, gioi_tinh),
    so_giay_to_tuy_thanh = COALESCE($6, so_giay_to_tuy_thanh),
    quoc_tich = COALESCE($7, quoc_tich),
    ghi_chu = COALESCE($8, ghi_chu)
WHERE id = $1
RETURNING id, dat_cho_id, ho_ten, ngay_sinh, loai_khach, gioi_tinh, so_giay_to_tuy_thanh, quoc_tich, ghi_chu
`

type UpdatePassengerParams struct {
	ID               int32       `json:"id"`
	HoTen            *string     `json:"ho_ten"`
	NgaySinh         pgtype.Date `json:"ngay_sinh"`
	LoaiKhach        *string     `json:"loai_khach"`
	GioiTinh         *string     `json:"gioi_tinh"`
	SoGiayToTuyThanh *string     `json:"so_giay_to_tuy_thanh"`
	QuocTich         *string     `json:"quoc_tich"`
	GhiChu           *string     `json:"ghi_chu"`
}

// Cập nhật thông tin hành khách
func (q *Queries) UpdatePassenger(ctx context.Context, arg UpdatePassengerParams) (HanhKhach, error) {
	row := q.db.QueryRow(ctx, updatePassenger,
		arg.ID,
		arg.HoTen,
		arg.NgaySinh,
		arg.LoaiKhach,
		arg.GioiTinh,
		arg.SoGiayToTuyThanh,
		arg.QuocTich,
		arg.GhiChu,
	)
	var i HanhKhach
	err := row.Scan(
		&i.ID,
		&i.DatChoID,
		&i.HoTen,
		&i.NgaySinh,
		&i.LoaiKhach,
		&i.GioiTinh,
		&i.SoGiayToTuyThanh,
		&i.QuocTich,
		&i.GhiChu,
	)
	return i, err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE lich_su_giao_dich
SET 
    trang_thai = $2,
    ma_tham_chieu_cong_thanh_toan = $3,
    ngay_hoan_thanh = CASE WHEN $2 = 'thanh_cong' THEN CURRENT_TIMESTAMP ELSE NULL END
WHERE id = $1
RETURNING id, dat_cho_id, nguoi_dung_id, ma_giao_dich_noi_bo, ma_tham_chieu_cong_thanh_toan, cong_thanh_toan_id, so_tien, loai_giao_dich, trang_thai, noi_dung_chuyen_khoan, ngay_tao, ngay_hoan_thanh
`

type UpdateTransactionStatusParams struct {
	ID          int32                  `json:"id"`
	TrangThai   NullTrangThaiThanhToan `json:"trang_thai"`
	MaThamChieu *string                `json:"ma_tham_chieu"`
}

// Cập nhật trạng thái giao dịch (callback từ cổng thanh toán)
func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (LichSuGiaoDich, error) {
	row := q.db.QueryRow(ctx, updateTransactionStatus, arg.ID, arg.TrangThai, arg.MaThamChieu)
	var i LichSuGiaoDich
	err := row.Scan(
		&i.ID,
		&i.DatChoID,
		&i.NguoiDungID,
		&i.MaGiaoDichNoiBo,
		&i.MaThamChieuCongThanhToan,
		&i.CongThanhToanID,
		&i.SoTien,
		&i.LoaiGiaoDich,
		&i.TrangThai,
		&i.NoiDungChuyenKhoan,
		&i.NgayTao,
		&i.NgayHoanThanh,
	)
	return i, err
}
