// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chat.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChatHistory = `-- name: CreateChatHistory :one
INSERT INTO lich_su_chat (
    nguoi_dung_id,
    ma_phien,
    cau_hoi,
    cau_tra_loi
) VALUES (
    $1, $2, $3, $4
) RETURNING id, nguoi_dung_id, ma_phien, cau_hoi, cau_tra_loi, ngay_tao
`

type CreateChatHistoryParams struct {
	NguoiDungID pgtype.UUID `json:"nguoi_dung_id"`
	MaPhien     string      `json:"ma_phien"`
	CauHoi      string      `json:"cau_hoi"`
	CauTraLoi   string      `json:"cau_tra_loi"`
}

func (q *Queries) CreateChatHistory(ctx context.Context, arg CreateChatHistoryParams) (LichSuChat, error) {
	row := q.db.QueryRow(ctx, createChatHistory,
		arg.NguoiDungID,
		arg.MaPhien,
		arg.CauHoi,
		arg.CauTraLoi,
	)
	var i LichSuChat
	err := row.Scan(
		&i.ID,
		&i.NguoiDungID,
		&i.MaPhien,
		&i.CauHoi,
		&i.CauTraLoi,
		&i.NgayTao,
	)
	return i, err
}

const deleteChatHistoryBySessionID = `-- name: DeleteChatHistoryBySessionID :exec
DELETE FROM lich_su_chat
WHERE ma_phien = $1
`

func (q *Queries) DeleteChatHistoryBySessionID(ctx context.Context, maPhien string) error {
	_, err := q.db.Exec(ctx, deleteChatHistoryBySessionID, maPhien)
	return err
}

const deleteChatHistoryByUserID = `-- name: DeleteChatHistoryByUserID :exec
DELETE FROM lich_su_chat
WHERE nguoi_dung_id = $1
`

func (q *Queries) DeleteChatHistoryByUserID(ctx context.Context, nguoiDungID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChatHistoryByUserID, nguoiDungID)
	return err
}

const getChatHistoryBySessionID = `-- name: GetChatHistoryBySessionID :many
SELECT id, nguoi_dung_id, ma_phien, cau_hoi, cau_tra_loi, ngay_tao FROM lich_su_chat
WHERE ma_phien = $1
ORDER BY ngay_tao DESC
LIMIT $2 OFFSET $3
`

type GetChatHistoryBySessionIDParams struct {
	MaPhien string `json:"ma_phien"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) GetChatHistoryBySessionID(ctx context.Context, arg GetChatHistoryBySessionIDParams) ([]LichSuChat, error) {
	rows, err := q.db.Query(ctx, getChatHistoryBySessionID, arg.MaPhien, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LichSuChat
	for rows.Next() {
		var i LichSuChat
		if err := rows.Scan(
			&i.ID,
			&i.NguoiDungID,
			&i.MaPhien,
			&i.CauHoi,
			&i.CauTraLoi,
			&i.NgayTao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatHistoryByUserID = `-- name: GetChatHistoryByUserID :many
SELECT id, nguoi_dung_id, ma_phien, cau_hoi, cau_tra_loi, ngay_tao FROM lich_su_chat
WHERE nguoi_dung_id = $1
ORDER BY ngay_tao DESC
LIMIT $2 OFFSET $3
`

type GetChatHistoryByUserIDParams struct {
	NguoiDungID pgtype.UUID `json:"nguoi_dung_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) GetChatHistoryByUserID(ctx context.Context, arg GetChatHistoryByUserIDParams) ([]LichSuChat, error) {
	rows, err := q.db.Query(ctx, getChatHistoryByUserID, arg.NguoiDungID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LichSuChat
	for rows.Next() {
		var i LichSuChat
		if err := rows.Scan(
			&i.ID,
			&i.NguoiDungID,
			&i.MaPhien,
			&i.CauHoi,
			&i.CauTraLoi,
			&i.NgayTao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentChatHistory = `-- name: GetRecentChatHistory :many
SELECT id, nguoi_dung_id, ma_phien, cau_hoi, cau_tra_loi, ngay_tao FROM lich_su_chat
WHERE (($1::uuid IS NOT NULL AND nguoi_dung_id = $1) OR ($1::uuid IS NULL AND ma_phien = $2))
ORDER BY ngay_tao DESC
LIMIT $3
`

type GetRecentChatHistoryParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	MaPhien string      `json:"ma_phien"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) GetRecentChatHistory(ctx context.Context, arg GetRecentChatHistoryParams) ([]LichSuChat, error) {
	rows, err := q.db.Query(ctx, getRecentChatHistory, arg.Column1, arg.MaPhien, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LichSuChat
	for rows.Next() {
		var i LichSuChat
		if err := rows.Scan(
			&i.ID,
			&i.NguoiDungID,
			&i.MaPhien,
			&i.CauHoi,
			&i.CauTraLoi,
			&i.NgayTao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
