// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForAddPassengers implements pgx.CopyFromSource.
type iteratorForAddPassengers struct {
	rows                 []AddPassengersParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddPassengers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddPassengers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].DatChoID,
		r.rows[0].HoTen,
		r.rows[0].NgaySinh,
		r.rows[0].LoaiKhach,
		r.rows[0].GioiTinh,
		r.rows[0].SoGiayToTuyThanh,
		r.rows[0].QuocTich,
		r.rows[0].GhiChu,
	}, nil
}

func (r iteratorForAddPassengers) Err() error {
	return nil
}

// Thêm nhiều hành khách cùng lúc
func (q *Queries) AddPassengers(ctx context.Context, arg []AddPassengersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"hanh_khach"}, []string{"dat_cho_id", "ho_ten", "ngay_sinh", "loai_khach", "gioi_tinh", "so_giay_to_tuy_thanh", "quoc_tich", "ghi_chu"}, &iteratorForAddPassengers{rows: arg})
}
