// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: departure.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelDeparture = `-- name: CancelDeparture :one
UPDATE khoi_hanh_tour
SET 
    trang_thai = 'huy',
    ngay_cap_nhat = NOW()
WHERE id = $1
RETURNING id, tour_id, ngay_khoi_hanh, ngay_ket_thuc, suc_chua, so_cho_da_dat, trang_thai, ghi_chu, ngay_tao, ngay_cap_nhat
`

func (q *Queries) CancelDeparture(ctx context.Context, id int32) (KhoiHanhTour, error) {
	row := q.db.QueryRow(ctx, cancelDeparture, id)
	var i KhoiHanhTour
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.NgayKhoiHanh,
		&i.NgayKetThuc,
		&i.SucChua,
		&i.SoChoDaDat,
		&i.TrangThai,
		&i.GhiChu,
		&i.NgayTao,
		&i.NgayCapNhat,
	)
	return i, err
}

const countAllDepartures = `-- name: CountAllDepartures :one
SELECT COUNT(*) FROM khoi_hanh_tour
`

func (q *Queries) CountAllDepartures(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllDepartures)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDeparturesByTour = `-- name: CountDeparturesByTour :one
SELECT COUNT(*) FROM khoi_hanh_tour
WHERE tour_id = $1
`

func (q *Queries) CountDeparturesByTour(ctx context.Context, tourID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countDeparturesByTour, tourID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeparture = `-- name: CreateDeparture :one

INSERT INTO khoi_hanh_tour (
    tour_id,
    ngay_khoi_hanh,
    ngay_ket_thuc,
    suc_chua,
    trang_thai,
    ghi_chu
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, tour_id, ngay_khoi_hanh, ngay_ket_thuc, suc_chua, so_cho_da_dat, trang_thai, ghi_chu, ngay_tao, ngay_cap_nhat
`

type CreateDepartureParams struct {
	TourID       int32                 `json:"tour_id"`
	NgayKhoiHanh pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc  pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua      int32                 `json:"suc_chua"`
	TrangThai    NullTrangThaiKhoiHanh `json:"trang_thai"`
	GhiChu       *string               `json:"ghi_chu"`
}

// ==================== DEPARTURE MANAGEMENT ====================
// tạo lịch khởi hành
func (q *Queries) CreateDeparture(ctx context.Context, arg CreateDepartureParams) (KhoiHanhTour, error) {
	row := q.db.QueryRow(ctx, createDeparture,
		arg.TourID,
		arg.NgayKhoiHanh,
		arg.NgayKetThuc,
		arg.SucChua,
		arg.TrangThai,
		arg.GhiChu,
	)
	var i KhoiHanhTour
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.NgayKhoiHanh,
		&i.NgayKetThuc,
		&i.SucChua,
		&i.SoChoDaDat,
		&i.TrangThai,
		&i.GhiChu,
		&i.NgayTao,
		&i.NgayCapNhat,
	)
	return i, err
}

const deleteDeparture = `-- name: DeleteDeparture :exec
DELETE FROM khoi_hanh_tour
WHERE id = $1
`

func (q *Queries) DeleteDeparture(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteDeparture, id)
	return err
}

const getAllDepartures = `-- name: GetAllDepartures :many
SELECT 
    kh.id, kh.tour_id, kh.ngay_khoi_hanh, kh.ngay_ket_thuc, kh.suc_chua, kh.so_cho_da_dat, kh.trang_thai, kh.ghi_chu, kh.ngay_tao, kh.ngay_cap_nhat,
    t.tieu_de as ten_tour,
    COALESCE(SUM(dc.so_nguoi_lon + dc.so_tre_em), 0) as so_cho_da_dat
FROM khoi_hanh_tour kh
JOIN tour t ON kh.tour_id = t.id
LEFT JOIN dat_cho dc ON kh.id = dc.khoi_hanh_id 
    AND dc.trang_thai NOT IN ('da_huy')
GROUP BY kh.id, t.tieu_de
ORDER BY kh.ngay_khoi_hanh DESC
LIMIT $1 OFFSET $2
`

type GetAllDeparturesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAllDeparturesRow struct {
	ID           int32                 `json:"id"`
	TourID       int32                 `json:"tour_id"`
	NgayKhoiHanh pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc  pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua      int32                 `json:"suc_chua"`
	SoChoDaDat   *int32                `json:"so_cho_da_dat"`
	TrangThai    NullTrangThaiKhoiHanh `json:"trang_thai"`
	GhiChu       *string               `json:"ghi_chu"`
	NgayTao      pgtype.Timestamp      `json:"ngay_tao"`
	NgayCapNhat  pgtype.Timestamp      `json:"ngay_cap_nhat"`
	TenTour      string                `json:"ten_tour"`
	SoChoDaDat_2 interface{}           `json:"so_cho_da_dat_2"`
}

func (q *Queries) GetAllDepartures(ctx context.Context, arg GetAllDeparturesParams) ([]GetAllDeparturesRow, error) {
	rows, err := q.db.Query(ctx, getAllDepartures, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllDeparturesRow
	for rows.Next() {
		var i GetAllDeparturesRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.NgayKhoiHanh,
			&i.NgayKetThuc,
			&i.SucChua,
			&i.SoChoDaDat,
			&i.TrangThai,
			&i.GhiChu,
			&i.NgayTao,
			&i.NgayCapNhat,
			&i.TenTour,
			&i.SoChoDaDat_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDepartureByID = `-- name: GetDepartureByID :one
SELECT 
    kh.id, kh.tour_id, kh.ngay_khoi_hanh, kh.ngay_ket_thuc, kh.suc_chua, kh.so_cho_da_dat, kh.trang_thai, kh.ghi_chu, kh.ngay_tao, kh.ngay_cap_nhat,
    t.tieu_de as ten_tour,
    t.gia_nguoi_lon as gia_nguoi_lon,
    t.gia_tre_em as gia_tre_em,
    t.don_vi_tien_te,
    COALESCE(SUM(dc.so_nguoi_lon + dc.so_tre_em), 0) as so_cho_da_dat,
    kh.suc_chua - COALESCE(SUM(dc.so_nguoi_lon + dc.so_tre_em), 0) as so_cho_con_trong
FROM khoi_hanh_tour kh
JOIN tour t ON kh.tour_id = t.id
LEFT JOIN dat_cho dc ON kh.id = dc.khoi_hanh_id 
    AND dc.trang_thai NOT IN ('da_huy')
WHERE kh.id = $1
GROUP BY kh.id, t.tieu_de, t.gia_nguoi_lon, t.gia_tre_em, t.don_vi_tien_te
`

type GetDepartureByIDRow struct {
	ID            int32                 `json:"id"`
	TourID        int32                 `json:"tour_id"`
	NgayKhoiHanh  pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc   pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua       int32                 `json:"suc_chua"`
	SoChoDaDat    *int32                `json:"so_cho_da_dat"`
	TrangThai     NullTrangThaiKhoiHanh `json:"trang_thai"`
	GhiChu        *string               `json:"ghi_chu"`
	NgayTao       pgtype.Timestamp      `json:"ngay_tao"`
	NgayCapNhat   pgtype.Timestamp      `json:"ngay_cap_nhat"`
	TenTour       string                `json:"ten_tour"`
	GiaNguoiLon   pgtype.Numeric        `json:"gia_nguoi_lon"`
	GiaTreEm      pgtype.Numeric        `json:"gia_tre_em"`
	DonViTienTe   *string               `json:"don_vi_tien_te"`
	SoChoDaDat_2  interface{}           `json:"so_cho_da_dat_2"`
	SoChoConTrong int32                 `json:"so_cho_con_trong"`
}

// lấy thông tin chi tiết của một lịch khởi hành
func (q *Queries) GetDepartureByID(ctx context.Context, id int32) (GetDepartureByIDRow, error) {
	row := q.db.QueryRow(ctx, getDepartureByID, id)
	var i GetDepartureByIDRow
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.NgayKhoiHanh,
		&i.NgayKetThuc,
		&i.SucChua,
		&i.SoChoDaDat,
		&i.TrangThai,
		&i.GhiChu,
		&i.NgayTao,
		&i.NgayCapNhat,
		&i.TenTour,
		&i.GiaNguoiLon,
		&i.GiaTreEm,
		&i.DonViTienTe,
		&i.SoChoDaDat_2,
		&i.SoChoConTrong,
	)
	return i, err
}

const getDeparturesByDateRange = `-- name: GetDeparturesByDateRange :many
SELECT 
    kh.id, kh.tour_id, kh.ngay_khoi_hanh, kh.ngay_ket_thuc, kh.suc_chua, kh.so_cho_da_dat, kh.trang_thai, kh.ghi_chu, kh.ngay_tao, kh.ngay_cap_nhat,
    t.tieu_de as ten_tour,
    COALESCE(SUM(dc.so_nguoi_lon + dc.so_tre_em), 0) as so_cho_da_dat
FROM khoi_hanh_tour kh
JOIN tour t ON kh.tour_id = t.id
LEFT JOIN dat_cho dc ON kh.id = dc.khoi_hanh_id 
    AND dc.trang_thai NOT IN ('da_huy')
WHERE kh.ngay_khoi_hanh >= $1 AND kh.ngay_khoi_hanh <= $2
GROUP BY kh.id, t.tieu_de
ORDER BY kh.ngay_khoi_hanh ASC
`

type GetDeparturesByDateRangeParams struct {
	NgayKhoiHanh   pgtype.Date `json:"ngay_khoi_hanh"`
	NgayKhoiHanh_2 pgtype.Date `json:"ngay_khoi_hanh_2"`
}

type GetDeparturesByDateRangeRow struct {
	ID           int32                 `json:"id"`
	TourID       int32                 `json:"tour_id"`
	NgayKhoiHanh pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc  pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua      int32                 `json:"suc_chua"`
	SoChoDaDat   *int32                `json:"so_cho_da_dat"`
	TrangThai    NullTrangThaiKhoiHanh `json:"trang_thai"`
	GhiChu       *string               `json:"ghi_chu"`
	NgayTao      pgtype.Timestamp      `json:"ngay_tao"`
	NgayCapNhat  pgtype.Timestamp      `json:"ngay_cap_nhat"`
	TenTour      string                `json:"ten_tour"`
	SoChoDaDat_2 interface{}           `json:"so_cho_da_dat_2"`
}

func (q *Queries) GetDeparturesByDateRange(ctx context.Context, arg GetDeparturesByDateRangeParams) ([]GetDeparturesByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, getDeparturesByDateRange, arg.NgayKhoiHanh, arg.NgayKhoiHanh_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeparturesByDateRangeRow
	for rows.Next() {
		var i GetDeparturesByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.NgayKhoiHanh,
			&i.NgayKetThuc,
			&i.SucChua,
			&i.SoChoDaDat,
			&i.TrangThai,
			&i.GhiChu,
			&i.NgayTao,
			&i.NgayCapNhat,
			&i.TenTour,
			&i.SoChoDaDat_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeparturesByStatus = `-- name: GetDeparturesByStatus :many
SELECT 
    kh.id, kh.tour_id, kh.ngay_khoi_hanh, kh.ngay_ket_thuc, kh.suc_chua, kh.so_cho_da_dat, kh.trang_thai, kh.ghi_chu, kh.ngay_tao, kh.ngay_cap_nhat,
    t.tieu_de as ten_tour,
    COALESCE(SUM(dc.so_nguoi_lon + dc.so_tre_em), 0) as so_cho_da_dat
FROM khoi_hanh_tour kh
JOIN tour t ON kh.tour_id = t.id
LEFT JOIN dat_cho dc ON kh.id = dc.khoi_hanh_id 
    AND dc.trang_thai NOT IN ('da_huy')
WHERE kh.trang_thai = $1
GROUP BY kh.id, t.tieu_de
ORDER BY kh.ngay_khoi_hanh ASC
LIMIT $2 OFFSET $3
`

type GetDeparturesByStatusParams struct {
	TrangThai NullTrangThaiKhoiHanh `json:"trang_thai"`
	Limit     int32                 `json:"limit"`
	Offset    int32                 `json:"offset"`
}

type GetDeparturesByStatusRow struct {
	ID           int32                 `json:"id"`
	TourID       int32                 `json:"tour_id"`
	NgayKhoiHanh pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc  pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua      int32                 `json:"suc_chua"`
	SoChoDaDat   *int32                `json:"so_cho_da_dat"`
	TrangThai    NullTrangThaiKhoiHanh `json:"trang_thai"`
	GhiChu       *string               `json:"ghi_chu"`
	NgayTao      pgtype.Timestamp      `json:"ngay_tao"`
	NgayCapNhat  pgtype.Timestamp      `json:"ngay_cap_nhat"`
	TenTour      string                `json:"ten_tour"`
	SoChoDaDat_2 interface{}           `json:"so_cho_da_dat_2"`
}

func (q *Queries) GetDeparturesByStatus(ctx context.Context, arg GetDeparturesByStatusParams) ([]GetDeparturesByStatusRow, error) {
	rows, err := q.db.Query(ctx, getDeparturesByStatus, arg.TrangThai, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeparturesByStatusRow
	for rows.Next() {
		var i GetDeparturesByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.NgayKhoiHanh,
			&i.NgayKetThuc,
			&i.SucChua,
			&i.SoChoDaDat,
			&i.TrangThai,
			&i.GhiChu,
			&i.NgayTao,
			&i.NgayCapNhat,
			&i.TenTour,
			&i.SoChoDaDat_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeparturesByTour = `-- name: GetDeparturesByTour :many
SELECT 
    kh.id, kh.tour_id, kh.ngay_khoi_hanh, kh.ngay_ket_thuc, kh.suc_chua, kh.so_cho_da_dat, kh.trang_thai, kh.ghi_chu, kh.ngay_tao, kh.ngay_cap_nhat,
    COALESCE(SUM(dc.so_nguoi_lon + dc.so_tre_em), 0) as so_cho_da_dat,
    kh.suc_chua - COALESCE(SUM(dc.so_nguoi_lon + dc.so_tre_em), 0) as so_cho_con_trong
FROM khoi_hanh_tour kh
LEFT JOIN dat_cho dc ON kh.id = dc.khoi_hanh_id 
    AND dc.trang_thai NOT IN ('da_huy')
WHERE kh.tour_id = $1
GROUP BY kh.id
ORDER BY kh.ngay_khoi_hanh ASC
`

type GetDeparturesByTourRow struct {
	ID            int32                 `json:"id"`
	TourID        int32                 `json:"tour_id"`
	NgayKhoiHanh  pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc   pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua       int32                 `json:"suc_chua"`
	SoChoDaDat    *int32                `json:"so_cho_da_dat"`
	TrangThai     NullTrangThaiKhoiHanh `json:"trang_thai"`
	GhiChu        *string               `json:"ghi_chu"`
	NgayTao       pgtype.Timestamp      `json:"ngay_tao"`
	NgayCapNhat   pgtype.Timestamp      `json:"ngay_cap_nhat"`
	SoChoDaDat_2  interface{}           `json:"so_cho_da_dat_2"`
	SoChoConTrong int32                 `json:"so_cho_con_trong"`
}

// lấy danh sách lịch khởi hành của một tour
func (q *Queries) GetDeparturesByTour(ctx context.Context, tourID int32) ([]GetDeparturesByTourRow, error) {
	rows, err := q.db.Query(ctx, getDeparturesByTour, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeparturesByTourRow
	for rows.Next() {
		var i GetDeparturesByTourRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.NgayKhoiHanh,
			&i.NgayKetThuc,
			&i.SucChua,
			&i.SoChoDaDat,
			&i.TrangThai,
			&i.GhiChu,
			&i.NgayTao,
			&i.NgayCapNhat,
			&i.SoChoDaDat_2,
			&i.SoChoConTrong,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingDeparturesList = `-- name: GetUpcomingDeparturesList :many
SELECT 
    kh.id, kh.tour_id, kh.ngay_khoi_hanh, kh.ngay_ket_thuc, kh.suc_chua, kh.so_cho_da_dat, kh.trang_thai, kh.ghi_chu, kh.ngay_tao, kh.ngay_cap_nhat,
    t.tieu_de as ten_tour,
    t.gia_nguoi_lon,
    t.gia_tre_em,
    COALESCE(SUM(dc.so_nguoi_lon + dc.so_tre_em), 0) as so_cho_da_dat
FROM khoi_hanh_tour kh
JOIN tour t ON kh.tour_id = t.id
LEFT JOIN dat_cho dc ON kh.id = dc.khoi_hanh_id 
    AND dc.trang_thai NOT IN ('da_huy')
WHERE kh.ngay_khoi_hanh BETWEEN CURRENT_DATE AND (CURRENT_DATE + INTERVAL '30 days')
    AND kh.trang_thai IN ('len_lich', 'xac_nhan', 'con_cho')
GROUP BY kh.id, t.tieu_de, t.gia_nguoi_lon, t.gia_tre_em
ORDER BY kh.ngay_khoi_hanh ASC
LIMIT $1
`

type GetUpcomingDeparturesListRow struct {
	ID           int32                 `json:"id"`
	TourID       int32                 `json:"tour_id"`
	NgayKhoiHanh pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc  pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua      int32                 `json:"suc_chua"`
	SoChoDaDat   *int32                `json:"so_cho_da_dat"`
	TrangThai    NullTrangThaiKhoiHanh `json:"trang_thai"`
	GhiChu       *string               `json:"ghi_chu"`
	NgayTao      pgtype.Timestamp      `json:"ngay_tao"`
	NgayCapNhat  pgtype.Timestamp      `json:"ngay_cap_nhat"`
	TenTour      string                `json:"ten_tour"`
	GiaNguoiLon  pgtype.Numeric        `json:"gia_nguoi_lon"`
	GiaTreEm     pgtype.Numeric        `json:"gia_tre_em"`
	SoChoDaDat_2 interface{}           `json:"so_cho_da_dat_2"`
}

func (q *Queries) GetUpcomingDeparturesList(ctx context.Context, limit int32) ([]GetUpcomingDeparturesListRow, error) {
	rows, err := q.db.Query(ctx, getUpcomingDeparturesList, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpcomingDeparturesListRow
	for rows.Next() {
		var i GetUpcomingDeparturesListRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.NgayKhoiHanh,
			&i.NgayKetThuc,
			&i.SucChua,
			&i.SoChoDaDat,
			&i.TrangThai,
			&i.GhiChu,
			&i.NgayTao,
			&i.NgayCapNhat,
			&i.TenTour,
			&i.GiaNguoiLon,
			&i.GiaTreEm,
			&i.SoChoDaDat_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeparture = `-- name: UpdateDeparture :one
UPDATE khoi_hanh_tour
SET 
    ngay_khoi_hanh = COALESCE($2, ngay_khoi_hanh),
    ngay_ket_thuc = COALESCE($3, ngay_ket_thuc),
    suc_chua = COALESCE($4, suc_chua),
    trang_thai = COALESCE($5, trang_thai),
    ghi_chu = COALESCE($6, ghi_chu),
    ngay_cap_nhat = NOW()
WHERE id = $1
RETURNING id, tour_id, ngay_khoi_hanh, ngay_ket_thuc, suc_chua, so_cho_da_dat, trang_thai, ghi_chu, ngay_tao, ngay_cap_nhat
`

type UpdateDepartureParams struct {
	ID           int32                 `json:"id"`
	NgayKhoiHanh pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc  pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua      *int32                `json:"suc_chua"`
	TrangThai    NullTrangThaiKhoiHanh `json:"trang_thai"`
	GhiChu       *string               `json:"ghi_chu"`
}

func (q *Queries) UpdateDeparture(ctx context.Context, arg UpdateDepartureParams) (KhoiHanhTour, error) {
	row := q.db.QueryRow(ctx, updateDeparture,
		arg.ID,
		arg.NgayKhoiHanh,
		arg.NgayKetThuc,
		arg.SucChua,
		arg.TrangThai,
		arg.GhiChu,
	)
	var i KhoiHanhTour
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.NgayKhoiHanh,
		&i.NgayKetThuc,
		&i.SucChua,
		&i.SoChoDaDat,
		&i.TrangThai,
		&i.GhiChu,
		&i.NgayTao,
		&i.NgayCapNhat,
	)
	return i, err
}

const updateDepartureCapacity = `-- name: UpdateDepartureCapacity :one
UPDATE khoi_hanh_tour
SET 
    suc_chua = $2,
    ngay_cap_nhat = NOW()
WHERE id = $1
RETURNING id, tour_id, ngay_khoi_hanh, ngay_ket_thuc, suc_chua, so_cho_da_dat, trang_thai, ghi_chu, ngay_tao, ngay_cap_nhat
`

type UpdateDepartureCapacityParams struct {
	ID      int32 `json:"id"`
	SucChua int32 `json:"suc_chua"`
}

func (q *Queries) UpdateDepartureCapacity(ctx context.Context, arg UpdateDepartureCapacityParams) (KhoiHanhTour, error) {
	row := q.db.QueryRow(ctx, updateDepartureCapacity, arg.ID, arg.SucChua)
	var i KhoiHanhTour
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.NgayKhoiHanh,
		&i.NgayKetThuc,
		&i.SucChua,
		&i.SoChoDaDat,
		&i.TrangThai,
		&i.GhiChu,
		&i.NgayTao,
		&i.NgayCapNhat,
	)
	return i, err
}

const updateDepartureStat = `-- name: UpdateDepartureStat :one
UPDATE khoi_hanh_tour
SET 
    ngay_cap_nhat = NOW()
WHERE id = $1
RETURNING id, tour_id, ngay_khoi_hanh, ngay_ket_thuc, suc_chua, so_cho_da_dat, trang_thai, ghi_chu, ngay_tao, ngay_cap_nhat
`

func (q *Queries) UpdateDepartureStat(ctx context.Context, id int32) (KhoiHanhTour, error) {
	row := q.db.QueryRow(ctx, updateDepartureStat, id)
	var i KhoiHanhTour
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.NgayKhoiHanh,
		&i.NgayKetThuc,
		&i.SucChua,
		&i.SoChoDaDat,
		&i.TrangThai,
		&i.GhiChu,
		&i.NgayTao,
		&i.NgayCapNhat,
	)
	return i, err
}
