// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: departure.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addHinhAnhTour = `-- name: AddHinhAnhTour :one
INSERT INTO anh_tour (tour_id, duong_dan, mo_ta, la_anh_chinh, thu_tu_hien_thi) VALUES ($1, $2, $3, $4, $5) RETURNING id, tour_id, duong_dan, mo_ta, la_anh_chinh, thu_tu_hien_thi, ngay_tao
`

type AddHinhAnhTourParams struct {
	TourID       int32   `json:"tour_id"`
	DuongDan     string  `json:"duong_dan"`
	MoTa         *string `json:"mo_ta"`
	LaAnhChinh   *bool   `json:"la_anh_chinh"`
	ThuTuHienThi *int32  `json:"thu_tu_hien_thi"`
}

func (q *Queries) AddHinhAnhTour(ctx context.Context, arg AddHinhAnhTourParams) (AnhTour, error) {
	row := q.db.QueryRow(ctx, addHinhAnhTour,
		arg.TourID,
		arg.DuongDan,
		arg.MoTa,
		arg.LaAnhChinh,
		arg.ThuTuHienThi,
	)
	var i AnhTour
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.DuongDan,
		&i.MoTa,
		&i.LaAnhChinh,
		&i.ThuTuHienThi,
		&i.NgayTao,
	)
	return i, err
}

const addTourDestination = `-- name: AddTourDestination :exec
INSERT INTO tour_diem_den (
    tour_id,
    diem_den_id,
    thu_tu_tham_quan
) VALUES (
    $1, $2, $3
)
`

type AddTourDestinationParams struct {
	TourID        int32  `json:"tour_id"`
	DiemDenID     int32  `json:"diem_den_id"`
	ThuTuThamQuan *int32 `json:"thu_tu_tham_quan"`
}

func (q *Queries) AddTourDestination(ctx context.Context, arg AddTourDestinationParams) error {
	_, err := q.db.Exec(ctx, addTourDestination, arg.TourID, arg.DiemDenID, arg.ThuTuThamQuan)
	return err
}

const cancelDeparture = `-- name: CancelDeparture :one
UPDATE khoi_hanh_tour
SET 
    trang_thai = 'huy',
    ngay_cap_nhat = NOW()
WHERE id = $1
RETURNING id, tour_id, ngay_khoi_hanh, ngay_ket_thuc, suc_chua, so_cho_da_dat, trang_thai, ghi_chu, ngay_tao, ngay_cap_nhat
`

func (q *Queries) CancelDeparture(ctx context.Context, id int32) (KhoiHanhTour, error) {
	row := q.db.QueryRow(ctx, cancelDeparture, id)
	var i KhoiHanhTour
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.NgayKhoiHanh,
		&i.NgayKetThuc,
		&i.SucChua,
		&i.SoChoDaDat,
		&i.TrangThai,
		&i.GhiChu,
		&i.NgayTao,
		&i.NgayCapNhat,
	)
	return i, err
}

const createDeparture = `-- name: CreateDeparture :one
INSERT INTO khoi_hanh_tour (
    tour_id,
    ngay_khoi_hanh,
    ngay_ket_thuc,
    suc_chua,
    trang_thai,
    ghi_chu
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, tour_id, ngay_khoi_hanh, ngay_ket_thuc, suc_chua, so_cho_da_dat, trang_thai, ghi_chu, ngay_tao, ngay_cap_nhat
`

type CreateDepartureParams struct {
	TourID       int32                 `json:"tour_id"`
	NgayKhoiHanh pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc  pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua      int32                 `json:"suc_chua"`
	TrangThai    NullTrangThaiKhoiHanh `json:"trang_thai"`
	GhiChu       *string               `json:"ghi_chu"`
}

// ==================== DEPARTURE MANAGEMENT ====================
// tạo lịch khởi hành
func (q *Queries) CreateDeparture(ctx context.Context, arg CreateDepartureParams) (KhoiHanhTour, error) {
	row := q.db.QueryRow(ctx, createDeparture,
		arg.TourID,
		arg.NgayKhoiHanh,
		arg.NgayKetThuc,
		arg.SucChua,
		arg.TrangThai,
		arg.GhiChu,
	)
	var i KhoiHanhTour
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.NgayKhoiHanh,
		&i.NgayKetThuc,
		&i.SucChua,
		&i.SoChoDaDat,
		&i.TrangThai,
		&i.GhiChu,
		&i.NgayTao,
		&i.NgayCapNhat,
	)
	return i, err
}

const deleteDeparture = `-- name: DeleteDeparture :exec
DELETE FROM khoi_hanh_tour
WHERE id = $1
`

func (q *Queries) DeleteDeparture(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteDeparture, id)
	return err
}

const deleteHinhAnhTour = `-- name: DeleteHinhAnhTour :exec
DELETE FROM anh_tour
WHERE id = $1 AND tour_id = $2
`

type DeleteHinhAnhTourParams struct {
	ID     int32 `json:"id"`
	TourID int32 `json:"tour_id"`
}

func (q *Queries) DeleteHinhAnhTour(ctx context.Context, arg DeleteHinhAnhTourParams) error {
	_, err := q.db.Exec(ctx, deleteHinhAnhTour, arg.ID, arg.TourID)
	return err
}

const deleteTourDestination = `-- name: DeleteTourDestination :exec
DELETE FROM tour_diem_den WHERE tour_id = $1 AND diem_den_id = $2
`

type DeleteTourDestinationParams struct {
	TourID    int32 `json:"tour_id"`
	DiemDenID int32 `json:"diem_den_id"`
}

func (q *Queries) DeleteTourDestination(ctx context.Context, arg DeleteTourDestinationParams) error {
	_, err := q.db.Exec(ctx, deleteTourDestination, arg.TourID, arg.DiemDenID)
	return err
}

const getAllDepartures = `-- name: GetAllDepartures :many
SELECT 
    kh.id, kh.tour_id, kh.ngay_khoi_hanh, kh.ngay_ket_thuc, kh.suc_chua, kh.so_cho_da_dat, kh.trang_thai, kh.ghi_chu, kh.ngay_tao, kh.ngay_cap_nhat,
    t.tieu_de as ten_tour,
    COALESCE(SUM(dc.so_nguoi_lon + dc.so_tre_em), 0) as so_cho_da_dat
FROM khoi_hanh_tour kh
JOIN tour t ON kh.tour_id = t.id
LEFT JOIN dat_cho dc ON kh.id = dc.khoi_hanh_id 
    AND dc.trang_thai NOT IN ('da_huy')
GROUP BY kh.id, t.tieu_de
ORDER BY kh.ngay_khoi_hanh DESC
LIMIT $1 OFFSET $2
`

type GetAllDeparturesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAllDeparturesRow struct {
	ID           int32                 `json:"id"`
	TourID       int32                 `json:"tour_id"`
	NgayKhoiHanh pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc  pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua      int32                 `json:"suc_chua"`
	SoChoDaDat   *int32                `json:"so_cho_da_dat"`
	TrangThai    NullTrangThaiKhoiHanh `json:"trang_thai"`
	GhiChu       *string               `json:"ghi_chu"`
	NgayTao      pgtype.Timestamp      `json:"ngay_tao"`
	NgayCapNhat  pgtype.Timestamp      `json:"ngay_cap_nhat"`
	TenTour      string                `json:"ten_tour"`
	SoChoDaDat_2 interface{}           `json:"so_cho_da_dat_2"`
}

func (q *Queries) GetAllDepartures(ctx context.Context, arg GetAllDeparturesParams) ([]GetAllDeparturesRow, error) {
	rows, err := q.db.Query(ctx, getAllDepartures, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllDeparturesRow
	for rows.Next() {
		var i GetAllDeparturesRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.NgayKhoiHanh,
			&i.NgayKetThuc,
			&i.SucChua,
			&i.SoChoDaDat,
			&i.TrangThai,
			&i.GhiChu,
			&i.NgayTao,
			&i.NgayCapNhat,
			&i.TenTour,
			&i.SoChoDaDat_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDepartureByID = `-- name: GetDepartureByID :one
SELECT 
    kh.id, kh.tour_id, kh.ngay_khoi_hanh, kh.ngay_ket_thuc, kh.suc_chua, kh.so_cho_da_dat, kh.trang_thai, kh.ghi_chu, kh.ngay_tao, kh.ngay_cap_nhat,
    t.tieu_de as ten_tour,
    t.gia_nguoi_lon as gia_nguoi_lon,
    t.gia_tre_em as gia_tre_em,
    t.don_vi_tien_te,
    COALESCE(SUM(dc.so_nguoi_lon + dc.so_tre_em), 0) as so_cho_da_dat,
    kh.suc_chua - COALESCE(SUM(dc.so_nguoi_lon + dc.so_tre_em), 0) as so_cho_con_trong
FROM khoi_hanh_tour kh
JOIN tour t ON kh.tour_id = t.id
LEFT JOIN dat_cho dc ON kh.id = dc.khoi_hanh_id 
    AND dc.trang_thai NOT IN ('da_huy')
WHERE kh.id = $1
GROUP BY kh.id, t.tieu_de, t.gia_nguoi_lon, t.gia_tre_em, t.don_vi_tien_te
`

type GetDepartureByIDRow struct {
	ID            int32                 `json:"id"`
	TourID        int32                 `json:"tour_id"`
	NgayKhoiHanh  pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc   pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua       int32                 `json:"suc_chua"`
	SoChoDaDat    *int32                `json:"so_cho_da_dat"`
	TrangThai     NullTrangThaiKhoiHanh `json:"trang_thai"`
	GhiChu        *string               `json:"ghi_chu"`
	NgayTao       pgtype.Timestamp      `json:"ngay_tao"`
	NgayCapNhat   pgtype.Timestamp      `json:"ngay_cap_nhat"`
	TenTour       string                `json:"ten_tour"`
	GiaNguoiLon   pgtype.Numeric        `json:"gia_nguoi_lon"`
	GiaTreEm      pgtype.Numeric        `json:"gia_tre_em"`
	DonViTienTe   *string               `json:"don_vi_tien_te"`
	SoChoDaDat_2  interface{}           `json:"so_cho_da_dat_2"`
	SoChoConTrong int32                 `json:"so_cho_con_trong"`
}

// lấy thông tin chi tiết của một lịch khởi hành
func (q *Queries) GetDepartureByID(ctx context.Context, id int32) (GetDepartureByIDRow, error) {
	row := q.db.QueryRow(ctx, getDepartureByID, id)
	var i GetDepartureByIDRow
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.NgayKhoiHanh,
		&i.NgayKetThuc,
		&i.SucChua,
		&i.SoChoDaDat,
		&i.TrangThai,
		&i.GhiChu,
		&i.NgayTao,
		&i.NgayCapNhat,
		&i.TenTour,
		&i.GiaNguoiLon,
		&i.GiaTreEm,
		&i.DonViTienTe,
		&i.SoChoDaDat_2,
		&i.SoChoConTrong,
	)
	return i, err
}

const getDeparturesByDateRange = `-- name: GetDeparturesByDateRange :many
SELECT 
    kh.id, kh.tour_id, kh.ngay_khoi_hanh, kh.ngay_ket_thuc, kh.suc_chua, kh.so_cho_da_dat, kh.trang_thai, kh.ghi_chu, kh.ngay_tao, kh.ngay_cap_nhat,
    t.tieu_de as ten_tour,
    COALESCE(SUM(dc.so_nguoi_lon + dc.so_tre_em), 0) as so_cho_da_dat
FROM khoi_hanh_tour kh
JOIN tour t ON kh.tour_id = t.id
LEFT JOIN dat_cho dc ON kh.id = dc.khoi_hanh_id 
    AND dc.trang_thai NOT IN ('da_huy')
WHERE kh.ngay_khoi_hanh >= $1 AND kh.ngay_khoi_hanh <= $2
GROUP BY kh.id, t.tieu_de
ORDER BY kh.ngay_khoi_hanh ASC
`

type GetDeparturesByDateRangeParams struct {
	NgayKhoiHanh   pgtype.Date `json:"ngay_khoi_hanh"`
	NgayKhoiHanh_2 pgtype.Date `json:"ngay_khoi_hanh_2"`
}

type GetDeparturesByDateRangeRow struct {
	ID           int32                 `json:"id"`
	TourID       int32                 `json:"tour_id"`
	NgayKhoiHanh pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc  pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua      int32                 `json:"suc_chua"`
	SoChoDaDat   *int32                `json:"so_cho_da_dat"`
	TrangThai    NullTrangThaiKhoiHanh `json:"trang_thai"`
	GhiChu       *string               `json:"ghi_chu"`
	NgayTao      pgtype.Timestamp      `json:"ngay_tao"`
	NgayCapNhat  pgtype.Timestamp      `json:"ngay_cap_nhat"`
	TenTour      string                `json:"ten_tour"`
	SoChoDaDat_2 interface{}           `json:"so_cho_da_dat_2"`
}

func (q *Queries) GetDeparturesByDateRange(ctx context.Context, arg GetDeparturesByDateRangeParams) ([]GetDeparturesByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, getDeparturesByDateRange, arg.NgayKhoiHanh, arg.NgayKhoiHanh_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeparturesByDateRangeRow
	for rows.Next() {
		var i GetDeparturesByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.NgayKhoiHanh,
			&i.NgayKetThuc,
			&i.SucChua,
			&i.SoChoDaDat,
			&i.TrangThai,
			&i.GhiChu,
			&i.NgayTao,
			&i.NgayCapNhat,
			&i.TenTour,
			&i.SoChoDaDat_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeparturesByStatus = `-- name: GetDeparturesByStatus :many
SELECT 
    kh.id, kh.tour_id, kh.ngay_khoi_hanh, kh.ngay_ket_thuc, kh.suc_chua, kh.so_cho_da_dat, kh.trang_thai, kh.ghi_chu, kh.ngay_tao, kh.ngay_cap_nhat,
    t.tieu_de as ten_tour,
    COALESCE(SUM(dc.so_nguoi_lon + dc.so_tre_em), 0) as so_cho_da_dat
FROM khoi_hanh_tour kh
JOIN tour t ON kh.tour_id = t.id
LEFT JOIN dat_cho dc ON kh.id = dc.khoi_hanh_id 
    AND dc.trang_thai NOT IN ('da_huy')
WHERE kh.trang_thai = $1
GROUP BY kh.id, t.tieu_de
ORDER BY kh.ngay_khoi_hanh ASC
LIMIT $2 OFFSET $3
`

type GetDeparturesByStatusParams struct {
	TrangThai NullTrangThaiKhoiHanh `json:"trang_thai"`
	Limit     int32                 `json:"limit"`
	Offset    int32                 `json:"offset"`
}

type GetDeparturesByStatusRow struct {
	ID           int32                 `json:"id"`
	TourID       int32                 `json:"tour_id"`
	NgayKhoiHanh pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc  pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua      int32                 `json:"suc_chua"`
	SoChoDaDat   *int32                `json:"so_cho_da_dat"`
	TrangThai    NullTrangThaiKhoiHanh `json:"trang_thai"`
	GhiChu       *string               `json:"ghi_chu"`
	NgayTao      pgtype.Timestamp      `json:"ngay_tao"`
	NgayCapNhat  pgtype.Timestamp      `json:"ngay_cap_nhat"`
	TenTour      string                `json:"ten_tour"`
	SoChoDaDat_2 interface{}           `json:"so_cho_da_dat_2"`
}

func (q *Queries) GetDeparturesByStatus(ctx context.Context, arg GetDeparturesByStatusParams) ([]GetDeparturesByStatusRow, error) {
	rows, err := q.db.Query(ctx, getDeparturesByStatus, arg.TrangThai, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeparturesByStatusRow
	for rows.Next() {
		var i GetDeparturesByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.NgayKhoiHanh,
			&i.NgayKetThuc,
			&i.SucChua,
			&i.SoChoDaDat,
			&i.TrangThai,
			&i.GhiChu,
			&i.NgayTao,
			&i.NgayCapNhat,
			&i.TenTour,
			&i.SoChoDaDat_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeparturesByTour = `-- name: GetDeparturesByTour :many
SELECT 
    kh.id, kh.tour_id, kh.ngay_khoi_hanh, kh.ngay_ket_thuc, kh.suc_chua, kh.so_cho_da_dat, kh.trang_thai, kh.ghi_chu, kh.ngay_tao, kh.ngay_cap_nhat,
    COALESCE(SUM(dc.so_nguoi_lon + dc.so_tre_em), 0) as so_cho_da_dat,
    kh.suc_chua - COALESCE(SUM(dc.so_nguoi_lon + dc.so_tre_em), 0) as so_cho_con_trong
FROM khoi_hanh_tour kh
LEFT JOIN dat_cho dc ON kh.id = dc.khoi_hanh_id 
    AND dc.trang_thai NOT IN ('da_huy')
WHERE kh.tour_id = $1
GROUP BY kh.id
ORDER BY kh.ngay_khoi_hanh ASC
`

type GetDeparturesByTourRow struct {
	ID            int32                 `json:"id"`
	TourID        int32                 `json:"tour_id"`
	NgayKhoiHanh  pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc   pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua       int32                 `json:"suc_chua"`
	SoChoDaDat    *int32                `json:"so_cho_da_dat"`
	TrangThai     NullTrangThaiKhoiHanh `json:"trang_thai"`
	GhiChu        *string               `json:"ghi_chu"`
	NgayTao       pgtype.Timestamp      `json:"ngay_tao"`
	NgayCapNhat   pgtype.Timestamp      `json:"ngay_cap_nhat"`
	SoChoDaDat_2  interface{}           `json:"so_cho_da_dat_2"`
	SoChoConTrong int32                 `json:"so_cho_con_trong"`
}

// lấy danh sách lịch khởi hành của một tour
func (q *Queries) GetDeparturesByTour(ctx context.Context, tourID int32) ([]GetDeparturesByTourRow, error) {
	rows, err := q.db.Query(ctx, getDeparturesByTour, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeparturesByTourRow
	for rows.Next() {
		var i GetDeparturesByTourRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.NgayKhoiHanh,
			&i.NgayKetThuc,
			&i.SucChua,
			&i.SoChoDaDat,
			&i.TrangThai,
			&i.GhiChu,
			&i.NgayTao,
			&i.NgayCapNhat,
			&i.SoChoDaDat_2,
			&i.SoChoConTrong,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHinhAnhTourByID = `-- name: GetHinhAnhTourByID :one
SELECT id, tour_id, duong_dan, mo_ta, la_anh_chinh, thu_tu_hien_thi, ngay_tao
FROM anh_tour
WHERE id = $1
`

func (q *Queries) GetHinhAnhTourByID(ctx context.Context, id int32) (AnhTour, error) {
	row := q.db.QueryRow(ctx, getHinhAnhTourByID, id)
	var i AnhTour
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.DuongDan,
		&i.MoTa,
		&i.LaAnhChinh,
		&i.ThuTuHienThi,
		&i.NgayTao,
	)
	return i, err
}

const getUpcomingDeparturesList = `-- name: GetUpcomingDeparturesList :many
SELECT 
    kh.id, kh.tour_id, kh.ngay_khoi_hanh, kh.ngay_ket_thuc, kh.suc_chua, kh.so_cho_da_dat, kh.trang_thai, kh.ghi_chu, kh.ngay_tao, kh.ngay_cap_nhat,
    t.tieu_de as ten_tour,
    t.gia_nguoi_lon,
    t.gia_tre_em,
    COALESCE(SUM(dc.so_nguoi_lon + dc.so_tre_em), 0) as so_cho_da_dat
FROM khoi_hanh_tour kh
JOIN tour t ON kh.tour_id = t.id
LEFT JOIN dat_cho dc ON kh.id = dc.khoi_hanh_id 
    AND dc.trang_thai NOT IN ('da_huy')
WHERE kh.ngay_khoi_hanh BETWEEN CURRENT_DATE AND (CURRENT_DATE + INTERVAL '30 days')
    AND kh.trang_thai IN ('len_lich', 'xac_nhan', 'con_cho')
GROUP BY kh.id, t.tieu_de, t.gia_nguoi_lon, t.gia_tre_em
ORDER BY kh.ngay_khoi_hanh ASC
LIMIT $1
`

type GetUpcomingDeparturesListRow struct {
	ID           int32                 `json:"id"`
	TourID       int32                 `json:"tour_id"`
	NgayKhoiHanh pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc  pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua      int32                 `json:"suc_chua"`
	SoChoDaDat   *int32                `json:"so_cho_da_dat"`
	TrangThai    NullTrangThaiKhoiHanh `json:"trang_thai"`
	GhiChu       *string               `json:"ghi_chu"`
	NgayTao      pgtype.Timestamp      `json:"ngay_tao"`
	NgayCapNhat  pgtype.Timestamp      `json:"ngay_cap_nhat"`
	TenTour      string                `json:"ten_tour"`
	GiaNguoiLon  pgtype.Numeric        `json:"gia_nguoi_lon"`
	GiaTreEm     pgtype.Numeric        `json:"gia_tre_em"`
	SoChoDaDat_2 interface{}           `json:"so_cho_da_dat_2"`
}

func (q *Queries) GetUpcomingDeparturesList(ctx context.Context, limit int32) ([]GetUpcomingDeparturesListRow, error) {
	rows, err := q.db.Query(ctx, getUpcomingDeparturesList, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpcomingDeparturesListRow
	for rows.Next() {
		var i GetUpcomingDeparturesListRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.NgayKhoiHanh,
			&i.NgayKetThuc,
			&i.SucChua,
			&i.SoChoDaDat,
			&i.TrangThai,
			&i.GhiChu,
			&i.NgayTao,
			&i.NgayCapNhat,
			&i.TenTour,
			&i.GiaNguoiLon,
			&i.GiaTreEm,
			&i.SoChoDaDat_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeparture = `-- name: UpdateDeparture :one
UPDATE khoi_hanh_tour
SET 
    ngay_khoi_hanh = COALESCE($2, ngay_khoi_hanh),
    ngay_ket_thuc = COALESCE($3, ngay_ket_thuc),
    suc_chua = COALESCE($4, suc_chua),
    trang_thai = COALESCE($5, trang_thai),
    ghi_chu = COALESCE($6, ghi_chu),
    ngay_cap_nhat = NOW()
WHERE id = $1
RETURNING id, tour_id, ngay_khoi_hanh, ngay_ket_thuc, suc_chua, so_cho_da_dat, trang_thai, ghi_chu, ngay_tao, ngay_cap_nhat
`

type UpdateDepartureParams struct {
	ID           int32                 `json:"id"`
	NgayKhoiHanh pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc  pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua      *int32                `json:"suc_chua"`
	TrangThai    NullTrangThaiKhoiHanh `json:"trang_thai"`
	GhiChu       *string               `json:"ghi_chu"`
}

func (q *Queries) UpdateDeparture(ctx context.Context, arg UpdateDepartureParams) (KhoiHanhTour, error) {
	row := q.db.QueryRow(ctx, updateDeparture,
		arg.ID,
		arg.NgayKhoiHanh,
		arg.NgayKetThuc,
		arg.SucChua,
		arg.TrangThai,
		arg.GhiChu,
	)
	var i KhoiHanhTour
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.NgayKhoiHanh,
		&i.NgayKetThuc,
		&i.SucChua,
		&i.SoChoDaDat,
		&i.TrangThai,
		&i.GhiChu,
		&i.NgayTao,
		&i.NgayCapNhat,
	)
	return i, err
}

const updateDepartureCapacity = `-- name: UpdateDepartureCapacity :one
UPDATE khoi_hanh_tour
SET 
    suc_chua = $2,
    ngay_cap_nhat = NOW()
WHERE id = $1
RETURNING id, tour_id, ngay_khoi_hanh, ngay_ket_thuc, suc_chua, so_cho_da_dat, trang_thai, ghi_chu, ngay_tao, ngay_cap_nhat
`

type UpdateDepartureCapacityParams struct {
	ID      int32 `json:"id"`
	SucChua int32 `json:"suc_chua"`
}

func (q *Queries) UpdateDepartureCapacity(ctx context.Context, arg UpdateDepartureCapacityParams) (KhoiHanhTour, error) {
	row := q.db.QueryRow(ctx, updateDepartureCapacity, arg.ID, arg.SucChua)
	var i KhoiHanhTour
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.NgayKhoiHanh,
		&i.NgayKetThuc,
		&i.SucChua,
		&i.SoChoDaDat,
		&i.TrangThai,
		&i.GhiChu,
		&i.NgayTao,
		&i.NgayCapNhat,
	)
	return i, err
}

const updateDepartureStat = `-- name: UpdateDepartureStat :one
UPDATE khoi_hanh_tour
SET 
    ngay_cap_nhat = NOW()
WHERE id = $1
RETURNING id, tour_id, ngay_khoi_hanh, ngay_ket_thuc, suc_chua, so_cho_da_dat, trang_thai, ghi_chu, ngay_tao, ngay_cap_nhat
`

func (q *Queries) UpdateDepartureStat(ctx context.Context, id int32) (KhoiHanhTour, error) {
	row := q.db.QueryRow(ctx, updateDepartureStat, id)
	var i KhoiHanhTour
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.NgayKhoiHanh,
		&i.NgayKetThuc,
		&i.SucChua,
		&i.SoChoDaDat,
		&i.TrangThai,
		&i.GhiChu,
		&i.NgayTao,
		&i.NgayCapNhat,
	)
	return i, err
}

const updateHoatDongTrongNgay = `-- name: UpdateHoatDongTrongNgay :one
UPDATE hoat_dong_trong_ngay
SET
    ten = COALESCE($2, ten),
    gio_bat_dau = COALESCE($3, gio_bat_dau),
    gio_ket_thuc = COALESCE($4, gio_ket_thuc),
    mo_ta = COALESCE($5, mo_ta),
    thu_tu = COALESCE($6, thu_tu)
WHERE id = $1
RETURNING id, lich_trinh_id, ten, gio_bat_dau, gio_ket_thuc, mo_ta, thu_tu, ngay_tao
`

type UpdateHoatDongTrongNgayParams struct {
	ID         int32       `json:"id"`
	Ten        *string     `json:"ten"`
	GioBatDau  pgtype.Time `json:"gio_bat_dau"`
	GioKetThuc pgtype.Time `json:"gio_ket_thuc"`
	MoTa       *string     `json:"mo_ta"`
	ThuTu      *int32      `json:"thu_tu"`
}

func (q *Queries) UpdateHoatDongTrongNgay(ctx context.Context, arg UpdateHoatDongTrongNgayParams) (HoatDongTrongNgay, error) {
	row := q.db.QueryRow(ctx, updateHoatDongTrongNgay,
		arg.ID,
		arg.Ten,
		arg.GioBatDau,
		arg.GioKetThuc,
		arg.MoTa,
		arg.ThuTu,
	)
	var i HoatDongTrongNgay
	err := row.Scan(
		&i.ID,
		&i.LichTrinhID,
		&i.Ten,
		&i.GioBatDau,
		&i.GioKetThuc,
		&i.MoTa,
		&i.ThuTu,
		&i.NgayTao,
	)
	return i, err
}

const updateKhoiHanhTour = `-- name: UpdateKhoiHanhTour :one
UPDATE khoi_hanh_tour
SET
    ngay_khoi_hanh = COALESCE($3, ngay_khoi_hanh),
    ngay_ket_thuc = COALESCE($4, ngay_ket_thuc),
    suc_chua = COALESCE($5, suc_chua),
    trang_thai = COALESCE($6, trang_thai),
    ghi_chu = COALESCE($7, ghi_chu),
    so_cho_da_dat = COALESCE($8, so_cho_da_dat),
    ngay_cap_nhat = NOW()
WHERE id = $1 AND tour_id = $2
RETURNING id, tour_id, ngay_khoi_hanh, ngay_ket_thuc, suc_chua, so_cho_da_dat, trang_thai, ghi_chu, ngay_tao, ngay_cap_nhat
`

type UpdateKhoiHanhTourParams struct {
	ID           int32                 `json:"id"`
	TourID       int32                 `json:"tour_id"`
	NgayKhoiHanh pgtype.Date           `json:"ngay_khoi_hanh"`
	NgayKetThuc  pgtype.Date           `json:"ngay_ket_thuc"`
	SucChua      *int32                `json:"suc_chua"`
	TrangThai    NullTrangThaiKhoiHanh `json:"trang_thai"`
	GhiChu       *string               `json:"ghi_chu"`
	SoChoDaDat   *int32                `json:"so_cho_da_dat"`
}

func (q *Queries) UpdateKhoiHanhTour(ctx context.Context, arg UpdateKhoiHanhTourParams) (KhoiHanhTour, error) {
	row := q.db.QueryRow(ctx, updateKhoiHanhTour,
		arg.ID,
		arg.TourID,
		arg.NgayKhoiHanh,
		arg.NgayKetThuc,
		arg.SucChua,
		arg.TrangThai,
		arg.GhiChu,
		arg.SoChoDaDat,
	)
	var i KhoiHanhTour
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.NgayKhoiHanh,
		&i.NgayKetThuc,
		&i.SucChua,
		&i.SoChoDaDat,
		&i.TrangThai,
		&i.GhiChu,
		&i.NgayTao,
		&i.NgayCapNhat,
	)
	return i, err
}

const updateLichTrinh = `-- name: UpdateLichTrinh :one
UPDATE lich_trinh
SET
    ngay_thu = COALESCE($2, ngay_thu),
    tieu_de = COALESCE($3, tieu_de),
    mo_ta = COALESCE($4, mo_ta),
    gio_bat_dau = COALESCE($5, gio_bat_dau),
    gio_ket_thuc = COALESCE($6, gio_ket_thuc),
    dia_diem = COALESCE($7, dia_diem),
    thong_tin_luu_tru = COALESCE($8, thong_tin_luu_tru),
    ngay_cap_nhat = NOW()
WHERE id = $1
RETURNING id, tour_id, ngay_thu, tieu_de, mo_ta, gio_bat_dau, gio_ket_thuc, dia_diem, thong_tin_luu_tru, ngay_tao, ngay_cap_nhat
`

type UpdateLichTrinhParams struct {
	ID             int32       `json:"id"`
	NgayThu        *int32      `json:"ngay_thu"`
	TieuDe         *string     `json:"tieu_de"`
	MoTa           *string     `json:"mo_ta"`
	GioBatDau      pgtype.Time `json:"gio_bat_dau"`
	GioKetThuc     pgtype.Time `json:"gio_ket_thuc"`
	DiaDiem        *string     `json:"dia_diem"`
	ThongTinLuuTru *string     `json:"thong_tin_luu_tru"`
}

func (q *Queries) UpdateLichTrinh(ctx context.Context, arg UpdateLichTrinhParams) (LichTrinh, error) {
	row := q.db.QueryRow(ctx, updateLichTrinh,
		arg.ID,
		arg.NgayThu,
		arg.TieuDe,
		arg.MoTa,
		arg.GioBatDau,
		arg.GioKetThuc,
		arg.DiaDiem,
		arg.ThongTinLuuTru,
	)
	var i LichTrinh
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.NgayThu,
		&i.TieuDe,
		&i.MoTa,
		&i.GioBatDau,
		&i.GioKetThuc,
		&i.DiaDiem,
		&i.ThongTinLuuTru,
		&i.NgayTao,
		&i.NgayCapNhat,
	)
	return i, err
}
