// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: discount.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkDiscountOverlap = `-- name: CheckDiscountOverlap :one
SELECT EXISTS(
    SELECT 1 FROM giam_gia_tour
    WHERE tour_id = $1
      AND id != COALESCE($2, 0)
      AND (
          (ngay_bat_dau <= $3 AND ngay_ket_thuc >= $3)
          OR (ngay_bat_dau <= $4 AND ngay_ket_thuc >= $4)
          OR (ngay_bat_dau >= $3 AND ngay_ket_thuc <= $4)
      )
) as has_overlap
`

type CheckDiscountOverlapParams struct {
	TourID       int32       `json:"tour_id"`
	ID           int32       `json:"id"`
	NgayBatDau   pgtype.Date `json:"ngay_bat_dau"`
	NgayBatDau_2 pgtype.Date `json:"ngay_bat_dau_2"`
}

func (q *Queries) CheckDiscountOverlap(ctx context.Context, arg CheckDiscountOverlapParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkDiscountOverlap,
		arg.TourID,
		arg.ID,
		arg.NgayBatDau,
		arg.NgayBatDau_2,
	)
	var has_overlap bool
	err := row.Scan(&has_overlap)
	return has_overlap, err
}

const countActiveDiscounts = `-- name: CountActiveDiscounts :one
SELECT COUNT(*) FROM giam_gia_tour
WHERE ngay_bat_dau <= CURRENT_DATE
  AND ngay_ket_thuc >= CURRENT_DATE
`

func (q *Queries) CountActiveDiscounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveDiscounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDiscount = `-- name: CreateDiscount :one

INSERT INTO giam_gia_tour (
    tour_id,
    phan_tram,
    ngay_bat_dau,
    ngay_ket_thuc
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, tour_id, phan_tram, ngay_bat_dau, ngay_ket_thuc, ngay_tao, ngay_cap_nhat
`

type CreateDiscountParams struct {
	TourID      int32          `json:"tour_id"`
	PhanTram    pgtype.Numeric `json:"phan_tram"`
	NgayBatDau  pgtype.Date    `json:"ngay_bat_dau"`
	NgayKetThuc pgtype.Date    `json:"ngay_ket_thuc"`
}

// ==================== DISCOUNT/PROMOTION MANAGEMENT ====================
func (q *Queries) CreateDiscount(ctx context.Context, arg CreateDiscountParams) (GiamGiaTour, error) {
	row := q.db.QueryRow(ctx, createDiscount,
		arg.TourID,
		arg.PhanTram,
		arg.NgayBatDau,
		arg.NgayKetThuc,
	)
	var i GiamGiaTour
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.PhanTram,
		&i.NgayBatDau,
		&i.NgayKetThuc,
		&i.NgayTao,
		&i.NgayCapNhat,
	)
	return i, err
}

const deleteDiscount = `-- name: DeleteDiscount :exec
DELETE FROM giam_gia_tour
WHERE id = $1
`

func (q *Queries) DeleteDiscount(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteDiscount, id)
	return err
}

const getActiveDiscountsByTour = `-- name: GetActiveDiscountsByTour :many
SELECT id, tour_id, phan_tram, ngay_bat_dau, ngay_ket_thuc, ngay_tao, ngay_cap_nhat FROM giam_gia_tour
WHERE tour_id = $1
  AND ngay_bat_dau <= CURRENT_DATE
  AND ngay_ket_thuc >= CURRENT_DATE
ORDER BY phan_tram DESC
`

func (q *Queries) GetActiveDiscountsByTour(ctx context.Context, tourID int32) ([]GiamGiaTour, error) {
	rows, err := q.db.Query(ctx, getActiveDiscountsByTour, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GiamGiaTour
	for rows.Next() {
		var i GiamGiaTour
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.PhanTram,
			&i.NgayBatDau,
			&i.NgayKetThuc,
			&i.NgayTao,
			&i.NgayCapNhat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllActiveDiscounts = `-- name: GetAllActiveDiscounts :many
SELECT 
    gg.id, gg.tour_id, gg.phan_tram, gg.ngay_bat_dau, gg.ngay_ket_thuc, gg.ngay_tao, gg.ngay_cap_nhat,
    t.tieu_de as ten_tour,
    t.gia_moi_nguoi as gia_goc,
    t.gia_moi_nguoi * (100 - gg.phan_tram) / 100 as gia_sau_giam
FROM giam_gia_tour gg
JOIN tour t ON gg.tour_id = t.id
WHERE gg.ngay_bat_dau <= CURRENT_DATE
  AND gg.ngay_ket_thuc >= CURRENT_DATE
  AND t.dang_hoat_dong = TRUE
ORDER BY gg.phan_tram DESC
LIMIT $1 OFFSET $2
`

type GetAllActiveDiscountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAllActiveDiscountsRow struct {
	ID          int32            `json:"id"`
	TourID      int32            `json:"tour_id"`
	PhanTram    pgtype.Numeric   `json:"phan_tram"`
	NgayBatDau  pgtype.Date      `json:"ngay_bat_dau"`
	NgayKetThuc pgtype.Date      `json:"ngay_ket_thuc"`
	NgayTao     pgtype.Timestamp `json:"ngay_tao"`
	NgayCapNhat pgtype.Timestamp `json:"ngay_cap_nhat"`
	TenTour     string           `json:"ten_tour"`
	GiaGoc      pgtype.Numeric   `json:"gia_goc"`
	GiaSauGiam  int32            `json:"gia_sau_giam"`
}

func (q *Queries) GetAllActiveDiscounts(ctx context.Context, arg GetAllActiveDiscountsParams) ([]GetAllActiveDiscountsRow, error) {
	rows, err := q.db.Query(ctx, getAllActiveDiscounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActiveDiscountsRow
	for rows.Next() {
		var i GetAllActiveDiscountsRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.PhanTram,
			&i.NgayBatDau,
			&i.NgayKetThuc,
			&i.NgayTao,
			&i.NgayCapNhat,
			&i.TenTour,
			&i.GiaGoc,
			&i.GiaSauGiam,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBestDiscounts = `-- name: GetBestDiscounts :many
SELECT 
    gg.id, gg.tour_id, gg.phan_tram, gg.ngay_bat_dau, gg.ngay_ket_thuc, gg.ngay_tao, gg.ngay_cap_nhat,
    t.tieu_de as ten_tour,
    t.gia_moi_nguoi as gia_goc,
    t.gia_moi_nguoi * (100 - gg.phan_tram) / 100 as gia_sau_giam,
    (
        SELECT link FROM anh_tour 
        WHERE tour_id = t.id AND la_anh_chinh = true 
        LIMIT 1
    ) as anh_tour
FROM giam_gia_tour gg
JOIN tour t ON gg.tour_id = t.id
WHERE gg.ngay_bat_dau <= CURRENT_DATE
  AND gg.ngay_ket_thuc >= CURRENT_DATE
  AND t.dang_hoat_dong = TRUE
  AND gg.phan_tram >= $1
ORDER BY gg.phan_tram DESC
LIMIT $2
`

type GetBestDiscountsParams struct {
	PhanTram pgtype.Numeric `json:"phan_tram"`
	Limit    int32          `json:"limit"`
}

type GetBestDiscountsRow struct {
	ID          int32            `json:"id"`
	TourID      int32            `json:"tour_id"`
	PhanTram    pgtype.Numeric   `json:"phan_tram"`
	NgayBatDau  pgtype.Date      `json:"ngay_bat_dau"`
	NgayKetThuc pgtype.Date      `json:"ngay_ket_thuc"`
	NgayTao     pgtype.Timestamp `json:"ngay_tao"`
	NgayCapNhat pgtype.Timestamp `json:"ngay_cap_nhat"`
	TenTour     string           `json:"ten_tour"`
	GiaGoc      pgtype.Numeric   `json:"gia_goc"`
	GiaSauGiam  int32            `json:"gia_sau_giam"`
	AnhTour     string           `json:"anh_tour"`
}

func (q *Queries) GetBestDiscounts(ctx context.Context, arg GetBestDiscountsParams) ([]GetBestDiscountsRow, error) {
	rows, err := q.db.Query(ctx, getBestDiscounts, arg.PhanTram, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBestDiscountsRow
	for rows.Next() {
		var i GetBestDiscountsRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.PhanTram,
			&i.NgayBatDau,
			&i.NgayKetThuc,
			&i.NgayTao,
			&i.NgayCapNhat,
			&i.TenTour,
			&i.GiaGoc,
			&i.GiaSauGiam,
			&i.AnhTour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentDiscountForTour = `-- name: GetCurrentDiscountForTour :one
SELECT id, tour_id, phan_tram, ngay_bat_dau, ngay_ket_thuc, ngay_tao, ngay_cap_nhat FROM giam_gia_tour
WHERE tour_id = $1
  AND ngay_bat_dau <= CURRENT_DATE
  AND ngay_ket_thuc >= CURRENT_DATE
ORDER BY phan_tram DESC
LIMIT 1
`

func (q *Queries) GetCurrentDiscountForTour(ctx context.Context, tourID int32) (GiamGiaTour, error) {
	row := q.db.QueryRow(ctx, getCurrentDiscountForTour, tourID)
	var i GiamGiaTour
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.PhanTram,
		&i.NgayBatDau,
		&i.NgayKetThuc,
		&i.NgayTao,
		&i.NgayCapNhat,
	)
	return i, err
}

const getDiscountByID = `-- name: GetDiscountByID :one
SELECT 
    gg.id, gg.tour_id, gg.phan_tram, gg.ngay_bat_dau, gg.ngay_ket_thuc, gg.ngay_tao, gg.ngay_cap_nhat,
    t.tieu_de as ten_tour
FROM giam_gia_tour gg
JOIN tour t ON gg.tour_id = t.id
WHERE gg.id = $1
`

type GetDiscountByIDRow struct {
	ID          int32            `json:"id"`
	TourID      int32            `json:"tour_id"`
	PhanTram    pgtype.Numeric   `json:"phan_tram"`
	NgayBatDau  pgtype.Date      `json:"ngay_bat_dau"`
	NgayKetThuc pgtype.Date      `json:"ngay_ket_thuc"`
	NgayTao     pgtype.Timestamp `json:"ngay_tao"`
	NgayCapNhat pgtype.Timestamp `json:"ngay_cap_nhat"`
	TenTour     string           `json:"ten_tour"`
}

func (q *Queries) GetDiscountByID(ctx context.Context, id int32) (GetDiscountByIDRow, error) {
	row := q.db.QueryRow(ctx, getDiscountByID, id)
	var i GetDiscountByIDRow
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.PhanTram,
		&i.NgayBatDau,
		&i.NgayKetThuc,
		&i.NgayTao,
		&i.NgayCapNhat,
		&i.TenTour,
	)
	return i, err
}

const getDiscountStatsByTour = `-- name: GetDiscountStatsByTour :one
SELECT 
    COUNT(*) as tong_so_giam_gia,
    AVG(phan_tram) as phan_tram_trung_binh,
    MAX(phan_tram) as phan_tram_cao_nhat,
    MIN(phan_tram) as phan_tram_thap_nhat
FROM giam_gia_tour
WHERE tour_id = $1
`

type GetDiscountStatsByTourRow struct {
	TongSoGiamGia     int64       `json:"tong_so_giam_gia"`
	PhanTramTrungBinh float64     `json:"phan_tram_trung_binh"`
	PhanTramCaoNhat   interface{} `json:"phan_tram_cao_nhat"`
	PhanTramThapNhat  interface{} `json:"phan_tram_thap_nhat"`
}

func (q *Queries) GetDiscountStatsByTour(ctx context.Context, tourID int32) (GetDiscountStatsByTourRow, error) {
	row := q.db.QueryRow(ctx, getDiscountStatsByTour, tourID)
	var i GetDiscountStatsByTourRow
	err := row.Scan(
		&i.TongSoGiamGia,
		&i.PhanTramTrungBinh,
		&i.PhanTramCaoNhat,
		&i.PhanTramThapNhat,
	)
	return i, err
}

const getDiscountsByTour = `-- name: GetDiscountsByTour :many
SELECT id, tour_id, phan_tram, ngay_bat_dau, ngay_ket_thuc, ngay_tao, ngay_cap_nhat FROM giam_gia_tour
WHERE tour_id = $1
ORDER BY ngay_bat_dau DESC
`

func (q *Queries) GetDiscountsByTour(ctx context.Context, tourID int32) ([]GiamGiaTour, error) {
	rows, err := q.db.Query(ctx, getDiscountsByTour, tourID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GiamGiaTour
	for rows.Next() {
		var i GiamGiaTour
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.PhanTram,
			&i.NgayBatDau,
			&i.NgayKetThuc,
			&i.NgayTao,
			&i.NgayCapNhat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredDiscounts = `-- name: GetExpiredDiscounts :many
SELECT 
    gg.id, gg.tour_id, gg.phan_tram, gg.ngay_bat_dau, gg.ngay_ket_thuc, gg.ngay_tao, gg.ngay_cap_nhat,
    t.tieu_de as ten_tour
FROM giam_gia_tour gg
JOIN tour t ON gg.tour_id = t.id
WHERE gg.ngay_ket_thuc < CURRENT_DATE
ORDER BY gg.ngay_ket_thuc DESC
LIMIT $1 OFFSET $2
`

type GetExpiredDiscountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetExpiredDiscountsRow struct {
	ID          int32            `json:"id"`
	TourID      int32            `json:"tour_id"`
	PhanTram    pgtype.Numeric   `json:"phan_tram"`
	NgayBatDau  pgtype.Date      `json:"ngay_bat_dau"`
	NgayKetThuc pgtype.Date      `json:"ngay_ket_thuc"`
	NgayTao     pgtype.Timestamp `json:"ngay_tao"`
	NgayCapNhat pgtype.Timestamp `json:"ngay_cap_nhat"`
	TenTour     string           `json:"ten_tour"`
}

func (q *Queries) GetExpiredDiscounts(ctx context.Context, arg GetExpiredDiscountsParams) ([]GetExpiredDiscountsRow, error) {
	rows, err := q.db.Query(ctx, getExpiredDiscounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiredDiscountsRow
	for rows.Next() {
		var i GetExpiredDiscountsRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.PhanTram,
			&i.NgayBatDau,
			&i.NgayKetThuc,
			&i.NgayTao,
			&i.NgayCapNhat,
			&i.TenTour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getToursWithActiveDiscount = `-- name: GetToursWithActiveDiscount :many
SELECT DISTINCT
    t.id, t.tieu_de, t.mo_ta, t.danh_muc_id, t.so_ngay, t.so_dem, t.gia_moi_nguoi, t.don_vi_tien_te, t.trang_thai, t.noi_bat, t.nguoi_tao_id, t.nha_cung_cap_id, t.dang_hoat_dong, t.ngay_tao, t.ngay_cap_nhat,
    gg.phan_tram as giam_gia,
    t.gia_moi_nguoi * (100 - gg.phan_tram) / 100 as gia_sau_giam,
    gg.ngay_ket_thuc as han_giam_gia
FROM tour t
JOIN giam_gia_tour gg ON t.id = gg.tour_id
WHERE gg.ngay_bat_dau <= CURRENT_DATE
  AND gg.ngay_ket_thuc >= CURRENT_DATE
  AND t.dang_hoat_dong = TRUE
ORDER BY gg.phan_tram DESC
LIMIT $1 OFFSET $2
`

type GetToursWithActiveDiscountParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetToursWithActiveDiscountRow struct {
	ID           int32            `json:"id"`
	TieuDe       string           `json:"tieu_de"`
	MoTa         *string          `json:"mo_ta"`
	DanhMucID    *int32           `json:"danh_muc_id"`
	SoNgay       int32            `json:"so_ngay"`
	SoDem        int32            `json:"so_dem"`
	GiaMoiNguoi  pgtype.Numeric   `json:"gia_moi_nguoi"`
	DonViTienTe  *string          `json:"don_vi_tien_te"`
	TrangThai    *string          `json:"trang_thai"`
	NoiBat       *bool            `json:"noi_bat"`
	NguoiTaoID   pgtype.UUID      `json:"nguoi_tao_id"`
	NhaCungCapID *int32           `json:"nha_cung_cap_id"`
	DangHoatDong *bool            `json:"dang_hoat_dong"`
	NgayTao      pgtype.Timestamp `json:"ngay_tao"`
	NgayCapNhat  pgtype.Timestamp `json:"ngay_cap_nhat"`
	GiamGia      pgtype.Numeric   `json:"giam_gia"`
	GiaSauGiam   int32            `json:"gia_sau_giam"`
	HanGiamGia   pgtype.Date      `json:"han_giam_gia"`
}

func (q *Queries) GetToursWithActiveDiscount(ctx context.Context, arg GetToursWithActiveDiscountParams) ([]GetToursWithActiveDiscountRow, error) {
	rows, err := q.db.Query(ctx, getToursWithActiveDiscount, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetToursWithActiveDiscountRow
	for rows.Next() {
		var i GetToursWithActiveDiscountRow
		if err := rows.Scan(
			&i.ID,
			&i.TieuDe,
			&i.MoTa,
			&i.DanhMucID,
			&i.SoNgay,
			&i.SoDem,
			&i.GiaMoiNguoi,
			&i.DonViTienTe,
			&i.TrangThai,
			&i.NoiBat,
			&i.NguoiTaoID,
			&i.NhaCungCapID,
			&i.DangHoatDong,
			&i.NgayTao,
			&i.NgayCapNhat,
			&i.GiamGia,
			&i.GiaSauGiam,
			&i.HanGiamGia,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingDiscounts = `-- name: GetUpcomingDiscounts :many
SELECT 
    gg.id, gg.tour_id, gg.phan_tram, gg.ngay_bat_dau, gg.ngay_ket_thuc, gg.ngay_tao, gg.ngay_cap_nhat,
    t.tieu_de as ten_tour
FROM giam_gia_tour gg
JOIN tour t ON gg.tour_id = t.id
WHERE gg.ngay_bat_dau > CURRENT_DATE
  AND t.dang_hoat_dong = TRUE
ORDER BY gg.ngay_bat_dau ASC
LIMIT $1
`

type GetUpcomingDiscountsRow struct {
	ID          int32            `json:"id"`
	TourID      int32            `json:"tour_id"`
	PhanTram    pgtype.Numeric   `json:"phan_tram"`
	NgayBatDau  pgtype.Date      `json:"ngay_bat_dau"`
	NgayKetThuc pgtype.Date      `json:"ngay_ket_thuc"`
	NgayTao     pgtype.Timestamp `json:"ngay_tao"`
	NgayCapNhat pgtype.Timestamp `json:"ngay_cap_nhat"`
	TenTour     string           `json:"ten_tour"`
}

func (q *Queries) GetUpcomingDiscounts(ctx context.Context, limit int32) ([]GetUpcomingDiscountsRow, error) {
	rows, err := q.db.Query(ctx, getUpcomingDiscounts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpcomingDiscountsRow
	for rows.Next() {
		var i GetUpcomingDiscountsRow
		if err := rows.Scan(
			&i.ID,
			&i.TourID,
			&i.PhanTram,
			&i.NgayBatDau,
			&i.NgayKetThuc,
			&i.NgayTao,
			&i.NgayCapNhat,
			&i.TenTour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiscount = `-- name: UpdateDiscount :one
UPDATE giam_gia_tour
SET 
    phan_tram = COALESCE($2, phan_tram),
    ngay_bat_dau = COALESCE($3, ngay_bat_dau),
    ngay_ket_thuc = COALESCE($4, ngay_ket_thuc),
    ngay_cap_nhat = NOW()
WHERE id = $1
RETURNING id, tour_id, phan_tram, ngay_bat_dau, ngay_ket_thuc, ngay_tao, ngay_cap_nhat
`

type UpdateDiscountParams struct {
	ID          int32          `json:"id"`
	PhanTram    pgtype.Numeric `json:"phan_tram"`
	NgayBatDau  pgtype.Date    `json:"ngay_bat_dau"`
	NgayKetThuc pgtype.Date    `json:"ngay_ket_thuc"`
}

func (q *Queries) UpdateDiscount(ctx context.Context, arg UpdateDiscountParams) (GiamGiaTour, error) {
	row := q.db.QueryRow(ctx, updateDiscount,
		arg.ID,
		arg.PhanTram,
		arg.NgayBatDau,
		arg.NgayKetThuc,
	)
	var i GiamGiaTour
	err := row.Scan(
		&i.ID,
		&i.TourID,
		&i.PhanTram,
		&i.NgayBatDau,
		&i.NgayKetThuc,
		&i.NgayTao,
		&i.NgayCapNhat,
	)
	return i, err
}
