// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notification.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotificationsByUser = `-- name: CountUnreadNotificationsByUser :one
SELECT COUNT(*)::int FROM thong_bao
WHERE nguoi_dung_id = $1 AND da_doc = FALSE
`

// Đếm số thông báo chưa đọc
func (q *Queries) CountUnreadNotificationsByUser(ctx context.Context, nguoiDungID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadNotificationsByUser, nguoiDungID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO thong_bao (
    nguoi_dung_id,
    tieu_de,
    noi_dung,
    loai,
    lien_ket
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, nguoi_dung_id, tieu_de, noi_dung, loai, lien_ket, da_doc, ngay_tao
`

type CreateNotificationParams struct {
	NguoiDungID pgtype.UUID `json:"nguoi_dung_id"`
	TieuDe      *string     `json:"tieu_de"`
	NoiDung     *string     `json:"noi_dung"`
	Loai        *string     `json:"loai"`
	LienKet     *string     `json:"lien_ket"`
}

// ===========================================
// THÔNG BÁO (NOTIFICATIONS)
// ===========================================
// Tạo thông báo mới
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (ThongBao, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.NguoiDungID,
		arg.TieuDe,
		arg.NoiDung,
		arg.Loai,
		arg.LienKet,
	)
	var i ThongBao
	err := row.Scan(
		&i.ID,
		&i.NguoiDungID,
		&i.TieuDe,
		&i.NoiDung,
		&i.Loai,
		&i.LienKet,
		&i.DaDoc,
		&i.NgayTao,
	)
	return i, err
}

const createNotificationForContactResponse = `-- name: CreateNotificationForContactResponse :one
INSERT INTO thong_bao (
    nguoi_dung_id,
    tieu_de,
    noi_dung,
    loai,
    lien_ket
) 
SELECT 
    lh.nguoi_dung_id,
    'Phản hồi liên hệ: ' || lh.tieu_de,
    'Chúng tôi đã phản hồi yêu cầu của bạn: ' || ph.noi_dung,
    'system',
    '/contact'
FROM lien_he lh
JOIN phan_hoi_lien_he ph ON ph.lien_he_id = lh.id
WHERE lh.id = $1 AND ph.id = $2 AND lh.nguoi_dung_id IS NOT NULL
RETURNING id, nguoi_dung_id, tieu_de, noi_dung, loai, lien_ket, da_doc, ngay_tao
`

type CreateNotificationForContactResponseParams struct {
	LienHeID  int32 `json:"lien_he_id"`
	PhanHoiID int32 `json:"phan_hoi_id"`
}

// Tạo thông báo khi admin phản hồi liên hệ
// Function này sẽ được gọi tự động khi có phản hồi
func (q *Queries) CreateNotificationForContactResponse(ctx context.Context, arg CreateNotificationForContactResponseParams) (ThongBao, error) {
	row := q.db.QueryRow(ctx, createNotificationForContactResponse, arg.LienHeID, arg.PhanHoiID)
	var i ThongBao
	err := row.Scan(
		&i.ID,
		&i.NguoiDungID,
		&i.TieuDe,
		&i.NoiDung,
		&i.Loai,
		&i.LienKet,
		&i.DaDoc,
		&i.NgayTao,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM thong_bao WHERE id = $1
`

// Xóa thông báo
func (q *Queries) DeleteNotification(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteNotification, id)
	return err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, nguoi_dung_id, tieu_de, noi_dung, loai, lien_ket, da_doc, ngay_tao FROM thong_bao WHERE id = $1
`

// Lấy thông báo theo ID
func (q *Queries) GetNotificationByID(ctx context.Context, id int32) (ThongBao, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i ThongBao
	err := row.Scan(
		&i.ID,
		&i.NguoiDungID,
		&i.TieuDe,
		&i.NoiDung,
		&i.Loai,
		&i.LienKet,
		&i.DaDoc,
		&i.NgayTao,
	)
	return i, err
}

const getNotificationsByUser = `-- name: GetNotificationsByUser :many
SELECT id, nguoi_dung_id, tieu_de, noi_dung, loai, lien_ket, da_doc, ngay_tao FROM thong_bao
WHERE nguoi_dung_id = $1
ORDER BY ngay_tao DESC
LIMIT $2 OFFSET $3
`

type GetNotificationsByUserParams struct {
	NguoiDungID pgtype.UUID `json:"nguoi_dung_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

// Lấy thông báo của người dùng (có phân trang)
func (q *Queries) GetNotificationsByUser(ctx context.Context, arg GetNotificationsByUserParams) ([]ThongBao, error) {
	rows, err := q.db.Query(ctx, getNotificationsByUser, arg.NguoiDungID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThongBao
	for rows.Next() {
		var i ThongBao
		if err := rows.Scan(
			&i.ID,
			&i.NguoiDungID,
			&i.TieuDe,
			&i.NoiDung,
			&i.Loai,
			&i.LienKet,
			&i.DaDoc,
			&i.NgayTao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadNotificationsByUser = `-- name: GetUnreadNotificationsByUser :many
SELECT id, nguoi_dung_id, tieu_de, noi_dung, loai, lien_ket, da_doc, ngay_tao FROM thong_bao
WHERE nguoi_dung_id = $1 AND da_doc = FALSE
ORDER BY ngay_tao DESC
LIMIT $2 OFFSET $3
`

type GetUnreadNotificationsByUserParams struct {
	NguoiDungID pgtype.UUID `json:"nguoi_dung_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

// Lấy thông báo chưa đọc của người dùng
func (q *Queries) GetUnreadNotificationsByUser(ctx context.Context, arg GetUnreadNotificationsByUserParams) ([]ThongBao, error) {
	rows, err := q.db.Query(ctx, getUnreadNotificationsByUser, arg.NguoiDungID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThongBao
	for rows.Next() {
		var i ThongBao
		if err := rows.Scan(
			&i.ID,
			&i.NguoiDungID,
			&i.TieuDe,
			&i.NoiDung,
			&i.Loai,
			&i.LienKet,
			&i.DaDoc,
			&i.NgayTao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE thong_bao
SET da_doc = TRUE
WHERE nguoi_dung_id = $1 AND da_doc = FALSE
`

// Đánh dấu tất cả thông báo của user đã đọc
func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, nguoiDungID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsAsRead, nguoiDungID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :one
UPDATE thong_bao
SET da_doc = TRUE
WHERE id = $1
RETURNING id, nguoi_dung_id, tieu_de, noi_dung, loai, lien_ket, da_doc, ngay_tao
`

// Đánh dấu thông báo đã đọc
func (q *Queries) MarkNotificationAsRead(ctx context.Context, id int32) (ThongBao, error) {
	row := q.db.QueryRow(ctx, markNotificationAsRead, id)
	var i ThongBao
	err := row.Scan(
		&i.ID,
		&i.NguoiDungID,
		&i.TieuDe,
		&i.NoiDung,
		&i.Loai,
		&i.LienKet,
		&i.DaDoc,
		&i.NgayTao,
	)
	return i, err
}
