// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddHinhAnhTour(ctx context.Context, arg AddHinhAnhTourParams) (AnhTour, error)
	// ===========================================
	// BƯỚC 3: NHẬP THÔNG TIN HÀNH KHÁCH
	// ===========================================
	// Thêm hành khách vào booking
	AddPassenger(ctx context.Context, arg AddPassengerParams) (HanhKhach, error)
	// Thêm nhiều hành khách cùng lúc
	AddPassengers(ctx context.Context, arg []AddPassengersParams) (int64, error)
	AddTourDestination(ctx context.Context, arg AddTourDestinationParams) error
	AddTourImage(ctx context.Context, arg AddTourImageParams) (AnhTour, error)
	//Trạng thái Đặt chỗ
	AdminChartBookingStatusStats(ctx context.Context, arg AdminChartBookingStatusStatsParams) ([]AdminChartBookingStatusStatsRow, error)
	//Cơ cấu Doanh thu theo Danh mục
	AdminChartCategoryDistribution(ctx context.Context, arg AdminChartCategoryDistributionParams) ([]AdminChartCategoryDistributionRow, error)
	// Xu hướng Doanh thu & Đặt chỗ
	AdminChartRevenueTrend(ctx context.Context, arg AdminChartRevenueTrendParams) ([]AdminChartRevenueTrendRow, error)
	//Top 5 Nhà cung cấp xuất sắc
	AdminChartTopSuppliers(ctx context.Context, arg AdminChartTopSuppliersParams) ([]AdminChartTopSuppliersRow, error)
	AdminCustomerGrowthMonthlyReport(ctx context.Context, nam int32) ([]AdminCustomerGrowthMonthlyReportRow, error)
	ApproveComment(ctx context.Context, id int32) (BinhLuanBlog, error)
	// phê duyệt nhà cung cấp
	ApproveSupplier(ctx context.Context, id pgtype.UUID) (NguoiDung, error)
	// Tự động hoàn thành các booking sau khi tour kết thúc (chạy bằng cron job)
	AutoCompleteBookings(ctx context.Context) error
	// cập nhật trạng thái nhà cung cấp hàng loạt
	BulkUpdateSupplierStatus(ctx context.Context, dollar_1 []int32) error
	CalculateRefundAmount(ctx context.Context, bookingID int32) (CalculateRefundAmountRow, error)
	// Tính giá tour cho khách hàng xem trước khi đặt
	CalculateTourPrice(ctx context.Context, arg CalculateTourPriceParams) (CalculateTourPriceRow, error)
	CancelBooking(ctx context.Context, bookingID int32) (CancelBookingRow, error)
	CancelDeparture(ctx context.Context, id int32) (KhoiHanhTour, error)
	ChangePassword(ctx context.Context, arg ChangePasswordParams) error
	// Kiểm tra booking có thể đánh giá: trang_thai_dat_cho = 'da_thanh_toan' VÀ trang_thai_khoi_hanh = 'hoan_thanh'
	CheckBookingCompletedAndNotReviewed(ctx context.Context, arg CheckBookingCompletedAndNotReviewedParams) (CheckBookingCompletedAndNotReviewedRow, error)
	// Kiểm tra còn đủ chỗ không
	CheckDepartureAvailability(ctx context.Context, arg CheckDepartureAvailabilityParams) (CheckDepartureAvailabilityRow, error)
	// Kiểm tra đã có review cho booking này chưa
	CheckReviewExists(ctx context.Context, arg CheckReviewExistsParams) (bool, error)
	// ===========================================
	// BƯỚC 6: HOÀN THÀNH TOUR
	// ===========================================
	// Đánh dấu booking hoàn thành (sau khi tour kết thúc)
	CompleteBooking(ctx context.Context, id int32) (DatCho, error)
	// ===========================================
	// BƯỚC 4: XÁC NHẬN ĐẶT CHỖ
	// ===========================================
	// Admin/Hệ thống xác nhận đặt chỗ
	ConfirmBooking(ctx context.Context, id int32) (DatCho, error)
	// Đếm tổng số booking cho admin với filter
	CountAllBookingsForAdmin(ctx context.Context, arg CountAllBookingsForAdminParams) (int32, error)
	CountAllTours(ctx context.Context) (int64, error)
	// Đếm tổng số giao dịch
	CountAllTransactions(ctx context.Context) (int64, error)
	CountBlogComments(ctx context.Context, blogID int32) (int64, error)
	CountBlogs(ctx context.Context, arg CountBlogsParams) (int64, error)
	// Đếm tổng số đặt chỗ của người dùng (có filter)
	CountBookingsByUser(ctx context.Context, arg CountBookingsByUserParams) (int32, error)
	CountContacts(ctx context.Context) (int64, error)
	CountContactsByStatus(ctx context.Context, trangThai *string) (int64, error)
	CountPublishedBlogs(ctx context.Context) (int64, error)
	CountSearchTours(ctx context.Context, arg CountSearchToursParams) (int64, error)
	// Đếm tổng số booking theo các filter nâng cao
	CountSupplierBookingsByStatusAdvanced(ctx context.Context, arg CountSupplierBookingsByStatusAdvancedParams) (int32, error)
	CountSuppliers(ctx context.Context) (int32, error)
	// đếm số lượng nhà cung cấp theo trạng thái
	CountSuppliersByStatus(ctx context.Context, email string) ([]CountSuppliersByStatusRow, error)
	CountToursBySupplier(ctx context.Context, nhaCungCapID pgtype.UUID) (int64, error)
	// Đếm số thông báo chưa đọc
	CountUnreadNotificationsByUser(ctx context.Context, nguoiDungID pgtype.UUID) (int32, error)
	// ==================== ACTIVITY QUERIES ====================
	CreateActivity(ctx context.Context, arg CreateActivityParams) (HoatDongTrongNgay, error)
	// ===========================================
	// BLOG QUERIES
	// ===========================================
	CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error)
	// ===========================================
	// BLOG AI HISTORY QUERIES
	// ===========================================
	CreateBlogAIHistory(ctx context.Context, arg CreateBlogAIHistoryParams) (LichSuAiBlog, error)
	// ===========================================
	// BLOG COMMENT QUERIES
	// ===========================================
	CreateBlogComment(ctx context.Context, arg CreateBlogCommentParams) (BinhLuanBlog, error)
	// Tạo đặt chỗ mới (tự động tính tổng tiền)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (CreateBookingRow, error)
	CreateCategoryTour(ctx context.Context, arg CreateCategoryTourParams) (DanhMucTour, error)
	CreateChatHistory(ctx context.Context, arg CreateChatHistoryParams) (LichSuChat, error)
	CreateContact(ctx context.Context, arg CreateContactParams) (LienHe, error)
	// ===========================================
	// PHẢN HỒI LIÊN HỆ
	// ===========================================
	// Tạo phản hồi cho liên hệ
	CreateContactResponse(ctx context.Context, arg CreateContactResponseParams) (PhanHoiLienHe, error)
	// ==================== DEPARTURE MANAGEMENT ====================
	// tạo lịch khởi hành
	CreateDeparture(ctx context.Context, arg CreateDepartureParams) (KhoiHanhTour, error)
	CreateDestination(ctx context.Context, arg CreateDestinationParams) (DiemDen, error)
	CreateDiscountTour(ctx context.Context, arg CreateDiscountTourParams) (GiamGiaTour, error)
	CreateFavoriteTour(ctx context.Context, arg CreateFavoriteTourParams) (TourYeuThich, error)
	// ==================== GROUP CONFIG QUERIES ====================
	CreateGroupConfig(ctx context.Context, arg CreateGroupConfigParams) (CauHinhNhomTour, error)
	// ==================== ITINERARY QUERIES ====================
	CreateItinerary(ctx context.Context, arg CreateItineraryParams) (LichTrinh, error)
	// ===========================================
	// THÔNG BÁO (NOTIFICATIONS)
	// ===========================================
	// Tạo thông báo mới
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (ThongBao, error)
	// Tạo thông báo khi admin phản hồi liên hệ
	// Function này sẽ được gọi tự động khi có phản hồi
	CreateNotificationForContactResponse(ctx context.Context, arg CreateNotificationForContactResponseParams) (ThongBao, error)
	CreatePasswordResetOTP(ctx context.Context, arg CreatePasswordResetOTPParams) (OtpDatLaiMatKhau, error)
	// Tạo đánh giá tour mới (chỉ khi booking đã hoàn thành)
	CreateReview(ctx context.Context, arg CreateReviewParams) (DanhGium, error)
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (NhaCungCap, error)
	// ==================== TOUR CRUD OPERATIONS ====================
	CreateTour(ctx context.Context, arg CreateTourParams) (Tour, error)
	// Tạo hoặc cập nhật embedding cho tour
	CreateTourEmbedding(ctx context.Context, arg CreateTourEmbeddingParams) (TourEmbedding, error)
	// ===========================================
	// QUERIES CHO AI GỢI Ý TOUR
	// ===========================================
	// Lưu lịch sử xem tour
	CreateTourViewHistory(ctx context.Context, arg CreateTourViewHistoryParams) (LichSuXemTour, error)
	// ===========================================
	// BƯỚC 5: THANH TOÁN
	// ===========================================
	// Tạo giao dịch thanh toán mới
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (LichSuGiaoDich, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (NguoiDung, error)
	DecrementBlogLikes(ctx context.Context, id int32) error
	DeleteActivitiesByItinerary(ctx context.Context, lichTrinhID int32) error
	DeleteActivity(ctx context.Context, arg DeleteActivityParams) error
	DeleteBlog(ctx context.Context, id int32) error
	// Xóa đặt chỗ
	DeleteBooking(ctx context.Context, id int32) error
	// Xóa nhiều đặt chỗ
	DeleteBookings(ctx context.Context, ids []int32) error
	DeleteChatHistoryBySessionID(ctx context.Context, maPhien string) error
	DeleteChatHistoryByUserID(ctx context.Context, nguoiDungID pgtype.UUID) error
	DeleteComment(ctx context.Context, id int32) error
	// Xóa phản hồi
	DeleteContactResponse(ctx context.Context, id int32) error
	DeleteDeparture(ctx context.Context, id int32) error
	DeleteDiscountTour(ctx context.Context, arg DeleteDiscountTourParams) error
	DeleteExpiredOTPs(ctx context.Context) error
	DeleteFavoriteTour(ctx context.Context, arg DeleteFavoriteTourParams) error
	DeleteGroupConfig(ctx context.Context, tourID int32) error
	DeleteHinhAnhTour(ctx context.Context, arg DeleteHinhAnhTourParams) error
	DeleteItinerariesByTour(ctx context.Context, tourID int32) error
	DeleteItinerary(ctx context.Context, arg DeleteItineraryParams) error
	// Xóa thông báo
	DeleteNotification(ctx context.Context, id int32) error
	// Xóa hành khách
	DeletePassenger(ctx context.Context, id int32) error
	DeleteSupplier(ctx context.Context, id pgtype.UUID) error
	DeleteTour(ctx context.Context, id int32) error
	DeleteTourDestination(ctx context.Context, arg DeleteTourDestinationParams) error
	DeleteTourImage(ctx context.Context, arg DeleteTourImageParams) error
	// Phản hồi đánh giá
	FeedbackReview(ctx context.Context, arg FeedbackReviewParams) (int32, error)
	FilterTours(ctx context.Context, arg FilterToursParams) ([]FilterToursRow, error)
	ForgotPassword(ctx context.Context, arg ForgotPasswordParams) error
	GetActiveSuppliers(ctx context.Context) ([]GetActiveSuppliersRow, error)
	GetActivitiesByItinerary(ctx context.Context, lichTrinhID int32) ([]HoatDongTrongNgay, error)
	GetActivityByID(ctx context.Context, id int32) (HoatDongTrongNgay, error)
	// Thống kê đặt chỗ chi tiết cho admin với nhiều filter
	GetAdminBookingStatistics(ctx context.Context, arg GetAdminBookingStatisticsParams) (GetAdminBookingStatisticsRow, error)
	// Lấy nhà cung cấp theo ID (admin)
	GetAdminSupplierByID(ctx context.Context, id pgtype.UUID) (GetAdminSupplierByIDRow, error)
	GetAllBlogs(ctx context.Context, arg GetAllBlogsParams) ([]GetAllBlogsRow, error)
	// Lấy tất cả booking cho admin với filter và pagination
	GetAllBookingsForAdmin(ctx context.Context, arg GetAllBookingsForAdminParams) ([]GetAllBookingsForAdminRow, error)
	GetAllContacts(ctx context.Context, arg GetAllContactsParams) ([]GetAllContactsRow, error)
	GetAllDepartures(ctx context.Context, arg GetAllDeparturesParams) ([]GetAllDeparturesRow, error)
	// ===========================================
	// QUẢN LÝ HOÀN TIỀN (REFUND MANAGEMENT)
	// ===========================================
	// Lấy tất cả refund cho admin (tất cả booking đã hủy với thông tin refund)
	GetAllRefunds(ctx context.Context, arg GetAllRefundsParams) ([]GetAllRefundsRow, error)
	//=====================================Nhà cung cấp=====================================
	GetAllSuppliers(ctx context.Context, arg GetAllSuppliersParams) ([]GetAllSuppliersRow, error)
	GetAllSuppliersIncludingDeleted(ctx context.Context) ([]GetAllSuppliersIncludingDeletedRow, error)
	GetAllTour(ctx context.Context, arg GetAllTourParams) ([]GetAllTourRow, error)
	GetAllTourCategory(ctx context.Context) ([]GetAllTourCategoryRow, error)
	// ==================== PAYMENT/TRANSACTION QUERIES ====================
	// Lấy tất cả giao dịch với thông tin đầy đủ (dành cho Admin)
	GetAllTransactions(ctx context.Context, arg GetAllTransactionsParams) ([]GetAllTransactionsRow, error)
	// ===========================================
	// BƯỚC 1: CHỌN TOUR & NGÀY KHỞI HÀNH
	// ===========================================
	// Lấy danh sách ngày khởi hành còn chỗ của một tour
	GetAvailableDepartures(ctx context.Context, tourID int32) ([]GetAvailableDeparturesRow, error)
	GetBlogAIHistory(ctx context.Context, blogID *int32) ([]LichSuAiBlog, error)
	GetBlogByID(ctx context.Context, id int32) (GetBlogByIDRow, error)
	GetBlogBySlug(ctx context.Context, slug string) (GetBlogBySlugRow, error)
	GetBlogCommentReplies(ctx context.Context, binhLuanChaID *int32) ([]GetBlogCommentRepliesRow, error)
	GetBlogComments(ctx context.Context, arg GetBlogCommentsParams) ([]GetBlogCommentsRow, error)
	GetBlogStats(ctx context.Context) (GetBlogStatsRow, error)
	GetBlogsByAuthor(ctx context.Context, arg GetBlogsByAuthorParams) ([]GetBlogsByAuthorRow, error)
	GetBlogsByCategory(ctx context.Context, arg GetBlogsByCategoryParams) ([]GetBlogsByCategoryRow, error)
	// Lấy thông tin đặt chỗ theo ID
	GetBookingById(ctx context.Context, id int32) (GetBookingByIdRow, error)
	// ===========================================
	// THỐNG KÊ & BÁO CÁO
	// ===========================================
	// Thống kê booking theo nhà cung cấp
	GetBookingStats(ctx context.Context, arg GetBookingStatsParams) (GetBookingStatsRow, error)
	// Thống kê booking theo ngày trong tuần
	GetBookingsByDayOfWeek(ctx context.Context) ([]GetBookingsByDayOfWeekRow, error)
	// Lấy booking theo trạng thái
	GetBookingsByStatus(ctx context.Context, arg GetBookingsByStatusParams) ([]GetBookingsByStatusRow, error)
	// Lấy danh sách đặt chỗ của người dùng
	GetBookingsByUser(ctx context.Context, arg GetBookingsByUserParams) ([]GetBookingsByUserRow, error)
	GetBookingsByUserId(ctx context.Context, nguoiDungID pgtype.UUID) ([]GetBookingsByUserIdRow, error)
	// Lấy danh sách booking đã hủy
	GetCancelledBookings(ctx context.Context, arg GetCancelledBookingsParams) ([]GetCancelledBookingsRow, error)
	GetChatHistoryBySessionID(ctx context.Context, arg GetChatHistoryBySessionIDParams) ([]LichSuChat, error)
	GetChatHistoryByUserID(ctx context.Context, arg GetChatHistoryByUserIDParams) ([]LichSuChat, error)
	GetCityByProvince(ctx context.Context, tinh *string) ([]GetCityByProvinceRow, error)
	GetContactByID(ctx context.Context, id int32) (GetContactByIDRow, error)
	// Lấy phản hồi theo ID
	GetContactResponseByID(ctx context.Context, id int32) (GetContactResponseByIDRow, error)
	// Lấy tất cả phản hồi của một liên hệ
	GetContactResponses(ctx context.Context, lienHeID int32) ([]GetContactResponsesRow, error)
	GetContactsByStatus(ctx context.Context, arg GetContactsByStatusParams) ([]GetContactsByStatusRow, error)
	GetCountry(ctx context.Context) ([]GetCountryRow, error)
	// Tổng quan dashboard: tổng số người dùng, tour, booking, doanh thu
	GetDashboardOverview(ctx context.Context) (GetDashboardOverviewRow, error)
	// Tổng quan dashboard: tổng số người dùng, tour, booking, doanh thu
	GetDashboardOverviewByMonthAndYear(ctx context.Context, arg GetDashboardOverviewByMonthAndYearParams) (GetDashboardOverviewByMonthAndYearRow, error)
	// lấy thông tin chi tiết của một lịch khởi hành
	GetDepartureByID(ctx context.Context, id int32) (GetDepartureByIDRow, error)
	// Lấy thông tin chi tiết một ngày khởi hành
	GetDepartureById(ctx context.Context, id int32) (GetDepartureByIdRow, error)
	GetDeparturesByDateRange(ctx context.Context, arg GetDeparturesByDateRangeParams) ([]GetDeparturesByDateRangeRow, error)
	GetDeparturesByStatus(ctx context.Context, arg GetDeparturesByStatusParams) ([]GetDeparturesByStatusRow, error)
	// lấy danh sách lịch khởi hành của một tour
	GetDeparturesByTour(ctx context.Context, tourID int32) ([]GetDeparturesByTourRow, error)
	// Lấy thông tin chi tiết điểm đến theo ID
	GetDestinationByID(ctx context.Context, id int32) (DiemDen, error)
	// Lấy danh sách đánh giá chi tiết với các bộ lọc theo sao và tour
	GetDetailedSupplierReviews(ctx context.Context, arg GetDetailedSupplierReviewsParams) ([]GetDetailedSupplierReviewsRow, error)
	GetDiscountsByTourID(ctx context.Context, tourID int32) ([]GiamGiaTour, error)
	GetFavoriteTours(ctx context.Context, nguoiDungID pgtype.UUID) ([]TourYeuThich, error)
	GetFeaturedBlogs(ctx context.Context, limit int32) ([]GetFeaturedBlogsRow, error)
	GetFeaturedTours(ctx context.Context, limit int32) ([]GetFeaturedToursRow, error)
	// Lấy danh sách phản hồi đánh giá
	GetFeedbackReview(ctx context.Context, danhGiaID int32) ([]PhanHoiDanhGium, error)
	// ==================== COMBINED QUERIES ====================
	GetFullItineraryByTour(ctx context.Context, tourID int32) ([]GetFullItineraryByTourRow, error)
	GetGroupConfigByTour(ctx context.Context, tourID int32) (CauHinhNhomTour, error)
	GetHinhAnhTourByID(ctx context.Context, id int32) (AnhTour, error)
	GetItinerariesByTour(ctx context.Context, tourID int32) ([]LichTrinh, error)
	GetItineraryByID(ctx context.Context, id int32) (LichTrinh, error)
	// =====================
	// 12. COMPREHENSIVE REPORTS
	// =====================
	// Báo cáo tháng
	GetMonthlyReport(ctx context.Context, dollar_1 pgtype.Date) (GetMonthlyReportRow, error)
	// Tours được yêu thích nhiều nhất
	GetMostFavoritedTours(ctx context.Context, limit int32) ([]GetMostFavoritedToursRow, error)
	// Lấy các tour được xem nhiều nhất
	GetMostViewedTours(ctx context.Context, limit int32) ([]GetMostViewedToursRow, error)
	// lấy danh sách tour của nhà cung cấp
	GetMyTours(ctx context.Context, arg GetMyToursParams) ([]Tour, error)
	// Lấy thông báo theo ID
	GetNotificationByID(ctx context.Context, id int32) (ThongBao, error)
	// Lấy thông báo của người dùng (có phân trang)
	GetNotificationsByUser(ctx context.Context, arg GetNotificationsByUserParams) ([]ThongBao, error)
	// Lấy danh sách hành khách của một booking
	GetPassengersByBooking(ctx context.Context, datChoID int32) ([]HanhKhach, error)
	GetPasswordResetOTP(ctx context.Context, arg GetPasswordResetOTPParams) (OtpDatLaiMatKhau, error)
	// Lấy danh sách cổng thanh toán đang hoạt động
	GetPaymentGateways(ctx context.Context) ([]CongThanhToan, error)
	// Lấy danh sách booking chờ xác nhận (dành cho Admin/NCC)
	GetPendingBookings(ctx context.Context, arg GetPendingBookingsParams) ([]GetPendingBookingsRow, error)
	GetPendingComments(ctx context.Context, arg GetPendingCommentsParams) ([]GetPendingCommentsRow, error)
	// Lấy các điểm đến phổ biến nhất (được nhiều tour sử dụng nhất)
	GetPopularDestinations(ctx context.Context, limit int32) ([]GetPopularDestinationsRow, error)
	GetProvinceByCountry(ctx context.Context, quocGia *string) ([]GetProvinceByCountryRow, error)
	GetPublishedBlogs(ctx context.Context, arg GetPublishedBlogsParams) ([]GetPublishedBlogsRow, error)
	// Báo cáo theo quý
	GetQuarterlyReport(ctx context.Context) ([]GetQuarterlyReportRow, error)
	// Booking gần đây
	GetRecentBookings(ctx context.Context, limit int32) ([]GetRecentBookingsRow, error)
	GetRecentChatHistory(ctx context.Context, arg GetRecentChatHistoryParams) ([]LichSuChat, error)
	// Gợi ý tour dựa trên các điểm đến mà người dùng đã yêu thích
	GetRecommendedToursByFavoriteDestinations(ctx context.Context, arg GetRecommendedToursByFavoriteDestinationsParams) ([]GetRecommendedToursByFavoriteDestinationsRow, error)
	// Gợi ý tour dựa trên sở thích người dùng (danh mục và điểm đến)
	GetRecommendedToursByPreferences(ctx context.Context, arg GetRecommendedToursByPreferencesParams) ([]GetRecommendedToursByPreferencesRow, error)
	// Gợi ý tour dựa trên lịch sử xem (ưu tiên tour xem lâu)
	GetRecommendedToursByViewHistory(ctx context.Context, arg GetRecommendedToursByViewHistoryParams) ([]GetRecommendedToursByViewHistoryRow, error)
	// Thống kê refund cho admin
	GetRefundStats(ctx context.Context, arg GetRefundStatsParams) (GetRefundStatsRow, error)
	GetRelatedBlogs(ctx context.Context, arg GetRelatedBlogsParams) ([]GetRelatedBlogsRow, error)
	// Doanh thu theo năm và tháng
	GetRevenueByDay(ctx context.Context, arg GetRevenueByDayParams) ([]GetRevenueByDayRow, error)
	GetReviewByTourId(ctx context.Context, tourID int32) (GetReviewByTourIdRow, error)
	// Tìm các tour tương tự dựa trên embedding (semantic search)
	GetSimilarToursByEmbedding(ctx context.Context, arg GetSimilarToursByEmbeddingParams) ([]GetSimilarToursByEmbeddingRow, error)
	// Thống kê booking theo trạng thái và thời gian
	GetSupplierBookingStatsByStatus(ctx context.Context, arg GetSupplierBookingStatsByStatusParams) ([]GetSupplierBookingStatsByStatusRow, error)
	// Lấy danh sách đặt chỗ theo trạng thái với nhiều filter nâng cao
	GetSupplierBookingsByStatusAdvanced(ctx context.Context, arg GetSupplierBookingsByStatusAdvancedParams) ([]GetSupplierBookingsByStatusAdvancedRow, error)
	GetSupplierByID(ctx context.Context, id pgtype.UUID) (GetSupplierByIDRow, error)
	GetSupplierById(ctx context.Context, id pgtype.UUID) (GetSupplierByIdRow, error)
	// Thống kê khách hàng: top khách hàng, số lần đặt, tổng tiền
	GetSupplierCustomerStats(ctx context.Context, arg GetSupplierCustomerStatsParams) ([]GetSupplierCustomerStatsRow, error)
	// ===========================================
	// DASHBOARD SUPPLIER - TRUY VẤN NÂNG CAO
	// ===========================================
	// Tổng quan dashboard: tổng doanh thu, số booking, số tour, đánh giá trung bình
	GetSupplierDashboardOverview(ctx context.Context, id pgtype.UUID) (GetSupplierDashboardOverviewRow, error)
	// Tăng trưởng nhà cung cấp theo tháng
	GetSupplierGrowthByMonth(ctx context.Context) ([]GetSupplierGrowthByMonthRow, error)
	// Phân tích đánh giá tour
	GetSupplierRatingAnalysis(ctx context.Context, id pgtype.UUID) (GetSupplierRatingAnalysisRow, error)
	// Booking gần đây
	GetSupplierRecentBookings(ctx context.Context, arg GetSupplierRecentBookingsParams) ([]GetSupplierRecentBookingsRow, error)
	// Thống kê refund cho supplier
	GetSupplierRefundStats(ctx context.Context, arg GetSupplierRefundStatsParams) (GetSupplierRefundStatsRow, error)
	// Lấy refund cho supplier (chỉ tour của họ)
	GetSupplierRefunds(ctx context.Context, arg GetSupplierRefundsParams) ([]GetSupplierRefundsRow, error)
	// Doanh thu theo khoảng thời gian (ngày, tuần, tháng)
	GetSupplierRevenueByTimeRange(ctx context.Context, arg GetSupplierRevenueByTimeRangeParams) ([]GetSupplierRevenueByTimeRangeRow, error)
	// Biểu đồ doanh thu theo thời gian (cho chart)
	GetSupplierRevenueChart(ctx context.Context, arg GetSupplierRevenueChartParams) ([]GetSupplierRevenueChartRow, error)
	// Thống kê doanh thu tổng hợp cho supplier
	GetSupplierRevenueStatistics(ctx context.Context, arg GetSupplierRevenueStatisticsParams) (GetSupplierRevenueStatisticsRow, error)
	// Thống kê chi tiết các chỉ số đánh giá của nhà cung cấp
	// Thống kê đánh giá của nhà cung cấp, có thể lọc theo từng tour cụ thể
	GetSupplierReviewStatistics(ctx context.Context, arg GetSupplierReviewStatisticsParams) (GetSupplierReviewStatisticsRow, error)
	// Tổng quan nhà cung cấp
	GetSupplierStats(ctx context.Context) (GetSupplierStatsRow, error)
	// Top tours bán chạy nhất theo số lượng booking và doanh thu
	GetSupplierTopTours(ctx context.Context, arg GetSupplierTopToursParams) ([]GetSupplierTopToursRow, error)
	// Thống kê tour theo danh mục của supplier
	GetSupplierTourStatsByCategory(ctx context.Context, id pgtype.UUID) ([]GetSupplierTourStatsByCategoryRow, error)
	// Thống kê tour theo trạng thái
	GetSupplierTourStatsByStatus(ctx context.Context, id pgtype.UUID) ([]GetSupplierTourStatsByStatusRow, error)
	// Lấy danh sách giao dịch (bookings đã thanh toán) với thông tin chi tiết
	GetSupplierTransactions(ctx context.Context, arg GetSupplierTransactionsParams) ([]GetSupplierTransactionsRow, error)
	// Lịch khởi hành sắp tới
	GetSupplierUpcomingDepartures(ctx context.Context, arg GetSupplierUpcomingDeparturesParams) ([]GetSupplierUpcomingDeparturesRow, error)
	GetSupplierWithTourCount(ctx context.Context, email string) ([]GetSupplierWithTourCountRow, error)
	GetSuppliersByStatus(ctx context.Context) ([]GetSuppliersByStatusRow, error)
	GetTicketsByBookingID(ctx context.Context, id int32) ([]GetTicketsByBookingIDRow, error)
	//=====================================Khách hàng=====================================
	// Top người dùng hoạt động nhiều nhất (theo số booking)
	GetTopActiveUsers(ctx context.Context, limit int32) ([]GetTopActiveUsersRow, error)
	// Top tours được đặt nhiều nhất
	GetTopBookedTours(ctx context.Context, limit int32) ([]GetTopBookedToursRow, error)
	// Top điểm đến phổ biến
	GetTopDestinations(ctx context.Context, limit int32) ([]GetTopDestinationsRow, error)
	// Lấy top N điểm đến phổ biến nhất với thông tin chi tiết (có số tour nổi bật)
	GetTopPopularDestinations(ctx context.Context, limit int32) ([]GetTopPopularDestinationsRow, error)
	// Top nhà cung cấp theo doanh thu
	GetTopSuppliersByRevenue(ctx context.Context, limit int32) ([]GetTopSuppliersByRevenueRow, error)
	// Top nhà cung cấp theo số tour
	GetTopSuppliersByTours(ctx context.Context, limit int32) ([]GetTopSuppliersByToursRow, error)
	GetTourContextForAI(ctx context.Context, arg GetTourContextForAIParams) ([]GetTourContextForAIRow, error)
	GetTourDestinations(ctx context.Context, tourID int32) ([]GetTourDestinationsRow, error)
	GetTourDetailByID(ctx context.Context, id int32) (GetTourDetailByIDRow, error)
	// Lấy embedding của một tour
	GetTourEmbedding(ctx context.Context, tourID int32) (TourEmbedding, error)
	GetTourImages(ctx context.Context, tourID int32) ([]AnhTour, error)
	// Phân bố giá tour
	GetTourPriceDistribution(ctx context.Context) ([]GetTourPriceDistributionRow, error)
	// Lấy lịch sử xem của một tour cụ thể
	GetTourViewHistoryByTour(ctx context.Context, arg GetTourViewHistoryByTourParams) ([]LichSuXemTour, error)
	// Lấy lịch sử xem tour của người dùng
	GetTourViewHistoryByUser(ctx context.Context, arg GetTourViewHistoryByUserParams) ([]LichSuXemTour, error)
	GetToursByCategoryFilter(ctx context.Context, arg GetToursByCategoryFilterParams) ([]GetToursByCategoryFilterRow, error)
	// Lấy tour quốc nội (iso2 = country_code) hoặc quốc tế (iso2 != country_code) sắp xếp theo số lượt đặt
	GetToursByCountryCode(ctx context.Context, arg GetToursByCountryCodeParams) ([]GetToursByCountryCodeRow, error)
	GetToursBySupplier(ctx context.Context, arg GetToursBySupplierParams) ([]Tour, error)
	// Tìm giao dịch theo mã nội bộ
	GetTransactionByCode(ctx context.Context, maGiaoDichNoiBo string) (LichSuGiaoDich, error)
	// Lấy lịch sử giao dịch của một booking
	GetTransactionsByBooking(ctx context.Context, datChoID *int32) ([]GetTransactionsByBookingRow, error)
	// Lấy giao dịch theo cổng thanh toán
	GetTransactionsByPaymentGateway(ctx context.Context, arg GetTransactionsByPaymentGatewayParams) ([]GetTransactionsByPaymentGatewayRow, error)
	// Lấy giao dịch theo trạng thái
	GetTransactionsByStatus(ctx context.Context, arg GetTransactionsByStatusParams) ([]GetTransactionsByStatusRow, error)
	GetUnreadContacts(ctx context.Context, arg GetUnreadContactsParams) ([]GetUnreadContactsRow, error)
	// Lấy thông báo chưa đọc của người dùng
	GetUnreadNotificationsByUser(ctx context.Context, arg GetUnreadNotificationsByUserParams) ([]ThongBao, error)
	GetUnverifiedPasswordResetOTP(ctx context.Context, arg GetUnverifiedPasswordResetOTPParams) (OtpDatLaiMatKhau, error)
	// =====================
	// 9. DEPARTURE STATISTICS
	// =====================
	// Các khởi hành sắp tới
	GetUpcomingDepartures(ctx context.Context, limit int32) ([]GetUpcomingDeparturesRow, error)
	GetUpcomingDeparturesList(ctx context.Context, limit int32) ([]GetUpcomingDeparturesListRow, error)
	GetUserByEmail(ctx context.Context, email string) (NguoiDung, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (GetUserByIdRow, error)
	// Note: yeu_thich table doesn't exist yet, will implement in Sprint 3-4
	// -- name: GetUserFavorites :many
	// SELECT * FROM yeu_thich
	// WHERE nguoi_dung_id = $1;
	// Function để xóa các OTP đã hết hạn
	GetUserPaymentHistory(ctx context.Context) ([]GetUserPaymentHistoryRow, error)
	// Lấy sở thích của người dùng
	GetUserPreferences(ctx context.Context, nguoiDungID pgtype.UUID) ([]SoThichNguoiDung, error)
	// Lấy sở thích theo loại (danh_muc hoặc diem_den)
	GetUserPreferencesByType(ctx context.Context, arg GetUserPreferencesByTypeParams) ([]SoThichNguoiDung, error)
	// =====================
	// 2. USER STATISTICS
	// =====================
	// Thống kê người dùng theo vai trò
	GetUserStatsByRole(ctx context.Context) ([]GetUserStatsByRoleRow, error)
	// So sánh theo năm
	GetYearlyComparisonReport(ctx context.Context) ([]GetYearlyComparisonReportRow, error)
	HoldSeat(ctx context.Context, arg HoldSeatParams) error
	IncrementBlogLikes(ctx context.Context, id int32) error
	IncrementBlogViews(ctx context.Context, id int32) error
	InvalidateAllOTPsForEmail(ctx context.Context, email string) error
	// Đánh dấu tất cả thông báo của user đã đọc
	MarkAllNotificationsAsRead(ctx context.Context, nguoiDungID pgtype.UUID) error
	MarkContactAsRead(ctx context.Context, id int32) (LienHe, error)
	// Đánh dấu thông báo đã đọc
	MarkNotificationAsRead(ctx context.Context, id int32) (ThongBao, error)
	// Lấy danh sách tour của nhà cung cấp
	OptionTour(ctx context.Context, nhaCungCapID pgtype.UUID) ([]OptionTourRow, error)
	// từ chối nhà cung cấp
	RejectSupplier(ctx context.Context, id pgtype.UUID) (NguoiDung, error)
	ResetPassword(ctx context.Context, arg ResetPasswordParams) (NguoiDung, error)
	RestoreSupplier(ctx context.Context, id pgtype.UUID) (NguoiDung, error)
	SearchBlogs(ctx context.Context, arg SearchBlogsParams) ([]SearchBlogsRow, error)
	SearchSuppliers(ctx context.Context, email string) ([]SearchSuppliersRow, error)
	// Đảm bảo bạn đã định nghĩa các CTE cần thiết (dd, dg, kh, ggt) như trong các bước trước.
	// Tôi sẽ gộp CTE tổng hợp thông tin tour cơ bản vào tour_info.
	// Câu truy vấn Chính: Tổng hợp tất cả thông tin và áp dụng các bộ lọc
	// LEFT JOIN các bộ lọc để áp dụng WHERE
	SearchTours(ctx context.Context, arg SearchToursParams) ([]SearchToursRow, error)
	SetPrimaryTourImage(ctx context.Context, arg SetPrimaryTourImageParams) error
	SoftDeleteSupplier(ctx context.Context, id pgtype.UUID) error
	// ===========================================
	// ADMIN STATISTICS QUERIES
	// ===========================================
	// =====================
	// 1. DASHBOARD OVERVIEW
	// =====================
	SupplierOptions(ctx context.Context) ([]SupplierOptionsRow, error)
	ToggleTourActive(ctx context.Context, id int32) (Tour, error)
	UpdateActivity(ctx context.Context, arg UpdateActivityParams) (HoatDongTrongNgay, error)
	UpdateBlog(ctx context.Context, arg UpdateBlogParams) (Blog, error)
	// Cập nhật trạng thái booking sau khi thanh toán thành công
	UpdateBookingPaymentStatus(ctx context.Context, arg UpdateBookingPaymentStatusParams) (DatCho, error)
	// Cập nhật phản hồi
	UpdateContactResponse(ctx context.Context, arg UpdateContactResponseParams) (PhanHoiLienHe, error)
	UpdateContactStatus(ctx context.Context, arg UpdateContactStatusParams) (LienHe, error)
	UpdateDeparture(ctx context.Context, arg UpdateDepartureParams) (KhoiHanhTour, error)
	UpdateDepartureCapacity(ctx context.Context, arg UpdateDepartureCapacityParams) (KhoiHanhTour, error)
	UpdateDepartureStat(ctx context.Context, id int32) (KhoiHanhTour, error)
	// Cập nhật hình ảnh cho điểm đến
	UpdateDestinationImage(ctx context.Context, arg UpdateDestinationImageParams) (DiemDen, error)
	UpdateDiscountTour(ctx context.Context, arg UpdateDiscountTourParams) (GiamGiaTour, error)
	UpdateGroupConfig(ctx context.Context, arg UpdateGroupConfigParams) (CauHinhNhomTour, error)
	UpdateHoatDongTrongNgay(ctx context.Context, arg UpdateHoatDongTrongNgayParams) (HoatDongTrongNgay, error)
	UpdateItinerary(ctx context.Context, arg UpdateItineraryParams) (LichTrinh, error)
	UpdateKhoiHanhTour(ctx context.Context, arg UpdateKhoiHanhTourParams) (KhoiHanhTour, error)
	UpdateLichTrinh(ctx context.Context, arg UpdateLichTrinhParams) (LichTrinh, error)
	// Cập nhật thông tin hành khách
	UpdatePassenger(ctx context.Context, arg UpdatePassengerParams) (HanhKhach, error)
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (NhaCungCap, error)
	UpdateSupplierAndUser(ctx context.Context) (UpdateSupplierAndUserRow, error)
	UpdateSupplierStatus(ctx context.Context, id pgtype.UUID) (NhaCungCap, error)
	UpdateTour(ctx context.Context, arg UpdateTourParams) (Tour, error)
	UpdateTourImage(ctx context.Context, arg UpdateTourImageParams) (AnhTour, error)
	UpdateTourStatus(ctx context.Context, arg UpdateTourStatusParams) (Tour, error)
	// Cập nhật thời lượng xem khi người dùng rời khỏi trang
	UpdateTourViewDuration(ctx context.Context, arg UpdateTourViewDurationParams) (LichSuXemTour, error)
	// Cập nhật trạng thái giao dịch (callback từ cổng thanh toán)
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (LichSuGiaoDich, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (NguoiDung, error)
	// Thêm dòng này
	UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) (NguoiDung, error)
	VerifyPasswordResetOTP(ctx context.Context, arg VerifyPasswordResetOTPParams) error
}

var _ Querier = (*Queries)(nil)
