// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/getAdminSummary": {
            "get": {
                "description": "Lấy tổng quan admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Lấy tổng quan admin",
                "responses": {
                    "200": {
                        "description": "Thành công",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/admin/getBookingsByMonth": {
            "get": {
                "description": "Thống kê số lượng đặt chỗ theo tháng trong năm",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Lấy đặt chỗ theo tháng",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Năm",
                        "name": "year",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/admin/getBookingsByStatus": {
            "get": {
                "description": "Lấy đơn đặt chỗ theo trạng thái",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Lấy đơn đặt chỗ theo trạng thái",
                "responses": {
                    "200": {
                        "description": "Thành công",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/admin/getNewUsersByMonth": {
            "get": {
                "description": "Thống kê số người dùng đăng ký mới theo tháng trong năm",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Lấy người dùng mới theo tháng",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Năm",
                        "name": "year",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/admin/getRevenueByDateRange": {
            "get": {
                "description": "Tổng doanh thu trong khoảng thời gian chỉ định",
                "tags": [
                    "admin"
                ],
                "summary": "Doanh thu theo khoảng thời gian",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ngày bắt đầu (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ngày kết thúc (YYYY-MM-DD)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/admin/getRevenueByMonth": {
            "get": {
                "description": "Lấy doanh thu theo tháng",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Lấy doanh thu theo tháng",
                "responses": {
                    "200": {
                        "description": "Thành công",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/admin/getRevenueBySupplier": {
            "get": {
                "description": "Thống kê doanh thu của từng nhà cung cấp",
                "tags": [
                    "admin"
                ],
                "summary": "Doanh thu theo nhà cung cấp",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Giới hạn",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/admin/getRevenueByYear": {
            "get": {
                "description": "Lấy doanh thu theo năm",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Lấy doanh thu theo năm",
                "responses": {
                    "200": {
                        "description": "Thành công",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/admin/getReviewStatsByTour": {
            "get": {
                "description": "Chi tiết phân bố rating cho các tour",
                "tags": [
                    "admin"
                ],
                "summary": "Thống kê đánh giá theo tour",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Giới hạn",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/admin/getTopCustomers": {
            "get": {
                "description": "Khách hàng chi tiêu nhiều nhất",
                "tags": [
                    "admin"
                ],
                "summary": "Top khách hàng",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Giới hạn",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/admin/getTopSuppliers": {
            "get": {
                "description": "Lấy danh sách nhà cung cấp hàng đầu theo số tour và booking",
                "tags": [
                    "admin"
                ],
                "summary": "Top nhà cung cấp",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Giới hạn kết quả",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/admin/getTopToursByBookings": {
            "get": {
                "description": "Lấy tour theo số đơn đặt chỗ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Lấy tour theo số đơn đặt chỗ",
                "responses": {
                    "200": {
                        "description": "Thành công",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/admin/getToursByCategory": {
            "get": {
                "description": "Thống kê số lượng tour và booking theo danh mục",
                "tags": [
                    "admin"
                ],
                "summary": "Tour theo danh mục",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/admin/getUpcomingDepartures": {
            "get": {
                "description": "Danh sách chuyến khởi hành sắp tới với thông tin chỗ trống",
                "tags": [
                    "admin"
                ],
                "summary": "Lịch khởi hành sắp tới",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Giới hạn",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/admin/getUserGrowth": {
            "get": {
                "description": "Số người dùng mới theo ngày trong khoảng thời gian",
                "tags": [
                    "admin"
                ],
                "summary": "Tăng trưởng người dùng",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ngày bắt đầu (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ngày kết thúc (YYYY-MM-DD)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/auth/createUser": {
            "post": {
                "description": "Tạo tài khoản từ OTP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Tạo tài khoản từ OTP",
                "parameters": [
                    {
                        "description": "Thông tin OTP",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.OTP"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Thành công",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "400": {
                        "description": "OTP không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/auth/createUserForm": {
            "post": {
                "description": "Tạo tài khoản từ form",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Tạo tài khoản từ form",
                "parameters": [
                    {
                        "description": "Thông tin tài khoản",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Thành công",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "409": {
                        "description": "Email đã được đăng ký",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/auth/getUserById/{id}": {
            "get": {
                "description": "Lấy thông tin user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Lấy thông tin user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID của user",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Thành công",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Đăng nhập",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Đăng nhập",
                "parameters": [
                    {
                        "description": "Thông tin đăng nhập",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Thành công",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Đăng xuất",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Đăng xuất",
                "responses": {
                    "200": {
                        "description": "Thành công",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/auth/updateUserById/{id}": {
            "put": {
                "description": "Cập nhật thông tin user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Cập nhật thông tin user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID của user",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin cập nhật",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GetUpdateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Thành công",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/storage/list": {
            "post": {
                "description": "List all images in the bucket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Storage"
                ],
                "summary": "List images in the bucket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder path",
                        "name": "folder_path",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.SupabaseFile"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/storage/upload": {
            "post": {
                "description": "Upload image with a specific path in the bucket",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Storage"
                ],
                "summary": "Upload image with a specific path in the bucket",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Image file to upload (JPEG, PNG, GIF, WebP, BMP)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Folder path",
                        "name": "folder_path",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/storage/upload-multiple": {
            "post": {
                "description": "Upload multiple images with a specific path in the bucket. You can select multiple files in the Swagger UI by holding Ctrl/Cmd while clicking files.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Storage"
                ],
                "summary": "Upload multiple images with a specific path in the bucket",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Image files to upload (JPEG, PNG, GIF, WebP, BMP) - select multiple files by holding Ctrl/Cmd",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Folder path",
                        "name": "folder_path",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "206": {
                        "description": "Partial Content",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/storage/upload-multiple-test": {
            "get": {
                "description": "Returns an HTML form for testing multiple file uploads",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Storage"
                ],
                "summary": "Test multiple file upload with HTML form",
                "responses": {
                    "200": {
                        "description": "HTML form",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tour/getAllTour": {
            "get": {
                "description": "Lấy danh sách tour",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tour"
                ],
                "summary": "Lấy danh sách tour",
                "responses": {
                    "200": {
                        "description": "Thành công",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/tour/getAllTourCategory": {
            "get": {
                "description": "Lấy danh mục tour",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tour"
                ],
                "summary": "Lấy danh mục tour",
                "responses": {
                    "200": {
                        "description": "Thành công",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/tour/getTourDetailByID/:id": {
            "get": {
                "description": "Lấy chi tiết tour",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tour"
                ],
                "summary": "Lấy chi tiết tour",
                "responses": {
                    "200": {
                        "description": "Thành công",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gin.H": {
            "type": "object",
            "additionalProperties": {}
        },
        "handler.SupabaseFile": {
            "type": "object",
            "properties": {
                "bucket_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_accessed_at": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "properties": {
                        "mimetype": {
                            "type": "string"
                        },
                        "size": {
                            "type": "integer"
                        }
                    }
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.CreateUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "models.GetUpdateUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ngay_cap_nhat": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.OTP": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "otp": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Travia API",
	Description:      "Travia API for travel management",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
