definitions:
  gin.H:
    additionalProperties: {}
    type: object
  handler.SupabaseFile:
    properties:
      bucket_id:
        type: string
      created_at:
        type: string
      id:
        type: string
      last_accessed_at:
        type: string
      metadata:
        properties:
          mimetype:
            type: string
          size:
            type: integer
        type: object
      name:
        type: string
      updated_at:
        type: string
    type: object
  models.CreateUser:
    properties:
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
      phone:
        type: string
    type: object
  models.GetUpdateUser:
    properties:
      email:
        type: string
      full_name:
        type: string
      id:
        type: string
      ngay_cap_nhat:
        type: string
      phone:
        type: string
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.OTP:
    properties:
      email:
        type: string
      otp:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Travia API for travel management
  termsOfService: http://swagger.io/terms/
  title: Travia API
  version: "1.0"
paths:
  /admin/getAdminSummary:
    get:
      consumes:
      - application/json
      description: Lấy tổng quan admin
      produces:
      - application/json
      responses:
        "200":
          description: Thành công
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Lỗi server
          schema:
            $ref: '#/definitions/gin.H'
      summary: Lấy tổng quan admin
      tags:
      - admin
  /admin/getBookingsByMonth:
    get:
      consumes:
      - application/json
      description: Thống kê số lượng đặt chỗ theo tháng trong năm
      parameters:
      - description: Năm
        in: query
        name: year
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: Lấy đặt chỗ theo tháng
      tags:
      - admin
  /admin/getBookingsByStatus:
    get:
      consumes:
      - application/json
      description: Lấy đơn đặt chỗ theo trạng thái
      produces:
      - application/json
      responses:
        "200":
          description: Thành công
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Lỗi server
          schema:
            $ref: '#/definitions/gin.H'
      summary: Lấy đơn đặt chỗ theo trạng thái
      tags:
      - admin
  /admin/getNewUsersByMonth:
    get:
      consumes:
      - application/json
      description: Thống kê số người dùng đăng ký mới theo tháng trong năm
      parameters:
      - description: Năm
        in: query
        name: year
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Lấy người dùng mới theo tháng
      tags:
      - admin
  /admin/getRevenueByDateRange:
    get:
      description: Tổng doanh thu trong khoảng thời gian chỉ định
      parameters:
      - description: Ngày bắt đầu (YYYY-MM-DD)
        in: query
        name: from
        required: true
        type: string
      - description: Ngày kết thúc (YYYY-MM-DD)
        in: query
        name: to
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: Doanh thu theo khoảng thời gian
      tags:
      - admin
  /admin/getRevenueByMonth:
    get:
      consumes:
      - application/json
      description: Lấy doanh thu theo tháng
      produces:
      - application/json
      responses:
        "200":
          description: Thành công
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Lỗi server
          schema:
            $ref: '#/definitions/gin.H'
      summary: Lấy doanh thu theo tháng
      tags:
      - admin
  /admin/getRevenueBySupplier:
    get:
      description: Thống kê doanh thu của từng nhà cung cấp
      parameters:
      - default: 10
        description: Giới hạn
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: Doanh thu theo nhà cung cấp
      tags:
      - admin
  /admin/getRevenueByYear:
    get:
      consumes:
      - application/json
      description: Lấy doanh thu theo năm
      produces:
      - application/json
      responses:
        "200":
          description: Thành công
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Lỗi server
          schema:
            $ref: '#/definitions/gin.H'
      summary: Lấy doanh thu theo năm
      tags:
      - admin
  /admin/getReviewStatsByTour:
    get:
      description: Chi tiết phân bố rating cho các tour
      parameters:
      - default: 10
        description: Giới hạn
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: Thống kê đánh giá theo tour
      tags:
      - admin
  /admin/getTopCustomers:
    get:
      description: Khách hàng chi tiêu nhiều nhất
      parameters:
      - default: 10
        description: Giới hạn
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: Top khách hàng
      tags:
      - admin
  /admin/getTopSuppliers:
    get:
      description: Lấy danh sách nhà cung cấp hàng đầu theo số tour và booking
      parameters:
      - default: 10
        description: Giới hạn kết quả
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: Top nhà cung cấp
      tags:
      - admin
  /admin/getTopToursByBookings:
    get:
      consumes:
      - application/json
      description: Lấy tour theo số đơn đặt chỗ
      produces:
      - application/json
      responses:
        "200":
          description: Thành công
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Lỗi server
          schema:
            $ref: '#/definitions/gin.H'
      summary: Lấy tour theo số đơn đặt chỗ
      tags:
      - admin
  /admin/getToursByCategory:
    get:
      description: Thống kê số lượng tour và booking theo danh mục
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: Tour theo danh mục
      tags:
      - admin
  /admin/getUpcomingDepartures:
    get:
      description: Danh sách chuyến khởi hành sắp tới với thông tin chỗ trống
      parameters:
      - default: 20
        description: Giới hạn
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: Lịch khởi hành sắp tới
      tags:
      - admin
  /admin/getUserGrowth:
    get:
      description: Số người dùng mới theo ngày trong khoảng thời gian
      parameters:
      - description: Ngày bắt đầu (YYYY-MM-DD)
        in: query
        name: from
        required: true
        type: string
      - description: Ngày kết thúc (YYYY-MM-DD)
        in: query
        name: to
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: Tăng trưởng người dùng
      tags:
      - admin
  /auth/createUser:
    post:
      consumes:
      - application/json
      description: Tạo tài khoản từ OTP
      parameters:
      - description: Thông tin OTP
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.OTP'
      produces:
      - application/json
      responses:
        "200":
          description: Thành công
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: OTP không hợp lệ
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Lỗi server
          schema:
            $ref: '#/definitions/gin.H'
      summary: Tạo tài khoản từ OTP
      tags:
      - auth
  /auth/createUserForm:
    post:
      consumes:
      - application/json
      description: Tạo tài khoản từ form
      parameters:
      - description: Thông tin tài khoản
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.CreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: Thành công
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Lỗi yêu cầu không hợp lệ
          schema:
            $ref: '#/definitions/gin.H'
        "409":
          description: Email đã được đăng ký
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Lỗi server
          schema:
            $ref: '#/definitions/gin.H'
      summary: Tạo tài khoản từ form
      tags:
      - auth
  /auth/getUserById/{id}:
    get:
      consumes:
      - application/json
      description: Lấy thông tin user
      parameters:
      - description: ID của user
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Thành công
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Lỗi yêu cầu không hợp lệ
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Lỗi server
          schema:
            $ref: '#/definitions/gin.H'
      summary: Lấy thông tin user
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Đăng nhập
      parameters:
      - description: Thông tin đăng nhập
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Thành công
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Lỗi yêu cầu không hợp lệ
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Lỗi server
          schema:
            $ref: '#/definitions/gin.H'
      summary: Đăng nhập
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Đăng xuất
      produces:
      - application/json
      responses:
        "200":
          description: Thành công
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Lỗi yêu cầu không hợp lệ
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Lỗi server
          schema:
            $ref: '#/definitions/gin.H'
      summary: Đăng xuất
      tags:
      - auth
  /auth/updateUserById/{id}:
    put:
      consumes:
      - application/json
      description: Cập nhật thông tin user
      parameters:
      - description: ID của user
        in: path
        name: id
        required: true
        type: string
      - description: Thông tin cập nhật
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.GetUpdateUser'
      produces:
      - application/json
      responses:
        "200":
          description: Thành công
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Lỗi yêu cầu không hợp lệ
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Lỗi server
          schema:
            $ref: '#/definitions/gin.H'
      summary: Cập nhật thông tin user
      tags:
      - auth
  /storage/list:
    post:
      consumes:
      - application/json
      description: List all images in the bucket
      parameters:
      - description: Folder path
        in: query
        name: folder_path
        type: string
      - description: Limit
        in: query
        name: limit
        type: string
      - description: Offset
        in: query
        name: offset
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.SupabaseFile'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: List images in the bucket
      tags:
      - Storage
  /storage/upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload image with a specific path in the bucket
      parameters:
      - description: Image file to upload (JPEG, PNG, GIF, WebP, BMP)
        in: formData
        name: file
        required: true
        type: file
      - description: Folder path
        in: formData
        name: folder_path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Upload image with a specific path in the bucket
      tags:
      - Storage
  /storage/upload-multiple:
    post:
      consumes:
      - multipart/form-data
      description: Upload multiple images with a specific path in the bucket. You
        can select multiple files in the Swagger UI by holding Ctrl/Cmd while clicking
        files.
      parameters:
      - description: Image files to upload (JPEG, PNG, GIF, WebP, BMP) - select multiple
          files by holding Ctrl/Cmd
        in: formData
        name: files
        required: true
        type: file
      - description: Folder path
        in: formData
        name: folder_path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "206":
          description: Partial Content
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Upload multiple images with a specific path in the bucket
      tags:
      - Storage
  /storage/upload-multiple-test:
    get:
      description: Returns an HTML form for testing multiple file uploads
      produces:
      - text/html
      responses:
        "200":
          description: HTML form
          schema:
            type: string
      summary: Test multiple file upload with HTML form
      tags:
      - Storage
  /tour/getAllTour:
    get:
      consumes:
      - application/json
      description: Lấy danh sách tour
      produces:
      - application/json
      responses:
        "200":
          description: Thành công
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Lỗi server
          schema:
            $ref: '#/definitions/gin.H'
      summary: Lấy danh sách tour
      tags:
      - tour
  /tour/getAllTourCategory:
    get:
      consumes:
      - application/json
      description: Lấy danh mục tour
      produces:
      - application/json
      responses:
        "200":
          description: Thành công
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Lỗi server
          schema:
            $ref: '#/definitions/gin.H'
      summary: Lấy danh mục tour
      tags:
      - tour
  /tour/getTourDetailByID/:id:
    get:
      consumes:
      - application/json
      description: Lấy chi tiết tour
      produces:
      - application/json
      responses:
        "200":
          description: Thành công
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Lỗi server
          schema:
            $ref: '#/definitions/gin.H'
      summary: Lấy chi tiết tour
      tags:
      - tour
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
